@startuml
class HMLRBGMessageEndpointBehavior {
    + HMLRBGMessageEndpointBehavior(username:string, password:string, logger:ILogger<LandRegistrySvc>)
}
Attribute <|-- HMLRBGMessageEndpointBehavior
IEndpointBehavior <|-- HMLRBGMessageEndpointBehavior
IOperationBehavior <|-- HMLRBGMessageEndpointBehavior
IContractBehavior <|-- HMLRBGMessageEndpointBehavior
@enduml
