// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace KnightFrank.Hub.LandRegistry.ServiceTests
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ApplicationEnquiryFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "ApplicationEnquiry.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "", "ApplicationEnquiry", "A short summary of the feature", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "ApplicationEnquiry")))
            {
                global::KnightFrank.Hub.LandRegistry.ServiceTests.ApplicationEnquiryFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void AppEnquiry(string test, string request, string userName, string password, string payload, string response, string messageDetails, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ApplicationEnquiry"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Test", test);
            argumentsOfScenario.Add("Request", request);
            argumentsOfScenario.Add("UserName", userName);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Payload", payload);
            argumentsOfScenario.Add("Response", response);
            argumentsOfScenario.Add("MessageDetails", messageDetails);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AppEnquiry", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
 testRunner.Given(string.Format("For a given property detail {0}", payload), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
 testRunner.And(string.Format("The Expected Message Details will be {0}", messageDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 9
 testRunner.And(string.Format("A different {0} and {1}", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
 testRunner.When(string.Format("I call the land registy {0}", request), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 11
 testRunner.Then(string.Format("I should receive {0}", response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AppEnquiry: 1-MultipleReturned")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "1-MultipleReturned")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "1-MultipleReturned")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"success-many-results\",\"ExternalRef\":\"ExternalRef\"},\"" +
            "Property\":{\"TitleNumber\": \"DN100\"}, \"Flags\":{\"ClosedAndContinued\":\"true\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"ExternalRef\"}" +
            "}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"Description\":\"Entries have been found against the Title Number requested.\",\"Dat" +
            "eTime\":\"2024-04-25T16:24:04\",\"Title\":{\"TitleNumber\":\"DN100\"},\"ApplicationEnquiry" +
            "\":[{\"ApplicationType\":\"Item80\",\"Expedited\":false,\"ApplicationReference\":\"132485\"" +
            ",\"PriorityDate\":\"0001-01-01T00:00:00\",\"PriorityTime\":\"0001-01-01T00:00:00\",\"Appl" +
            "icant\":\"Thomas Burnett\",\"ApplicationProgress\":{\"Description\":\"Received: Priority" +
            " Protected - Set-up activity underway\"},\"CustomerReference\":\"Burnett2223\",\"Appli" +
            "cationReceivedBy\":\"ApplicationReceivedByContentType\",\"PropertyDescription\":\"24 R" +
            "ose Bud Way, Liskeard\"},{\"ApplicationType\":\"Item20\",\"Expedited\":false,\"Applicati" +
            "onReference\":\"Z645XXX\",\"PriorityDate\":\"0001-01-01T00:00:00\",\"PriorityTime\":\"0001" +
            "-01-01T00:00:00\",\"Applicant\":\"Mr An Applicant\",\"ApplicationProgress\":{\"Descripti" +
            "on\":\"Received: Priority Protected - Awaiting Processing\"},\"CustomerReference\":\"A" +
            "pplicant999\",\"ApplicationReceivedBy\":\"ApplicationReceivedByContentType\"},{\"Appli" +
            "cationType\":\"Item30\",\"Expedited\":false,\"ApplicationReference\":\"F665XDX\",\"Priorit" +
            "yDate\":\"0001-01-01T00:00:00\",\"PriorityTime\":\"0001-01-01T00:00:00\",\"Applicant\":\"M" +
            "r Bee Applicant\",\"ApplicationProgress\":{\"Description\":\"Delayed - Prior Pending A" +
            "pplication(s) or Official Search(es)\",\"Correspondence\":[{\"CorrespondenceType\":\"I" +
            "tem20\",\"RequestedOnDate\":\"0001-01-01T00:00:00\",\"IssuedOnDate\":\"2019-03-22T00:00:" +
            "00\",\"ExpiresOnDate\":\"0001-01-01T00:00:00\"},{\"CorrespondenceType\":\"Item30\",\"Reque" +
            "stedOnDate\":\"0001-01-01T00:00:00\",\"IssuedOnDate\":\"2019-03-27T00:00:00\",\"ExpiresO" +
            "nDate\":\"0001-01-01T00:00:00\"}]},\"CustomerReference\":\"No customer reference recor" +
            "ded\",\"ApplicationReceivedBy\":\"ApplicationReceivedByContentType\"},{\"ApplicationTy" +
            "pe\":\"Item40\",\"Expedited\":false,\"ApplicationReference\":\"K771LFV\",\"PriorityDate\":\"" +
            "0001-01-01T00:00:00\",\"PriorityTime\":\"0001-01-01T00:00:00\",\"Applicant\":\"Mrs J App" +
            "licant\",\"ApplicationProgress\":{\"Description\":\"In Progress - Previous corresponde" +
            "nce\",\"Correspondence\":[{\"CorrespondenceType\":\"Item40\",\"RequestedOnDate\":\"2019-04" +
            "-03T00:00:00\",\"IssuedOnDate\":\"0001-01-01T00:00:00\",\"ExpiresOnDate\":\"0001-01-01T0" +
            "0:00:00\"}]},\"CustomerReference\":\"123/abc/8C\",\"ApplicationReceivedBy\":\"Applicatio" +
            "nReceivedByContentType\",\"PropertyDescription\":\"4 Angel Road, Northallerton\"},{\"A" +
            "pplicationType\":\"Item50\",\"Expedited\":false,\"ApplicationReference\":\"Y645XVW\",\"Pri" +
            "orityDate\":\"0001-01-01T00:00:00\",\"PriorityTime\":\"0001-01-01T00:00:00\",\"Applicant" +
            "\":\"Another Applicant\",\"ApplicationProgress\":{\"Description\":\"In Progress - No pre" +
            "vious correspondence\"},\"CustomerReference\":\"Applicant666\",\"ApplicationReceivedBy" +
            "\":\"ApplicationReceivedByContentType\",\"PropertyDescription\":\"No property descript" +
            "ion recorded for this application\"},{\"ApplicationType\":\"Item60\",\"Expedited\":fals" +
            "e,\"ApplicationReference\":\"F665SSS\",\"PriorityDate\":\"0001-01-01T00:00:00\",\"Priorit" +
            "yTime\":\"0001-01-01T00:00:00\",\"Applicant\":\"Mr Manifold\",\"ApplicationProgress\":{\"D" +
            "escription\":\"Delayed\",\"Correspondence\":[{\"CorrespondenceType\":\"Item40\",\"Requeste" +
            "dOnDate\":\"2019-06-10T00:00:00\",\"IssuedOnDate\":\"0001-01-01T00:00:00\",\"ExpiresOnDa" +
            "te\":\"0001-01-01T00:00:00\"},{\"CorrespondenceType\":\"Item10\",\"RequestedOnDate\":\"000" +
            "1-01-01T00:00:00\",\"IssuedOnDate\":\"2019-06-11T00:00:00\",\"ExpiresOnDate\":\"0001-01-" +
            "01T00:00:00\"}]},\"CustomerReference\":\"01012011156\",\"ApplicationReceivedBy\":\"Appli" +
            "cationReceivedByContentType\",\"PropertyDescription\":\"121b Halifax Road, London\"}," +
            "{\"ApplicationType\":\"Item70\",\"Expedited\":false,\"ApplicationReference\":\"U565LDE\",\"" +
            "PriorityDate\":\"0001-01-01T00:00:00\",\"PriorityTime\":\"0001-01-01T00:00:00\",\"Applic" +
            "ant\":\"The Third Earl of Doncaster\",\"ApplicationProgress\":{\"Description\":\"Delayed" +
            " - Extension of time granted\"},\"CustomerReference\":\"Doncaster354\",\"ApplicationRe" +
            "ceivedBy\":\"ApplicationReceivedByContentType\",\"PropertyDescription\":\"No property " +
            "description recorded for this application\"},{\"ApplicationType\":\"Item0\",\"Expedite" +
            "d\":false,\"ApplicationReference\":\"U565YYY\",\"PriorityDate\":\"0001-01-01T00:00:00\",\"" +
            "PriorityTime\":\"0001-01-01T00:00:00\",\"Applicant\":\"Steve Stone\",\"CustomerReference" +
            "\":\"Stone1234\",\"ApplicationReceivedBy\":\"ApplicationReceivedByContentType\"},{\"Appl" +
            "icationType\":\"Item10\",\"Expedited\":false,\"ApplicationReference\":\"U565KWA\",\"Priori" +
            "tyDate\":\"0001-01-01T00:00:00\",\"PriorityTime\":\"0001-01-01T00:00:00\",\"Applicant\":\"" +
            "Mr D Donoghue\",\"CustomerReference\":\"Donoghue SearchOfPart\",\"ApplicationReceivedB" +
            "y\":\"ApplicationReceivedByContentType\",\"PropertyDescription\":\"Flat 4, 136 Downtow" +
            "n, Portsmouth\"}]}")]
        public void AppEnquiry_1_MultipleReturned()
        {
#line 6
this.AppEnquiry("1-MultipleReturned", "ApplicationEnquiry", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"success-many-results\",\"ExternalRef\":\"ExternalRef\"},\"" +
                    "Property\":{\"TitleNumber\": \"DN100\"}, \"Flags\":{\"ClosedAndContinued\":\"true\"}}", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"ExternalRef\"}" +
                    "}}", "{\"Description\":\"Entries have been found against the Title Number requested.\",\"Dat" +
                    "eTime\":\"2024-04-25T16:24:04\",\"Title\":{\"TitleNumber\":\"DN100\"},\"ApplicationEnquiry" +
                    "\":[{\"ApplicationType\":\"Item80\",\"Expedited\":false,\"ApplicationReference\":\"132485\"" +
                    ",\"PriorityDate\":\"0001-01-01T00:00:00\",\"PriorityTime\":\"0001-01-01T00:00:00\",\"Appl" +
                    "icant\":\"Thomas Burnett\",\"ApplicationProgress\":{\"Description\":\"Received: Priority" +
                    " Protected - Set-up activity underway\"},\"CustomerReference\":\"Burnett2223\",\"Appli" +
                    "cationReceivedBy\":\"ApplicationReceivedByContentType\",\"PropertyDescription\":\"24 R" +
                    "ose Bud Way, Liskeard\"},{\"ApplicationType\":\"Item20\",\"Expedited\":false,\"Applicati" +
                    "onReference\":\"Z645XXX\",\"PriorityDate\":\"0001-01-01T00:00:00\",\"PriorityTime\":\"0001" +
                    "-01-01T00:00:00\",\"Applicant\":\"Mr An Applicant\",\"ApplicationProgress\":{\"Descripti" +
                    "on\":\"Received: Priority Protected - Awaiting Processing\"},\"CustomerReference\":\"A" +
                    "pplicant999\",\"ApplicationReceivedBy\":\"ApplicationReceivedByContentType\"},{\"Appli" +
                    "cationType\":\"Item30\",\"Expedited\":false,\"ApplicationReference\":\"F665XDX\",\"Priorit" +
                    "yDate\":\"0001-01-01T00:00:00\",\"PriorityTime\":\"0001-01-01T00:00:00\",\"Applicant\":\"M" +
                    "r Bee Applicant\",\"ApplicationProgress\":{\"Description\":\"Delayed - Prior Pending A" +
                    "pplication(s) or Official Search(es)\",\"Correspondence\":[{\"CorrespondenceType\":\"I" +
                    "tem20\",\"RequestedOnDate\":\"0001-01-01T00:00:00\",\"IssuedOnDate\":\"2019-03-22T00:00:" +
                    "00\",\"ExpiresOnDate\":\"0001-01-01T00:00:00\"},{\"CorrespondenceType\":\"Item30\",\"Reque" +
                    "stedOnDate\":\"0001-01-01T00:00:00\",\"IssuedOnDate\":\"2019-03-27T00:00:00\",\"ExpiresO" +
                    "nDate\":\"0001-01-01T00:00:00\"}]},\"CustomerReference\":\"No customer reference recor" +
                    "ded\",\"ApplicationReceivedBy\":\"ApplicationReceivedByContentType\"},{\"ApplicationTy" +
                    "pe\":\"Item40\",\"Expedited\":false,\"ApplicationReference\":\"K771LFV\",\"PriorityDate\":\"" +
                    "0001-01-01T00:00:00\",\"PriorityTime\":\"0001-01-01T00:00:00\",\"Applicant\":\"Mrs J App" +
                    "licant\",\"ApplicationProgress\":{\"Description\":\"In Progress - Previous corresponde" +
                    "nce\",\"Correspondence\":[{\"CorrespondenceType\":\"Item40\",\"RequestedOnDate\":\"2019-04" +
                    "-03T00:00:00\",\"IssuedOnDate\":\"0001-01-01T00:00:00\",\"ExpiresOnDate\":\"0001-01-01T0" +
                    "0:00:00\"}]},\"CustomerReference\":\"123/abc/8C\",\"ApplicationReceivedBy\":\"Applicatio" +
                    "nReceivedByContentType\",\"PropertyDescription\":\"4 Angel Road, Northallerton\"},{\"A" +
                    "pplicationType\":\"Item50\",\"Expedited\":false,\"ApplicationReference\":\"Y645XVW\",\"Pri" +
                    "orityDate\":\"0001-01-01T00:00:00\",\"PriorityTime\":\"0001-01-01T00:00:00\",\"Applicant" +
                    "\":\"Another Applicant\",\"ApplicationProgress\":{\"Description\":\"In Progress - No pre" +
                    "vious correspondence\"},\"CustomerReference\":\"Applicant666\",\"ApplicationReceivedBy" +
                    "\":\"ApplicationReceivedByContentType\",\"PropertyDescription\":\"No property descript" +
                    "ion recorded for this application\"},{\"ApplicationType\":\"Item60\",\"Expedited\":fals" +
                    "e,\"ApplicationReference\":\"F665SSS\",\"PriorityDate\":\"0001-01-01T00:00:00\",\"Priorit" +
                    "yTime\":\"0001-01-01T00:00:00\",\"Applicant\":\"Mr Manifold\",\"ApplicationProgress\":{\"D" +
                    "escription\":\"Delayed\",\"Correspondence\":[{\"CorrespondenceType\":\"Item40\",\"Requeste" +
                    "dOnDate\":\"2019-06-10T00:00:00\",\"IssuedOnDate\":\"0001-01-01T00:00:00\",\"ExpiresOnDa" +
                    "te\":\"0001-01-01T00:00:00\"},{\"CorrespondenceType\":\"Item10\",\"RequestedOnDate\":\"000" +
                    "1-01-01T00:00:00\",\"IssuedOnDate\":\"2019-06-11T00:00:00\",\"ExpiresOnDate\":\"0001-01-" +
                    "01T00:00:00\"}]},\"CustomerReference\":\"01012011156\",\"ApplicationReceivedBy\":\"Appli" +
                    "cationReceivedByContentType\",\"PropertyDescription\":\"121b Halifax Road, London\"}," +
                    "{\"ApplicationType\":\"Item70\",\"Expedited\":false,\"ApplicationReference\":\"U565LDE\",\"" +
                    "PriorityDate\":\"0001-01-01T00:00:00\",\"PriorityTime\":\"0001-01-01T00:00:00\",\"Applic" +
                    "ant\":\"The Third Earl of Doncaster\",\"ApplicationProgress\":{\"Description\":\"Delayed" +
                    " - Extension of time granted\"},\"CustomerReference\":\"Doncaster354\",\"ApplicationRe" +
                    "ceivedBy\":\"ApplicationReceivedByContentType\",\"PropertyDescription\":\"No property " +
                    "description recorded for this application\"},{\"ApplicationType\":\"Item0\",\"Expedite" +
                    "d\":false,\"ApplicationReference\":\"U565YYY\",\"PriorityDate\":\"0001-01-01T00:00:00\",\"" +
                    "PriorityTime\":\"0001-01-01T00:00:00\",\"Applicant\":\"Steve Stone\",\"CustomerReference" +
                    "\":\"Stone1234\",\"ApplicationReceivedBy\":\"ApplicationReceivedByContentType\"},{\"Appl" +
                    "icationType\":\"Item10\",\"Expedited\":false,\"ApplicationReference\":\"U565KWA\",\"Priori" +
                    "tyDate\":\"0001-01-01T00:00:00\",\"PriorityTime\":\"0001-01-01T00:00:00\",\"Applicant\":\"" +
                    "Mr D Donoghue\",\"CustomerReference\":\"Donoghue SearchOfPart\",\"ApplicationReceivedB" +
                    "y\":\"ApplicationReceivedByContentType\",\"PropertyDescription\":\"Flat 4, 136 Downtow" +
                    "n, Portsmouth\"}]}", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AppEnquiry: 2-OneReturned")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "2-OneReturned")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "2-OneReturned")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"success-one-result\",\"ExternalRef\":\"ExternalRef\"},\"Pr" +
            "operty\":{\"TitleNumber\": \"DN101\"}, \"Flags\":{\"ClosedAndContinued\":\"true\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"ExternalRef\"}" +
            "}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", @"{""Description"":""Entries have been found against the Title Number requested."",""DateTime"":""2024-04-24T18:04:12"",""Title"":{""TitleNumber"":""DN101""},""ApplicationEnquiry"":[{""ApplicationType"":""Item40"",""Expedited"":false,""ApplicationReference"":""ABR123Z"",""Applicant"":""Kevin Garett"",""ApplicationProgress"":{""Description"":""Delayed"",""Correspondence"":[{""CorrespondenceType"":""Item40""},{""CorrespondenceType"":""Item30""}]},""CustomerReference"":""rbud17/1"",""ApplicationReceivedBy"":""ApplicationReceivedByContentType"",""PropertyDescription"":""17 Rose Bud Way, Liskeard""}]}")]
        public void AppEnquiry_2_OneReturned()
        {
#line 6
this.AppEnquiry("2-OneReturned", "ApplicationEnquiry", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"success-one-result\",\"ExternalRef\":\"ExternalRef\"},\"Pr" +
                    "operty\":{\"TitleNumber\": \"DN101\"}, \"Flags\":{\"ClosedAndContinued\":\"true\"}}", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"ExternalRef\"}" +
                    "}}", @"{""Description"":""Entries have been found against the Title Number requested."",""DateTime"":""2024-04-24T18:04:12"",""Title"":{""TitleNumber"":""DN101""},""ApplicationEnquiry"":[{""ApplicationType"":""Item40"",""Expedited"":false,""ApplicationReference"":""ABR123Z"",""Applicant"":""Kevin Garett"",""ApplicationProgress"":{""Description"":""Delayed"",""Correspondence"":[{""CorrespondenceType"":""Item40""},{""CorrespondenceType"":""Item30""}]},""CustomerReference"":""rbud17/1"",""ApplicationReceivedBy"":""ApplicationReceivedByContentType"",""PropertyDescription"":""17 Rose Bud Way, Liskeard""}]}", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AppEnquiry: 3-AppRefOneReturned")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "3-AppRefOneReturned")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "3-AppRefOneReturned")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"application-reference-one-result\",\"ExternalRef\":\"Ext" +
            "ernalRef\"},\"ApplicationReference\":{\"Reference\": \"U565LDE\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"ExternalRef\"}" +
            "}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", @"{""Description"":""Entries have been found against the Application Reference requested."",""DateTime"":""2024-04-24T18:04:12"",""Title"":{""TitleNumber"":""DN100""},""ApplicationEnquiry"":[{""ApplicationType"":""Item30"",""Expedited"":false,""ApplicationReference"":""F665XDX"",""PriorityDate"":""0001-01-01T00:00:00"",""PriorityTime"":""0001-01-01T00:00:00"",""Applicant"":""Mr Bee Applicant"",""ApplicationProgress"":{""Description"":""Delayed - Prior Pending Application(s) or Official Search(es)"",""Correspondence"":[{""CorrespondenceType"":""Item20"",""RequestedOnDate"":""0001-01-01T00:00:00"",""IssuedOnDate"":""2019-03-22T00:00:00"",""ExpiresOnDate"":""0001-01-01T00:00:00""},{""CorrespondenceType"":""Item30"",""RequestedOnDate"":""0001-01-01T00:00:00"",""IssuedOnDate"":""2019-03-27T00:00:00"",""ExpiresOnDate"":""0001-01-01T00:00:00""}]},""CustomerReference"":""No customer reference recorded"",""ApplicationReceivedBy"":""ApplicationReceivedByContentType""}]}")]
        public void AppEnquiry_3_AppRefOneReturned()
        {
#line 6
this.AppEnquiry("3-AppRefOneReturned", "ApplicationEnquiry", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"application-reference-one-result\",\"ExternalRef\":\"Ext" +
                    "ernalRef\"},\"ApplicationReference\":{\"Reference\": \"U565LDE\"}}", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"ExternalRef\"}" +
                    "}}", @"{""Description"":""Entries have been found against the Application Reference requested."",""DateTime"":""2024-04-24T18:04:12"",""Title"":{""TitleNumber"":""DN100""},""ApplicationEnquiry"":[{""ApplicationType"":""Item30"",""Expedited"":false,""ApplicationReference"":""F665XDX"",""PriorityDate"":""0001-01-01T00:00:00"",""PriorityTime"":""0001-01-01T00:00:00"",""Applicant"":""Mr Bee Applicant"",""ApplicationProgress"":{""Description"":""Delayed - Prior Pending Application(s) or Official Search(es)"",""Correspondence"":[{""CorrespondenceType"":""Item20"",""RequestedOnDate"":""0001-01-01T00:00:00"",""IssuedOnDate"":""2019-03-22T00:00:00"",""ExpiresOnDate"":""0001-01-01T00:00:00""},{""CorrespondenceType"":""Item30"",""RequestedOnDate"":""0001-01-01T00:00:00"",""IssuedOnDate"":""2019-03-27T00:00:00"",""ExpiresOnDate"":""0001-01-01T00:00:00""}]},""CustomerReference"":""No customer reference recorded"",""ApplicationReceivedBy"":""ApplicationReceivedByContentType""}]}", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AppEnquiry: 4-AppRefClosed30Days")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "4-AppRefClosed30Days")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "4-AppRefClosed30Days")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"application-reference-thirty-days\",\"ExternalRef\":\"Ex" +
            "ternalRef\"},\"ApplicationReference\":{\"Reference\": \"G665YYG\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"ExternalRef\"}" +
            "}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"Description\":\"There is no Application pending against this Land Registry Refere" +
            "nce.\",\"DateTime\":\"2024-04-25T15:51:47\",\"RecentApplication\":{\"EndReason\":\"Item10\"" +
            ",\"EndDate\":\"2019-07-21T00:00:00\"}}")]
        public void AppEnquiry_4_AppRefClosed30Days()
        {
#line 6
this.AppEnquiry("4-AppRefClosed30Days", "ApplicationEnquiry", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"application-reference-thirty-days\",\"ExternalRef\":\"Ex" +
                    "ternalRef\"},\"ApplicationReference\":{\"Reference\": \"G665YYG\"}}", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"ExternalRef\"}" +
                    "}}", "{\"Description\":\"There is no Application pending against this Land Registry Refere" +
                    "nce.\",\"DateTime\":\"2024-04-25T15:51:47\",\"RecentApplication\":{\"EndReason\":\"Item10\"" +
                    ",\"EndDate\":\"2019-07-21T00:00:00\"}}", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AppEnquiry: 5-NoneReturned")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "5-NoneReturned")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "5-NoneReturned")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"success-no-results\",\"ExternalRef\":\"ExternalRef\"},\"Pr" +
            "operty\":{\"TitleNumber\": \"DN102\"}, \"Flags\":{\"ContinueIfFeeExceeds\":\"true\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"ExternalRef\"}" +
            "}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"Description\":\"There is no Application pending against this Title Number.\",\"Date" +
            "Time\":\"2024-04-25T15:33:25\",\"Title\":{\"TitleNumber\":\"DN102\"}}")]
        public void AppEnquiry_5_NoneReturned()
        {
#line 6
this.AppEnquiry("5-NoneReturned", "ApplicationEnquiry", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"success-no-results\",\"ExternalRef\":\"ExternalRef\"},\"Pr" +
                    "operty\":{\"TitleNumber\": \"DN102\"}, \"Flags\":{\"ContinueIfFeeExceeds\":\"true\"}}", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"ExternalRef\"}" +
                    "}}", "{\"Description\":\"There is no Application pending against this Title Number.\",\"Date" +
                    "Time\":\"2024-04-25T15:33:25\",\"Title\":{\"TitleNumber\":\"DN102\"}}", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AppEnquiry: 6-TitleIsClosed")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "6-TitleIsClosed")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "6-TitleIsClosed")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"closed-title-number\",\"ExternalRef\":\"ExternalRef\"},\"P" +
            "roperty\":{\"TitleNumber\": \"DN999\"}, \"Flags\":{\"ContinueIfFeeExceeds\":\"true\", \"Cont" +
            "inueIfFeeExceeds\":\"false\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\": {\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"" +
            ",\"Reason\":\"This title number is closed.\",\"Code\":\"bg.title.closed\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void AppEnquiry_6_TitleIsClosed()
        {
#line 6
this.AppEnquiry("6-TitleIsClosed", "ApplicationEnquiry", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"closed-title-number\",\"ExternalRef\":\"ExternalRef\"},\"P" +
                    "roperty\":{\"TitleNumber\": \"DN999\"}, \"Flags\":{\"ContinueIfFeeExceeds\":\"true\", \"Cont" +
                    "inueIfFeeExceeds\":\"false\"}}", "{\"Response\": {\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"" +
                    ",\"Reason\":\"This title number is closed.\",\"Code\":\"bg.title.closed\"}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AppEnquiry: 7-TitleIsClosedAndContinued")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "7-TitleIsClosedAndContinued")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "7-TitleIsClosedAndContinued")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"closed-and-continued\",\"ExternalRef\":\"ExternalRef\"},\"" +
            "Property\":{\"TitleNumber\": \"BK554444\"}, \"Flags\":{\"ClosedAndContinued\":\"true\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
            "\"RejectionResponse\":{\"Reason\":\"Title Number BK554444 has been closed and registr" +
            "ation continued under Title Number DT1551.\",\"Code\":\"bg.general.title.closedAndCo" +
            "ntinued\"}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void AppEnquiry_7_TitleIsClosedAndContinued()
        {
#line 6
this.AppEnquiry("7-TitleIsClosedAndContinued", "ApplicationEnquiry", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"closed-and-continued\",\"ExternalRef\":\"ExternalRef\"},\"" +
                    "Property\":{\"TitleNumber\": \"BK554444\"}, \"Flags\":{\"ClosedAndContinued\":\"true\"}}", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
                    "\"RejectionResponse\":{\"Reason\":\"Title Number BK554444 has been closed and registr" +
                    "ation continued under Title Number DT1551.\",\"Code\":\"bg.general.title.closedAndCo" +
                    "ntinued\"}}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AppEnquiry: 8-TitleIsNotFound")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "8-TitleIsNotFound")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "8-TitleIsNotFound")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"title-number-not-found\",\"ExternalRef\":\"ExternalRef\"}" +
            ",\"Property\":{\"TitleNumber\": \"DY100\"}, \"Flags\":{\"ClosedAndContinued\":\"true\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
            "\"RejectionResponse\":{\"Reason\":\"Title number is invalid.\",\"Code\":\"bg.title.invali" +
            "d\"}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void AppEnquiry_8_TitleIsNotFound()
        {
#line 6
this.AppEnquiry("8-TitleIsNotFound", "ApplicationEnquiry", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"title-number-not-found\",\"ExternalRef\":\"ExternalRef\"}" +
                    ",\"Property\":{\"TitleNumber\": \"DY100\"}, \"Flags\":{\"ClosedAndContinued\":\"true\"}}", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
                    "\"RejectionResponse\":{\"Reason\":\"Title number is invalid.\",\"Code\":\"bg.title.invali" +
                    "d\"}}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AppEnquiry: 9-AccessDenied")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "9-AccessDenied")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "9-AccessDenied")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"access-denied\",\"ExternalRef\":\"ExternalRef\"},\"Propert" +
            "y\":{\"TitleNumber\": \"DN100\"}, \"Flags\":{\"ClosedAndContinued\":\"true\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"SystemError\":{\"Description\":\"You do not have the necessary rights to access thi" +
            "s service.\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void AppEnquiry_9_AccessDenied()
        {
#line 6
this.AppEnquiry("9-AccessDenied", "ApplicationEnquiry", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"access-denied\",\"ExternalRef\":\"ExternalRef\"},\"Propert" +
                    "y\":{\"TitleNumber\": \"DN100\"}, \"Flags\":{\"ClosedAndContinued\":\"true\"}}", "{\"SystemError\":{\"Description\":\"You do not have the necessary rights to access thi" +
                    "s service.\"}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AppEnquiry: 10-OutOfHours")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "10-OutOfHours")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "10-OutOfHours")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"out-of-hours\",\"ExternalRef\":\"ExternalRef\"},\"Property" +
            "\":{\"TitleNumber\": \"DN100\"}, \"Flags\":{\"ClosedAndContinued\":\"true\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""out-of-hours"",""ExpectedResponseDateTime"":""2024-04-26T16:22:18"",""MessageDescription"":""Service is not currently available.System has queued your request,please poll at specified time.""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void AppEnquiry_10_OutOfHours()
        {
#line 6
this.AppEnquiry("10-OutOfHours", "ApplicationEnquiry", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"out-of-hours\",\"ExternalRef\":\"ExternalRef\"},\"Property" +
                    "\":{\"TitleNumber\": \"DN100\"}, \"Flags\":{\"ClosedAndContinued\":\"true\"}}", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""out-of-hours"",""ExpectedResponseDateTime"":""2024-04-26T16:22:18"",""MessageDescription"":""Service is not currently available.System has queued your request,please poll at specified time.""}}}", "", ((string[])(null)));
#line hidden
        }
        
        public virtual void AppEnquiryPoll(string test, string request, string userName, string password, string payload, string response, string messageDetails, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ApplicationEnquiryPoll"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Test", test);
            argumentsOfScenario.Add("Request", request);
            argumentsOfScenario.Add("UserName", userName);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Payload", payload);
            argumentsOfScenario.Add("Response", response);
            argumentsOfScenario.Add("MessageDetails", messageDetails);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AppEnquiryPoll", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 27
 testRunner.Given(string.Format("For a given property detail {0}", payload), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 28
 testRunner.And(string.Format("The Expected Message Details will be {0}", messageDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 29
 testRunner.And(string.Format("A different {0} and {1}", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 30
 testRunner.When(string.Format("I call the land registy {0}", request), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 31
 testRunner.Then(string.Format("I should receive {0}", response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AppEnquiryPoll: 11-NotYetProccessed")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ApplicationEnquiryPoll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "11-NotYetProccessed")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "11-NotYetProccessed")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "PollApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"pollstilloutofhours\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Acknowledgement\",\"Acknowledgement\":{\"UniqueMsgId\":\"pollsti" +
            "lloutofhours\",\"ExpectedResponseDateTime\":\"2011-07-20T08:36:26\",\"MessageDescripti" +
            "on\":\"Request has not yet been processed.\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void AppEnquiryPoll_11_NotYetProccessed()
        {
#line 26
this.AppEnquiryPoll("11-NotYetProccessed", "PollApplicationEnquiry", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"pollstilloutofhours\"}}", "{\"Response\":{\"Status\":\"Acknowledgement\",\"Acknowledgement\":{\"UniqueMsgId\":\"pollsti" +
                    "lloutofhours\",\"ExpectedResponseDateTime\":\"2011-07-20T08:36:26\",\"MessageDescripti" +
                    "on\":\"Request has not yet been processed.\"}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AppEnquiryPoll: 12-NoResults")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ApplicationEnquiryPoll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "12-NoResults")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "12-NoResults")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "PollApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"pollsuccessnoresults\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"ext ref\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"Description\":\"There is no Application pending against this Title Number.\",\"Date" +
            "Time\":\"2011-05-25T10:39:40\",\"Title\":{\"TitleNumber\":\"DN102\"}}")]
        public void AppEnquiryPoll_12_NoResults()
        {
#line 26
this.AppEnquiryPoll("12-NoResults", "PollApplicationEnquiry", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"pollsuccessnoresults\"}}", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"ext ref\"}}}", "{\"Description\":\"There is no Application pending against this Title Number.\",\"Date" +
                    "Time\":\"2011-05-25T10:39:40\",\"Title\":{\"TitleNumber\":\"DN102\"}}", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("AppEnquiryPoll: 13-Rejection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ApplicationEnquiryPoll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "13-Rejection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "13-Rejection")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "PollApplicationEnquiry")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"polltitlenumberclosed\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ext ref\",\"Rej" +
            "ectionResponse\":{\"Reason\":\"This title number is closed.\",\"Code\":\"bg.title.closed" +
            "\"}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void AppEnquiryPoll_13_Rejection()
        {
#line 26
this.AppEnquiryPoll("13-Rejection", "PollApplicationEnquiry", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"polltitlenumberclosed\"}}", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ext ref\",\"Rej" +
                    "ectionResponse\":{\"Reason\":\"This title number is closed.\",\"Code\":\"bg.title.closed" +
                    "\"}}}}", "", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
