Feature: DischargeActivity

A short summary of the feature

@DischargeActivity
Scenario: DischargeActivity
	Given For a given property detail <Payload>
	And The Expected Message Details will be <MessageDetails>
	And A different <UserName> and <Password>
	When I call the land registy <Request>
	Then I should receive <Response>
Examples: 
| Test                    | Request           | UserName  | Password   | Payload                                                                                                                                                                                                | Response                                                                                                                                                                                                                                                                                 | MessageDetails                                                                                                                                                                                           |
| 1-2Charges1ChargedDate  | DischargeActivity | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"success-two-discharges-one-match","ExternalRef":"ExternalRef"},"Property":{"TitleNumber":"DT984660","ChargeDate":"2019-02-13"},"Flags":{"ContinueIfFeeExceeds":"true"}}   | {"Response": {"Status": "Success","Results": {"ExternalReference": "ExternalRef"}}}                                                                                                                                                                                                      | {"Description":null,"ResultDateTime":"2024-04-29T12:14:06","TitleNumber":"DT984660","DischargeCount":2,"Discharges":[{"DischargeDate":"2019-09-15T00:00:00","ChargeProprietors":["Barclays Bank PLC"]}]} |
| 2-1Charge1ChargeDate    | DischargeActivity | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"success-one-discharge-one-match","ExternalRef":"ExternalRef"},"Property":{"TitleNumber":"NYK123654","ChargeDate":"2002-08-23"}}                                           | {"Response": {"Status": "Success","Results": {"ExternalReference": "ExternalRef"}}}                                                                                                                                                                                                      | {"Description":null,"ResultDateTime":"2024-04-29T14:37:47","TitleNumber":"NYK123654","DischargeCount":1,"Discharges":[]}                                                                                 |
| 3-2Charges2ChargeDates  | DischargeActivity | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"success-two-discharges-two-matches","ExternalRef":"ExternalRef"},"Property":{"TitleNumber":"DT984660","ChargeDate":"1995-02-13"},"Flags":{"ContinueIfFeeExceeds":"true"}} | {"Response": {"Status": "Success","Results": {"ExternalReference": "ExternalRef"}}}                                                                                                                                                                                                      | {"Description":null,"ResultDateTime":"2024-04-29T14:37:47","TitleNumber":"DT984660","DischargeCount":2,"Discharges":[{"DischargeDate":"2019-09-15T00:00:00","ChargeProprietors":["Barclays Bank PLC"]}]} |
| 4-0Charges0ChargeDates  | DischargeActivity | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"success-no-results","ExternalRef":"ExternalRef"},"Property":{"TitleNumber":"NYK567842","ChargeDate":"2007-10-26"},"Flags":{"ContinueIfFeeExceeds":"true"}}                | {"Response": {"Status": "Success","Results": {"ExternalReference": "ExternalRef"}}}                                                                                                                                                                                                      | {"Description":"No charges of this date have been discharged in the last 30 calendar days","ResultDateTime":"2024-04-29T15:02:13","TitleNumber":"NYK567842","DischargeCount":0,"Discharges":null}        |
| 5-ClosedAndContinued    | DischargeActivity | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"closed-and-continued","ExternalRef":"ExternalRef"},"Property":{"TitleNumber":"BK554444"}}                                                                                 | {"Response":{"Status":"Rejection","Rejection":{"ExternalReference":"ExternalRef","RejectionResponse":{"Reason":"Title Number BK554444 has been closed and registration continued under Title Number DT643551.","Code":"bg.general.title.closedAndContinued","Errors":[]}}}}              |                                                                                                                                                                                                          |
| 6-TitleNotFound         | DischargeActivity | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"title-number-not-found","ExternalRef":"ExternalRef"},"Property":{"TitleNumber":"NT99999"},"Flags":{"ContinueIfFeeExceeds":"true"}}                                        | {"Response":{"Status":"Rejection","Rejection":{"ExternalReference":"ExternalRef","RejectionResponse":{"Reason":"Title number is invalid.","Code":"bg.title.invalid","Errors":[]}}}}                                                                                                      |                                                                                                                                                                                                          |
| 7-OOH                   | DischargeActivity | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"out-of-hours","ExternalRef":"ExternalRef"},"Property":{"TitleNumber":"NYK456581"},"Flags":{"ContinueIfFeeExceeds":"true"}}                                                | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"out-of-hours","ExpectedResponseDateTime":"2024-04-30T14:37:49","MessageDescription":"Service is not currently available.System has queued your request,please poll at specified time.","HMLRReference":null}}} |                                                                                                                                                                                                          |
| 8-1Charge1ChargeDateC&C | DischargeActivity | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"success-one-discharge-one-match","ExternalRef":"ExternalRef"},"Property":{"TitleNumber":"NYK456113","ChargeDate":"1999-12-01"},"Flags":{"ContinueIfFeeExceeds":"true"}}   | {"Response": {"Status": "Success","Results": {"ExternalReference": "ExternalRef"}}}                                                                                                                                                                                                      | {"Description":null,"ResultDateTime":"2024-04-29T14:52:44","TitleNumber":"NYK123654","DischargeCount":1,"Discharges":[]}                                                                                 |
| 9-0ChargesC&C           | DischargeActivity | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"success-no-results","ExternalRef":"ExternalRef"},"Property":{"TitleNumber":"NYK456113","ChargeDate":"1999-12-15"},"Flags":{"ContinueIfFeeExceeds":"true"}}                | {"Response": {"Status": "Success","Results": {"ExternalReference": "ExternalRef"}}}                                                                                                                                                                                                      | {"Description":"No charges of this date have been discharged in the last 30 calendar days","ResultDateTime":"2024-04-29T15:10:18","TitleNumber":"NYK567842","DischargeCount":0,"Discharges":null}        |
| 10-1Charge0ChargeDate   | DischargeActivity | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"success-one-discharge-no-match","ExternalRef":"ExternalRef"},"Property":{"TitleNumber":"NYK567842","ChargeDate":"2001-05-18"},"Flags":{"ContinueIfFeeExceeds":"true"}}    | {"Response": {"Status": "Success","Results": {"ExternalReference": "ExternalRef"}}}                                                                                                                                                                                                      | {"Description":"No charges of this date have been discharged in the last 30 calendar days","ResultDateTime":"2024-04-29T14:37:38","TitleNumber":"NYK567842","DischargeCount":1,"Discharges":[]}          |
| 11-1Charge              | DischargeActivity | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"success-one-discharge","ExternalRef":"ExternalRef"},"Property":{"TitleNumber":"NYK123654"},"Flags":{"ContinueIfFeeExceeds":"true"}}                                       | {"Response": {"Status": "Success","Results": {"ExternalReference": "ExternalRef"}}}                                                                                                                                                                                                      | {"Description":null,"ResultDateTime":"2024-04-29T14:37:38","TitleNumber":"NYK123654","DischargeCount":1,"Discharges":[]}                                                                                 |
| 12-C&CUnderAnother      | DischargeActivity | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"closed-title-number","ExternalRef":"ExternalRef"},"Property":{"TitleNumber":"DT516100"},"Flags":{"ContinueIfFeeExceeds":"true"}}                                          | {"Response":{"Status":"Rejection","Rejection":{"ExternalReference":"ExternalRef","RejectionResponse":{"Reason":"This title number is closed.","Code":"bg.title.closed","Errors":[]}}}}                                                                                                   |                                                                                                                                                                                                          |
| 13-AccessIsDenied       | DischargeActivity | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"access-denied","ExternalRef":"ExternalRef"},"Property":{"TitleNumber":"DN100"},"Flags":{"ContinueIfFeeExceeds":"true"}}                                                   | {"SystemError":{"Description":"You do not have the necessary rights to access this service."}}                                                                                                                                                                                           |                                                                                                                                                                                                          |

@DischargeActivityPoll
Scenario: DischargeActivityPoll
	Given For a given property detail <Payload>
	And The Expected Message Details will be <MessageDetails>
	And A different <UserName> and <Password>
	When I call the land registy <Request>
	Then I should receive <Response>
Examples: 
| Test                | Request               | UserName  | Password   | Payload                                               | Response                                                                                                                                                                                                      | MessageDetails                                                                                                                                                                                    |
| 14-NotYetProccessed | PollDischargeActivity | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"pollstilloutofhours"}}   | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"pollstilloutofhours","ExpectedResponseDateTime":"2011-07-20T08:36:26","MessageDescription":"Request has not yet been processed."}}} |                                                                                                                                                                                                   |
| 15-NoResults        | PollDischargeActivity | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"pollsuccessnoresults"}}  | {"Response": {"Status": "Success","Results": {"ExternalReference": "D.Rippon-9874"}}}                                                                                                                         | {"Description":"No charges of this date have been discharged in the last 30 calendar days","ResultDateTime":"2019-10-11T13:38:10","TitleNumber":"NYK567842","DischargeCount":0,"Discharges":null} |
| 16-Rejection        | PollDischargeActivity | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"polltitlenumberclosed"}} | {"Response":{"Status":"Rejection","Acknowledgement":null,"Rejection":{"ExternalReference":"9874/2","RejectionResponse":{"Reason":"This title number is closed.","Code":"bg.title.closed","Errors":[]}}}}      |                                                                                                                                                                                                   |



