// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace KnightFrank.Hub.LandRegistry.ServiceTests
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class EnquiryByPropertyDescriptionFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "EnquiryByPropertyDescriptionTest.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "", "EnquiryByPropertyDescription", "\tIn order to validate the owners of a property\r\n\tAs a responcioble Estate Agent \r" +
                    "\n\tI want to be able to Call the HMLR and retrieve a Property Title", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "EnquiryByPropertyDescription")))
            {
                global::KnightFrank.Hub.LandRegistry.ServiceTests.EnquiryByPropertyDescriptionFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void Property(string test, string request, string payload, string response, string messageDetails, string expectedResponseDateTime, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "FindByDescription"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Test", test);
            argumentsOfScenario.Add("Request", request);
            argumentsOfScenario.Add("Payload", payload);
            argumentsOfScenario.Add("Response", response);
            argumentsOfScenario.Add("MessageDetails", messageDetails);
            argumentsOfScenario.Add("ExpectedResponseDateTime", expectedResponseDateTime);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Property", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
 testRunner.Given(string.Format("For a given property detail {0}", payload), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
 testRunner.And(string.Format("The Expected Message Details will be {0}", messageDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
 testRunner.When(string.Format("I call the land registy {0}", request), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 11
 testRunner.Then(string.Format("I should receive {0}", response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Property: 1a-Single")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FindByDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "1a-Single")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "1a-Single")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"ExternalRef\":\"ExternalRef\",\"CustomerRef\":\"CustomerReference\"},\"Pro" +
            "perty\":{\"PropertyNumber\": \"99\", \"PostCode\":\"TQ56 4HY\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"Titles\":[{\"TitleNumber\":\"ST500681\",\"Address\":{\"BuildingNumber\":\"99\",\"StreetName" +
            "\":\"FLAKE AVENUE\",\"CityName\":\"TORQUAY\",\"PostcodeZone\":\"TQ56 4HY\"},\"TenureTypeCode" +
            "\":\"Leasehold\"}]}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ExpectedResponseDateTime", "False")]
        public void Property_1A_Single()
        {
#line 7
this.Property("1a-Single", "EnquiryByPropertyDescription", "{\"Reference\":{\"ExternalRef\":\"ExternalRef\",\"CustomerRef\":\"CustomerReference\"},\"Pro" +
                    "perty\":{\"PropertyNumber\": \"99\", \"PostCode\":\"TQ56 4HY\"}}", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}", "{\"Titles\":[{\"TitleNumber\":\"ST500681\",\"Address\":{\"BuildingNumber\":\"99\",\"StreetName" +
                    "\":\"FLAKE AVENUE\",\"CityName\":\"TORQUAY\",\"PostcodeZone\":\"TQ56 4HY\"},\"TenureTypeCode" +
                    "\":\"Leasehold\"}]}", "False", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Property: 1b-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FindByDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "1b-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "1b-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"pollST500681\", \"ExternalRef\":\"ExternalRef\",\"Customer" +
            "Ref\":\"CustomerReference\"},\"Property\":{\"PropertyNumber\": \"99\", \"Line1\":\"Flake Ave" +
            "nue\", \"PostCode\":\"TQ56 4HY\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\": {\"Status\": \"Acknowledgement\",\"Acknowledgement\" : {\"UniqueMsgId\": \"po" +
            "llST500681\",\"MessageDescription\" : \"Service is not currently available.System ha" +
            "s queued your request,please poll at specified time.\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ExpectedResponseDateTime", "False")]
        public void Property_1B_OOH()
        {
#line 7
this.Property("1b-OOH", "EnquiryByPropertyDescription", "{\"Reference\":{\"UniqueMsgId\":\"pollST500681\", \"ExternalRef\":\"ExternalRef\",\"Customer" +
                    "Ref\":\"CustomerReference\"},\"Property\":{\"PropertyNumber\": \"99\", \"Line1\":\"Flake Ave" +
                    "nue\", \"PostCode\":\"TQ56 4HY\"}}", "{\"Response\": {\"Status\": \"Acknowledgement\",\"Acknowledgement\" : {\"UniqueMsgId\": \"po" +
                    "llST500681\",\"MessageDescription\" : \"Service is not currently available.System ha" +
                    "s queued your request,please poll at specified time.\"}}}", "", "False", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Property: 2a-Single")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FindByDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "2a-Single")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "2a-Single")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"ExternalRef\":\"ExternalRef\",\"CustomerRef\":\"CustomerReference\"},\"Pro" +
            "perty\":{\"PropertyNumber\": \"71\", \"Line1\":\"Allerburn Lea\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"": {""Status"": ""Rejection"",""Rejection"": {""ExternalReference"": ""ExternalRef"",""Reason"": ""Insufficient address details. Please provide flat/house and postcode OR flat, street and town OR house, street and town"",""Code"": ""bg.invalid.property.search.criteria""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ExpectedResponseDateTime", "False")]
        public void Property_2A_Single()
        {
#line 7
this.Property("2a-Single", "EnquiryByPropertyDescription", "{\"Reference\":{\"ExternalRef\":\"ExternalRef\",\"CustomerRef\":\"CustomerReference\"},\"Pro" +
                    "perty\":{\"PropertyNumber\": \"71\", \"Line1\":\"Allerburn Lea\"}}", @"{""Response"": {""Status"": ""Rejection"",""Rejection"": {""ExternalReference"": ""ExternalRef"",""Reason"": ""Insufficient address details. Please provide flat/house and postcode OR flat, street and town OR house, street and town"",""Code"": ""bg.invalid.property.search.criteria""}}}", "", "False", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Property: 2b-Single")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FindByDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "2b-Single")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "2b-Single")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"ExternalRef\":\"ExternalRef\",\"CustomerRef\":\"CustomerReference\"},\"Pro" +
            "perty\":{\"PropertyNumber\": \"71\", \"Line1\":\"Allerburn Lea\",\"City\":\"Alnwick\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"ExternalRef\"}" +
            "}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"Titles\": [{\"TitleNumber\": \"ND66318\",\"Address\": {\"BuildingNumber\": \"71\",\"StreetN" +
            "ame\": \"ALLERBURN LEA\",\"CityName\": \"ALNWICK\",\"PostcodeZone\": \"NE66 2NQ\"},\"TenureT" +
            "ypeCode\": \"Leasehold\"}]}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ExpectedResponseDateTime", "False")]
        public void Property_2B_Single()
        {
#line 7
this.Property("2b-Single", "EnquiryByPropertyDescription", "{\"Reference\":{\"ExternalRef\":\"ExternalRef\",\"CustomerRef\":\"CustomerReference\"},\"Pro" +
                    "perty\":{\"PropertyNumber\": \"71\", \"Line1\":\"Allerburn Lea\",\"City\":\"Alnwick\"}}", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"ExternalRef\"}" +
                    "}}", "{\"Titles\": [{\"TitleNumber\": \"ND66318\",\"Address\": {\"BuildingNumber\": \"71\",\"StreetN" +
                    "ame\": \"ALLERBURN LEA\",\"CityName\": \"ALNWICK\",\"PostcodeZone\": \"NE66 2NQ\"},\"TenureT" +
                    "ypeCode\": \"Leasehold\"}]}", "False", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Property: 2c-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FindByDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "2c-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "2c-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"pollND66318\", \"ExternalRef\":\"ExternalRef\",\"CustomerR" +
            "ef\":\"CustomerReference\"},\"Property\":{\"PropertyNumber\": \"71\", \"Line1\":\"Allerburn " +
            "Lea\",\"City\":\"Alnwick\"} }")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\": {\"Status\": \"Acknowledgement\",\"Acknowledgement\" : {\"UniqueMsgId\": \"po" +
            "llND66318\",\"MessageDescription\" : \"Service is not currently available.System has" +
            " queued your request,please poll at specified time.\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ExpectedResponseDateTime", "True")]
        public void Property_2C_OOH()
        {
#line 7
this.Property("2c-OOH", "EnquiryByPropertyDescription", "{\"Reference\":{\"UniqueMsgId\":\"pollND66318\", \"ExternalRef\":\"ExternalRef\",\"CustomerR" +
                    "ef\":\"CustomerReference\"},\"Property\":{\"PropertyNumber\": \"71\", \"Line1\":\"Allerburn " +
                    "Lea\",\"City\":\"Alnwick\"} }", "{\"Response\": {\"Status\": \"Acknowledgement\",\"Acknowledgement\" : {\"UniqueMsgId\": \"po" +
                    "llND66318\",\"MessageDescription\" : \"Service is not currently available.System has" +
                    " queued your request,please poll at specified time.\"}}}", "", "True", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Property: 3-Multi")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FindByDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "3-Multi")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "3-Multi")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"ExternalRef\":\"ExternalRef\",\"CustomerRef\":\"CustomerReference\"},\"Pro" +
            "perty\":{\"PropertyNumber\": \"27\", \"Line1\":\"Church Road\",\"City\":\"Exeter\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"ExternalRef\"}" +
            "}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", @"{""Titles"": [{""TitleNumber"": ""GR518195"",""Address"": {""BuildingNumber"": ""27"",	""StreetName"": ""CHURCH ROAD"",""CityName"": ""EXETER"",""PostcodeZone"": ""EX56 4HY""},""TenureTypeCode"": ""Leasehold""},{""TitleNumber"": ""GR518197"",""Address"": {""BuildingNumber"": ""27"",	""StreetName"": ""CHURCH ROAD"",""CityName"": ""EXETER"",""PostcodeZone"": ""EX56 4HY""},""TenureTypeCode"": ""Leasehold""}]}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ExpectedResponseDateTime", "False")]
        public void Property_3_Multi()
        {
#line 7
this.Property("3-Multi", "EnquiryByPropertyDescription", "{\"Reference\":{\"ExternalRef\":\"ExternalRef\",\"CustomerRef\":\"CustomerReference\"},\"Pro" +
                    "perty\":{\"PropertyNumber\": \"27\", \"Line1\":\"Church Road\",\"City\":\"Exeter\"}}", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"ExternalRef\"}" +
                    "}}", @"{""Titles"": [{""TitleNumber"": ""GR518195"",""Address"": {""BuildingNumber"": ""27"",	""StreetName"": ""CHURCH ROAD"",""CityName"": ""EXETER"",""PostcodeZone"": ""EX56 4HY""},""TenureTypeCode"": ""Leasehold""},{""TitleNumber"": ""GR518197"",""Address"": {""BuildingNumber"": ""27"",	""StreetName"": ""CHURCH ROAD"",""CityName"": ""EXETER"",""PostcodeZone"": ""EX56 4HY""},""TenureTypeCode"": ""Leasehold""}]}", "False", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Property: 4-NoProp")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FindByDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "4-NoProp")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "4-NoProp")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"ExternalRef\":\"ExternalRef\",\"CustomerRef\":\"CustomerReference\"},\"Pro" +
            "perty\":{\"PropertyNumber\": \"10\", \"Line1\":\"Knight Frank\",\"City\":\"Bristol\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"": {""Status"": ""Rejection"",""Rejection"": {""ExternalReference"": ""ExternalRef"",""Reason"": ""No title number has been identified from the data supplied. This does not necessarily mean that a register of a title does not exist but only that insufficient data has matched."",""Code"": ""bg.properties.nopropertyfound""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ExpectedResponseDateTime", "False")]
        public void Property_4_NoProp()
        {
#line 7
this.Property("4-NoProp", "EnquiryByPropertyDescription", "{\"Reference\":{\"ExternalRef\":\"ExternalRef\",\"CustomerRef\":\"CustomerReference\"},\"Pro" +
                    "perty\":{\"PropertyNumber\": \"10\", \"Line1\":\"Knight Frank\",\"City\":\"Bristol\"}}", @"{""Response"": {""Status"": ""Rejection"",""Rejection"": {""ExternalReference"": ""ExternalRef"",""Reason"": ""No title number has been identified from the data supplied. This does not necessarily mean that a register of a title does not exist but only that insufficient data has matched."",""Code"": ""bg.properties.nopropertyfound""}}}", "", "False", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Property: 5-ToMany")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FindByDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "5-ToMany")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "5-ToMany")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"ExternalRef\":\"ExternalRef\",\"CustomerRef\":\"CustomerReference\"},\"Pro" +
            "perty\":{\"PropertyName\": \"Caldey Island House\", \"City\":\"Cardiff\",\"PostCode\":\"CF11" +
            " 0JN\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"": {""Status"": ""Rejection"",""Rejection"": {""ExternalReference"": ""ExternalRef"",""Reason"": ""The property address you entered has matched with a large number of properties on our database. Please request again with refined address details."",	""Code"": ""bg.properties.toomanyproperties""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ExpectedResponseDateTime", "False")]
        public void Property_5_ToMany()
        {
#line 7
this.Property("5-ToMany", "EnquiryByPropertyDescription", "{\"Reference\":{\"ExternalRef\":\"ExternalRef\",\"CustomerRef\":\"CustomerReference\"},\"Pro" +
                    "perty\":{\"PropertyName\": \"Caldey Island House\", \"City\":\"Cardiff\",\"PostCode\":\"CF11" +
                    " 0JN\"}}", @"{""Response"": {""Status"": ""Rejection"",""Rejection"": {""ExternalReference"": ""ExternalRef"",""Reason"": ""The property address you entered has matched with a large number of properties on our database. Please request again with refined address details."",	""Code"": ""bg.properties.toomanyproperties""}}}", "", "False", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Property: 6-InvPostCodeFormat")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FindByDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "6-InvPostCodeFormat")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "6-InvPostCodeFormat")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"ExternalRef\":\"ExternalRef\",\"CustomerRef\":\"CustomerReference\"},\"Pro" +
            "perty\":{\"PostCode\":\"AB11 1CD\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"SystemError\":{\"Code\":null,\"Description\":\"Schema Errors have occured\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ExpectedResponseDateTime", "False")]
        public void Property_6_InvPostCodeFormat()
        {
#line 7
this.Property("6-InvPostCodeFormat", "EnquiryByPropertyDescription", "{\"Reference\":{\"ExternalRef\":\"ExternalRef\",\"CustomerRef\":\"CustomerReference\"},\"Pro" +
                    "perty\":{\"PostCode\":\"AB11 1CD\"}}", "{\"SystemError\":{\"Code\":null,\"Description\":\"Schema Errors have occured\"}}", "", "False", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Property: 7-InvPostCode")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FindByDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "7-InvPostCode")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "7-InvPostCode")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"ExternalRef\":\"ExternalRef\",\"CustomerRef\":\"CustomerReference\"},\"Pro" +
            "perty\":{\"PropertyNumber\": \"10\", \"PostCode\":\"PL1 8XX\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\": {\"Status\": \"Rejection\",\"Rejection\": {\"ExternalReference\": \"ExternalR" +
            "ef\",\"Reason\": \"Please provide valid postcode\",\"Code\": \"bg.postcode.invalid\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ExpectedResponseDateTime", "False")]
        public void Property_7_InvPostCode()
        {
#line 7
this.Property("7-InvPostCode", "EnquiryByPropertyDescription", "{\"Reference\":{\"ExternalRef\":\"ExternalRef\",\"CustomerRef\":\"CustomerReference\"},\"Pro" +
                    "perty\":{\"PropertyNumber\": \"10\", \"PostCode\":\"PL1 8XX\"}}", "{\"Response\": {\"Status\": \"Rejection\",\"Rejection\": {\"ExternalReference\": \"ExternalR" +
                    "ef\",\"Reason\": \"Please provide valid postcode\",\"Code\": \"bg.postcode.invalid\"}}}", "", "False", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Property: 8-InvAddress")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FindByDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "8-InvAddress")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "8-InvAddress")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"ExternalRef\":\"ExternalRef\",\"CustomerRef\":\"CustomerReference\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"SystemError\":{\"Code\":null,\"Description\":\"Schema Errors have occured\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ExpectedResponseDateTime", "")]
        public void Property_8_InvAddress()
        {
#line 7
this.Property("8-InvAddress", "EnquiryByPropertyDescription", "{\"Reference\":{\"ExternalRef\":\"ExternalRef\",\"CustomerRef\":\"CustomerReference\"}}", "{\"SystemError\":{\"Code\":null,\"Description\":\"Schema Errors have occured\"}}", "", "", ((string[])(null)));
#line hidden
        }
        
        public virtual void Access(string test, string request, string userName, string password, string payload, string response, string messageDetails, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Test", test);
            argumentsOfScenario.Add("Request", request);
            argumentsOfScenario.Add("UserName", userName);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Payload", payload);
            argumentsOfScenario.Add("Response", response);
            argumentsOfScenario.Add("MessageDetails", messageDetails);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Access", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 28
 testRunner.Given(string.Format("For a given property detail {0}", payload), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 29
 testRunner.And(string.Format("The Expected Message Details will be {0}", messageDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 30
 testRunner.And(string.Format("A different {0} and {1}", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 31
 testRunner.When(string.Format("I call the land registy {0}", request), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 32
 testRunner.Then(string.Format("I should receive {0}", response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Access: 9-AccessDenied")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "9-AccessDenied")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "9-AccessDenied")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser002")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"SystemError\":{\"Code\":null,\"Description\":\"Schema Errors have occured\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void Access_9_AccessDenied()
        {
#line 27
this.Access("9-AccessDenied", "EnquiryByPropertyDescription", "BGUser002", "landreg001", "", "{\"SystemError\":{\"Code\":null,\"Description\":\"Schema Errors have occured\"}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Access: 10-NotActivated")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "10-NotActivated")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "10-NotActivated")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser006")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"SystemError\":{\"Code\":null,\"Description\":\"Schema Errors have occured\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void Access_10_NotActivated()
        {
#line 27
this.Access("10-NotActivated", "EnquiryByPropertyDescription", "BGUser006", "landreg001", "", "{\"SystemError\":{\"Code\":null,\"Description\":\"Schema Errors have occured\"}}", "", ((string[])(null)));
#line hidden
        }
        
        public virtual void Polling(string test, string request, string messageId, string payload, string response, string messageDetails, string expectedResponseDateTime, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Test", test);
            argumentsOfScenario.Add("Request", request);
            argumentsOfScenario.Add("MessageId", messageId);
            argumentsOfScenario.Add("Payload", payload);
            argumentsOfScenario.Add("Response", response);
            argumentsOfScenario.Add("MessageDetails", messageDetails);
            argumentsOfScenario.Add("ExpectedResponseDateTime", expectedResponseDateTime);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Polling", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 42
 testRunner.Given(string.Format("For a given property detail {0}", payload), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 43
 testRunner.And(string.Format("The Expected Message Details will be {0}", messageDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 45
 testRunner.When(string.Format("I call the land registy {0}", request), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 46
 testRunner.Then(string.Format("I should receive {0}", response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Polling: 1c-Poll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "1c-Poll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "1c-Poll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "PollEnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageId", "pollST500681")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"pollST500681\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"er1\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"Titles\": [{\"TitleNumber\": \"ST500681\",\"Address\": {\"BuildingNumber\": \"99\",\t\"Stree" +
            "tName\": \"FLAKE AVENUE\",\"CityName\": \"TORQUAY\",\"PostcodeZone\": \"TQ56 4HY\"},\"Tenure" +
            "TypeCode\": \"Leasehold\"}]}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ExpectedResponseDateTime", "False")]
        public void Polling_1C_Poll()
        {
#line 41
this.Polling("1c-Poll", "PollEnquiryByPropertyDescription", "pollST500681", "{\"Reference\":{\"UniqueMsgId\":\"pollST500681\"}}", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"er1\"}}}", "{\"Titles\": [{\"TitleNumber\": \"ST500681\",\"Address\": {\"BuildingNumber\": \"99\",\t\"Stree" +
                    "tName\": \"FLAKE AVENUE\",\"CityName\": \"TORQUAY\",\"PostcodeZone\": \"TQ56 4HY\"},\"Tenure" +
                    "TypeCode\": \"Leasehold\"}]}", "False", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Polling: 2c-Poll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "2c-Poll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "2c-Poll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "PollEnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageId", "pollND66318")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"pollND66318\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"er21\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"Titles\": [{\"TitleNumber\": \"ND66318\",\"Address\": {\"BuildingNumber\": \"71\",\"StreetN" +
            "ame\": \"ALLERBURN LEA\",\"CityName\": \"ALNWICK\",\"PostcodeZone\": \"NE66 2NQ\"},\"TenureT" +
            "ypeCode\": \"Leasehold\"}]}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ExpectedResponseDateTime", "False")]
        public void Polling_2C_Poll()
        {
#line 41
this.Polling("2c-Poll", "PollEnquiryByPropertyDescription", "pollND66318", "{\"Reference\":{\"UniqueMsgId\":\"pollND66318\"}}", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"er21\"}}}", "{\"Titles\": [{\"TitleNumber\": \"ND66318\",\"Address\": {\"BuildingNumber\": \"71\",\"StreetN" +
                    "ame\": \"ALLERBURN LEA\",\"CityName\": \"ALNWICK\",\"PostcodeZone\": \"NE66 2NQ\"},\"TenureT" +
                    "ypeCode\": \"Leasehold\"}]}", "False", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Polling: 11-OOHPoll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "11-OOHPoll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "11-OOHPoll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "PollEnquiryByPropertyDescription")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageId", "polloutofhours")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"polloutofhours\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\": {\"Status\": \"Acknowledgement\",\"Acknowledgement\": {\"UniqueMsgId\": \"pol" +
            "loutofhours\",\"MessageDescription\": \"Service is not currently available.System ha" +
            "s queued your request,please poll at specified time.\\n\\t\\t\\t\\t\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ExpectedResponseDateTime", "True")]
        public void Polling_11_OOHPoll()
        {
#line 41
this.Polling("11-OOHPoll", "PollEnquiryByPropertyDescription", "polloutofhours", "{\"Reference\":{\"UniqueMsgId\":\"polloutofhours\"}}", "{\"Response\": {\"Status\": \"Acknowledgement\",\"Acknowledgement\": {\"UniqueMsgId\": \"pol" +
                    "loutofhours\",\"MessageDescription\": \"Service is not currently available.System ha" +
                    "s queued your request,please poll at specified time.\\n\\t\\t\\t\\t\"}}}", "", "True", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
