Feature: EnquiryByPropertyDescription
	In order to validate the owners of a property
	As a responcioble Estate Agent 
	I want to be able to Call the HMLR and retrieve a Property Title

@FindByDescription
Scenario: Property
	Given For a given property detail <Payload>
	And The Expected Message Details will be <MessageDetails>
	When I call the land registy <Request>
	Then I should receive <Response>
	#And New ExpectedResponseDateTime should be present <ExpectedResponseDateTime>
Examples:
| Test                | Request                      | Payload                                                                                                                                                                                        | Response                                                                                                                                                                                                                                                                                                                      | MessageDetails                                                                                                                                                                                                                                                                                                                                                      | ExpectedResponseDateTime |
| 1a-Single           | EnquiryByPropertyDescription | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"PropertyNumber": "99", "PostCode":"TQ56 4HY"}}                                                       | {"Response":{"Status":"Success","Results":{"ExternalReference":"ExternalRef"}}}                                                                                                                                                                                                                                               | {"Titles":[{"TitleNumber":"ST500681","Address":{"BuildingNumber":"99","StreetName":"FLAKE AVENUE","CityName":"TORQUAY","PostcodeZone":"TQ56 4HY"},"TenureTypeCode":"Leasehold"}]}                                                                                                                                                                                   | False                    |
| 1b-OOH              | EnquiryByPropertyDescription | {"Reference":{"UniqueMsgId":"pollST500681", "ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"PropertyNumber": "99", "Line1":"Flake Avenue", "PostCode":"TQ56 4HY"}} | {"Response": {"Status": "Acknowledgement","Acknowledgement" : {"UniqueMsgId": "pollST500681","MessageDescription" : "Service is not currently available.System has queued your request,please poll at specified time."}}}                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                     | False                    |
| 2a-Single           | EnquiryByPropertyDescription | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"PropertyNumber": "71", "Line1":"Allerburn Lea"}}                                                     | {"Response": {"Status": "Rejection","Rejection": {"ExternalReference": "ExternalRef","Reason": "Insufficient address details. Please provide flat/house and postcode OR flat, street and town OR house, street and town","Code": "bg.invalid.property.search.criteria"}}}                                                     |                                                                                                                                                                                                                                                                                                                                                                     | False                    |
| 2b-Single           | EnquiryByPropertyDescription | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"PropertyNumber": "71", "Line1":"Allerburn Lea","City":"Alnwick"}}                                    | {"Response": {"Status": "Success","Results": {"ExternalReference": "ExternalRef"}}}                                                                                                                                                                                                                                           | {"Titles": [{"TitleNumber": "ND66318","Address": {"BuildingNumber": "71","StreetName": "ALLERBURN LEA","CityName": "ALNWICK","PostcodeZone": "NE66 2NQ"},"TenureTypeCode": "Leasehold"}]}                                                                                                                                                                           | False                    |
| 2c-OOH              | EnquiryByPropertyDescription | {"Reference":{"UniqueMsgId":"pollND66318", "ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"PropertyNumber": "71", "Line1":"Allerburn Lea","City":"Alnwick"} }      | {"Response": {"Status": "Acknowledgement","Acknowledgement" : {"UniqueMsgId": "pollND66318","MessageDescription" : "Service is not currently available.System has queued your request,please poll at specified time."}}}                                                                                                      |                                                                                                                                                                                                                                                                                                                                                                     | True                     |
| 3-Multi             | EnquiryByPropertyDescription | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"PropertyNumber": "27", "Line1":"Church Road","City":"Exeter"}}                                       | {"Response": {"Status": "Success","Results": {"ExternalReference": "ExternalRef"}}}                                                                                                                                                                                                                                           | {"Titles": [{"TitleNumber": "GR518195","Address": {"BuildingNumber": "27",	"StreetName": "CHURCH ROAD","CityName": "EXETER","PostcodeZone": "EX56 4HY"},"TenureTypeCode": "Leasehold"},{"TitleNumber": "GR518197","Address": {"BuildingNumber": "27",	"StreetName": "CHURCH ROAD","CityName": "EXETER","PostcodeZone": "EX56 4HY"},"TenureTypeCode": "Leasehold"}]} | False                    |
| 4-NoProp            | EnquiryByPropertyDescription | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"PropertyNumber": "10", "Line1":"Knight Frank","City":"Bristol"}}                                     | {"Response": {"Status": "Rejection","Rejection": {"ExternalReference": "ExternalRef","Reason": "No title number has been identified from the data supplied. This does not necessarily mean that a register of a title does not exist but only that insufficient data has matched.","Code": "bg.properties.nopropertyfound"}}} |                                                                                                                                                                                                                                                                                                                                                                     | False                    |
| 5-ToMany            | EnquiryByPropertyDescription | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"PropertyName": "Caldey Island House", "City":"Cardiff","PostCode":"CF11 0JN"}}                       | {"Response": {"Status": "Rejection","Rejection": {"ExternalReference": "ExternalRef","Reason": "The property address you entered has matched with a large number of properties on our database. Please request again with refined address details.",	"Code": "bg.properties.toomanyproperties"}}}                             |                                                                                                                                                                                                                                                                                                                                                                     | False                    |
| 6-InvPostCodeFormat | EnquiryByPropertyDescription | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"PostCode":"AB11 1CD"}}                                                                               | {"SystemError":{"Code":null,"Description":"Schema Errors have occured"}}                                                                                                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                                                                     | False                    |
| 7-InvPostCode       | EnquiryByPropertyDescription | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"PropertyNumber": "10", "PostCode":"PL1 8XX"}}                                                        | {"Response": {"Status": "Rejection","Rejection": {"ExternalReference": "ExternalRef","Reason": "Please provide valid postcode","Code": "bg.postcode.invalid"}}}                                                                                                                                                               |                                                                                                                                                                                                                                                                                                                                                                     | False                    |
| 8-InvAddress        | EnquiryByPropertyDescription | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"}}                                                                                                                  | {"SystemError":{"Code":null,"Description":"Schema Errors have occured"}}                                                                                                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                                                                     |                          |

Scenario: Access
	Given For a given property detail <Payload>
	And The Expected Message Details will be <MessageDetails>
	And A different <UserName> and <Password>
	When I call the land registy <Request>
	Then I should receive <Response>
Examples: 
| Test            | Request                      | UserName  | Password   | Payload | Response                                                                 | MessageDetails |
| 9-AccessDenied  | EnquiryByPropertyDescription | BGUser002 | landreg001 |         | {"SystemError":{"Code":null,"Description":"Schema Errors have occured"}} |                |
| 10-NotActivated | EnquiryByPropertyDescription | BGUser006 | landreg001 |         | {"SystemError":{"Code":null,"Description":"Schema Errors have occured"}} |                |

#| 9-AccessDenied  | EnquiryByPropertyDescription | BGUser002 | landreg001 | {"SystemError": {"Description": "One or more errors occurred. (Your account is locked. Please reset your password using Portal.)"}} |
#| 10-NotActivated | EnquiryByPropertyDescription | BGUser006 | landreg001 | {"SystemError": {"Description": "One or more errors occurred. (Please activate your account using Portal.)"}}|

Scenario: Polling
	Given For a given property detail <Payload>
	And The Expected Message Details will be <MessageDetails>
	#And A MessageId <MessageId>
	When I call the land registy <Request>
	Then I should receive <Response>
Examples: 
| Test       | Request                          | MessageId      | Payload                                        | Response                                                                                                                                                                                                                                    | MessageDetails                                                                                                                                                                             | ExpectedResponseDateTime |
| 1c-Poll    | PollEnquiryByPropertyDescription | pollST500681   | {"Reference":{"UniqueMsgId":"pollST500681"}}   | {"Response": {"Status": "Success","Results": {"ExternalReference": "er1"}}}                                                                                                                                                              | {"Titles": [{"TitleNumber": "ST500681","Address": {"BuildingNumber": "99",	"StreetName": "FLAKE AVENUE","CityName": "TORQUAY","PostcodeZone": "TQ56 4HY"},"TenureTypeCode": "Leasehold"}]} | False                    |
| 2c-Poll    | PollEnquiryByPropertyDescription | pollND66318    | {"Reference":{"UniqueMsgId":"pollND66318"}}    | {"Response": {"Status": "Success","Results": {"ExternalReference": "er21"}}}                                                                                                                                                             | {"Titles": [{"TitleNumber": "ND66318","Address": {"BuildingNumber": "71","StreetName": "ALLERBURN LEA","CityName": "ALNWICK","PostcodeZone": "NE66 2NQ"},"TenureTypeCode": "Leasehold"}]}  | False                    |
| 11-OOHPoll | PollEnquiryByPropertyDescription | polloutofhours | {"Reference":{"UniqueMsgId":"polloutofhours"}} | {"Response": {"Status": "Acknowledgement","Acknowledgement": {"UniqueMsgId": "polloutofhours","MessageDescription": "Service is not currently available.System has queued your request,please poll at specified time.\\n\\t\\t\\t\\t"}}} |                                                                                                                                                                                            | True                     |




