// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace KnightFrank.Hub.LandRegistry.ServiceTests
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class LandChargesFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "LandCharges.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "", "LandCharges", "A short summary of the feature", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "LandCharges")))
            {
                global::KnightFrank.Hub.LandRegistry.ServiceTests.LandChargesFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void LandChargesBankruptcySearch(string test, string request, string userName, string password, string payload, string response, string messageDetails, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "LandChargesBankruptcySearch"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Test", test);
            argumentsOfScenario.Add("Request", request);
            argumentsOfScenario.Add("UserName", userName);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Payload", payload);
            argumentsOfScenario.Add("Response", response);
            argumentsOfScenario.Add("MessageDetails", messageDetails);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("LandChargesBankruptcySearch", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
 testRunner.Given(string.Format("For a given property detail {0}", payload), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
 testRunner.And(string.Format("The Expected Message Details will be {0}", messageDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 9
 testRunner.And(string.Format("A different {0} and {1}", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
 testRunner.When(string.Format("I call the land registy {0}", request), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 11
 testRunner.Then(string.Format("I should receive {0}", response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("LandChargesBankruptcySearch: 1-Standard")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LandCharges")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LandChargesBankruptcySearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "1-Standard")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "1-Standard")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "LCBankruptcySearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testsuccesselectronic"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""ExpectedPrice"":4.0},""SearchParty"":{""ContinueIfFeeExceeds"":false,""SearchType"":""10"", ""Applicants"":[{""Surname"":""Bloggs"",""Forename"":""Fred""}]}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"HMLRReference\":\"1234D\",\"ActualPrice\":6.0,\"Attachment\":{\"EmbeddedFileBinaryObjec" +
            "t\":{\"format\":\"PDF\"}},\"ResultTypeCode\":\"10\"}")]
        public void LandChargesBankruptcySearch_1_Standard()
        {
#line 6
this.LandChargesBankruptcySearch("1-Standard", "LCBankruptcySearch", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testsuccesselectronic"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""ExpectedPrice"":4.0},""SearchParty"":{""ContinueIfFeeExceeds"":false,""SearchType"":""10"", ""Applicants"":[{""Surname"":""Bloggs"",""Forename"":""Fred""}]}}", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}", "{\"HMLRReference\":\"1234D\",\"ActualPrice\":6.0,\"Attachment\":{\"EmbeddedFileBinaryObjec" +
                    "t\":{\"format\":\"PDF\"}},\"ResultTypeCode\":\"10\"}", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("LandChargesBankruptcySearch: 2-ComplexNames")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LandCharges")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LandChargesBankruptcySearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "2-ComplexNames")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "2-ComplexNames")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "LCBankruptcySearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testsuccesscomplex"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""ExpectedPrice"":4.0},""SearchParty"":{""ContinueIfFeeExceeds"":false,""SearchType"":""30"", ""Applicants"":[{""ComplexName"":""name1""},{""ComplexName"":""name2""}]}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"Description\":\"The application has been accepted. The certificate of result of s" +
            "earch will be sent by post\",\"ActualPrice\":12.0,\"ResultTypeCode\":\"30\"}")]
        public void LandChargesBankruptcySearch_2_ComplexNames()
        {
#line 6
this.LandChargesBankruptcySearch("2-ComplexNames", "LCBankruptcySearch", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testsuccesscomplex"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""ExpectedPrice"":4.0},""SearchParty"":{""ContinueIfFeeExceeds"":false,""SearchType"":""30"", ""Applicants"":[{""ComplexName"":""name1""},{""ComplexName"":""name2""}]}}", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}", "{\"Description\":\"The application has been accepted. The certificate of result of s" +
                    "earch will be sent by post\",\"ActualPrice\":12.0,\"ResultTypeCode\":\"30\"}", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("LandChargesBankruptcySearch: 3-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LandCharges")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LandChargesBankruptcySearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "3-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "3-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "LCBankruptcySearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"testoutofhours\",\"ExternalRef\":\"ExternalRef\",\"Custome" +
            "rRef\":\"Bguser1\"},\"Property\":{\"ExpectedPrice\":4.0},\"SearchParty\":{\"ContinueIfFeeE" +
            "xceeds\":false,\"SearchType\":\"10\", \"Applicants\":[{\"Surname\":\"Bloggs\",\"Forename\":\"F" +
            "red\"}]}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testoutofhours"",""ExpectedResponseDateTime"":""2024-04-27T15:57:31"",""MessageDescription"":""Service is not currently available.System has queued your request,please poll at specified time.""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void LandChargesBankruptcySearch_3_OOH()
        {
#line 6
this.LandChargesBankruptcySearch("3-OOH", "LCBankruptcySearch", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"testoutofhours\",\"ExternalRef\":\"ExternalRef\",\"Custome" +
                    "rRef\":\"Bguser1\"},\"Property\":{\"ExpectedPrice\":4.0},\"SearchParty\":{\"ContinueIfFeeE" +
                    "xceeds\":false,\"SearchType\":\"10\", \"Applicants\":[{\"Surname\":\"Bloggs\",\"Forename\":\"F" +
                    "red\"}]}}", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testoutofhours"",""ExpectedResponseDateTime"":""2024-04-27T15:57:31"",""MessageDescription"":""Service is not currently available.System has queued your request,please poll at specified time.""}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("LandChargesBankruptcySearch: 4-AccessDenied")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LandCharges")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LandChargesBankruptcySearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "4-AccessDenied")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "4-AccessDenied")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "LCBankruptcySearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"testaccessdenied\",\"ExternalRef\":\"ExternalRef\",\"Custo" +
            "merRef\":\"Bguser1\"},\"Property\":{\"ExpectedPrice\":4.0},\"SearchParty\":{\"ContinueIfFe" +
            "eExceeds\":false,\"SearchType\":\"10\", \"Applicants\":[{\"Surname\":\"Bloggs\",\"Forename\":" +
            "\"Fred\"}]}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"SystemError\":{\"Description\":\"You do not have the necessary rights to access thi" +
            "s service.\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void LandChargesBankruptcySearch_4_AccessDenied()
        {
#line 6
this.LandChargesBankruptcySearch("4-AccessDenied", "LCBankruptcySearch", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"testaccessdenied\",\"ExternalRef\":\"ExternalRef\",\"Custo" +
                    "merRef\":\"Bguser1\"},\"Property\":{\"ExpectedPrice\":4.0},\"SearchParty\":{\"ContinueIfFe" +
                    "eExceeds\":false,\"SearchType\":\"10\", \"Applicants\":[{\"Surname\":\"Bloggs\",\"Forename\":" +
                    "\"Fred\"}]}}", "{\"SystemError\":{\"Description\":\"You do not have the necessary rights to access thi" +
                    "s service.\"}}", "", ((string[])(null)));
#line hidden
        }
        
        public virtual void LandChargesBankruptcySearchPoll(string test, string request, string userName, string password, string payload, string response, string messageDetails, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "LandChargesBankruptcySearchPoll"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Test", test);
            argumentsOfScenario.Add("Request", request);
            argumentsOfScenario.Add("UserName", userName);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Payload", payload);
            argumentsOfScenario.Add("Response", response);
            argumentsOfScenario.Add("MessageDetails", messageDetails);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("LandChargesBankruptcySearchPoll", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 21
 testRunner.Given(string.Format("For a given property detail {0}", payload), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 22
 testRunner.And(string.Format("The Expected Message Details will be {0}", messageDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 23
 testRunner.And(string.Format("A different {0} and {1}", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 24
 testRunner.When(string.Format("I call the land registy {0}", request), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 25
 testRunner.Then(string.Format("I should receive {0}", response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("LandChargesBankruptcySearchPoll: 5-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LandCharges")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LandChargesBankruptcySearchPoll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "5-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "5-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "PollLCBankruptcySearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"pollstilloutofhours\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Acknowledgement\",\"Acknowledgement\":{\"UniqueMsgId\":\"testout" +
            "ofhours\",\"ExpectedResponseDateTime\":\"2011-06-16T10:37:29\",\"MessageDescription\":\"" +
            "Request has not yet been processed.\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void LandChargesBankruptcySearchPoll_5_OOH()
        {
#line 20
this.LandChargesBankruptcySearchPoll("5-OOH", "PollLCBankruptcySearch", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"pollstilloutofhours\"}}", "{\"Response\":{\"Status\":\"Acknowledgement\",\"Acknowledgement\":{\"UniqueMsgId\":\"testout" +
                    "ofhours\",\"ExpectedResponseDateTime\":\"2011-06-16T10:37:29\",\"MessageDescription\":\"" +
                    "Request has not yet been processed.\"}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("LandChargesBankruptcySearchPoll: 6-NoResults")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LandCharges")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LandChargesBankruptcySearchPoll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "6-NoResults")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "6-NoResults")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "PollLCBankruptcySearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"pollsuccessnoresults\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"Ext_Ref\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"HMLRReference\":\"10632D\",\"ActualPrice\":6.0,\"Attachment\":{\"EmbeddedFileBinaryObje" +
            "ct\":{\"format\":\"PDF\"}},\"ResultTypeCode\":\"10\"}")]
        public void LandChargesBankruptcySearchPoll_6_NoResults()
        {
#line 20
this.LandChargesBankruptcySearchPoll("6-NoResults", "PollLCBankruptcySearch", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"pollsuccessnoresults\"}}", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"Ext_Ref\"}}}", "{\"HMLRReference\":\"10632D\",\"ActualPrice\":6.0,\"Attachment\":{\"EmbeddedFileBinaryObje" +
                    "ct\":{\"format\":\"PDF\"}},\"ResultTypeCode\":\"10\"}", ((string[])(null)));
#line hidden
        }
        
        public virtual void LandChargesFullSearch(string test, string request, string userName, string password, string payload, string response, string messageDetails, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "LandChargesFullSearch"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Test", test);
            argumentsOfScenario.Add("Request", request);
            argumentsOfScenario.Add("UserName", userName);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Payload", payload);
            argumentsOfScenario.Add("Response", response);
            argumentsOfScenario.Add("MessageDetails", messageDetails);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("LandChargesFullSearch", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 33
 testRunner.Given(string.Format("For a given property detail {0}", payload), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 34
 testRunner.And(string.Format("The Expected Message Details will be {0}", messageDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 35
 testRunner.And(string.Format("A different {0} and {1}", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 36
 testRunner.When(string.Format("I call the land registy {0}", request), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 37
 testRunner.Then(string.Format("I should receive {0}", response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("LandChargesFullSearch: 1-Standard")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LandCharges")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LandChargesFullSearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "1-Standard")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "1-Standard")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "LCFullSearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testsuccesselectronic"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""ExpectedPrice"":2.0},""SearchParty"":{""ContinueIfFeeExceeds"":true,""SearchType"":""10"", ""Applicants"":[{""Surname"":""John"",""Forename"":""Smith"",""From"":""1970-01-01"",""To"":""2000-01-01""}],""County"":[""Avon"",""Blackpool"",""Cornwall"",""Devon"",""Essex"",""Glamorgan""]}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"HMLRReference\":\"1234D\",\"ActualPrice\":6.0,\"Attachment\":{\"EmbeddedFileBinaryObjec" +
            "t\":{\"format\":\"PDF\"}},\"ResultTypeCode\":\"10\"}")]
        public void LandChargesFullSearch_1_Standard()
        {
#line 32
this.LandChargesFullSearch("1-Standard", "LCFullSearch", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testsuccesselectronic"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""ExpectedPrice"":2.0},""SearchParty"":{""ContinueIfFeeExceeds"":true,""SearchType"":""10"", ""Applicants"":[{""Surname"":""John"",""Forename"":""Smith"",""From"":""1970-01-01"",""To"":""2000-01-01""}],""County"":[""Avon"",""Blackpool"",""Cornwall"",""Devon"",""Essex"",""Glamorgan""]}}", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}", "{\"HMLRReference\":\"1234D\",\"ActualPrice\":6.0,\"Attachment\":{\"EmbeddedFileBinaryObjec" +
                    "t\":{\"format\":\"PDF\"}},\"ResultTypeCode\":\"10\"}", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("LandChargesFullSearch: 2-ComplexNames")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LandCharges")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LandChargesFullSearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "2-ComplexNames")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "2-ComplexNames")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "LCFullSearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testsuccesscomplex"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""ExpectedPrice"":4.0},""SearchParty"":{""ContinueIfFeeExceeds"":true,""SearchType"":""30"", ""Applicants"":[{""ComplexName"":""name1"",""From"":""1900-01-01"",""To"":""2000-01-01""},{""ComplexName"":""name2"",""From"":""1900-01-01"",""To"":""2000-01-01""}],""County"":[""Avon"",""Blackpool"",""Cornwall"",""Devon"",""Essex"",""Glamorgan""]}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"Description\":\"The application has been accepted. The certificate of result of s" +
            "earch will be sent by post\",\"ActualPrice\":12.0,\"ResultTypeCode\":\"30\"}")]
        public void LandChargesFullSearch_2_ComplexNames()
        {
#line 32
this.LandChargesFullSearch("2-ComplexNames", "LCFullSearch", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testsuccesscomplex"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""ExpectedPrice"":4.0},""SearchParty"":{""ContinueIfFeeExceeds"":true,""SearchType"":""30"", ""Applicants"":[{""ComplexName"":""name1"",""From"":""1900-01-01"",""To"":""2000-01-01""},{""ComplexName"":""name2"",""From"":""1900-01-01"",""To"":""2000-01-01""}],""County"":[""Avon"",""Blackpool"",""Cornwall"",""Devon"",""Essex"",""Glamorgan""]}}", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}", "{\"Description\":\"The application has been accepted. The certificate of result of s" +
                    "earch will be sent by post\",\"ActualPrice\":12.0,\"ResultTypeCode\":\"30\"}", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("LandChargesFullSearch: 3-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LandCharges")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LandChargesFullSearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "3-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "3-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "LCFullSearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testoutofhours"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""Bguser1""},""Property"":{""ExpectedPrice"":4.0},""SearchParty"":{""ContinueIfFeeExceeds"":false,""SearchType"":""10"", ""Applicants"":[{""Surname"":""John"",""Forename"":""Smith"",""From"":""1970-01-01"",""To"":""2000-01-01""}],""County"":[""Avon"",""Blackpool"",""Cornwall"",""Devon"",""Essex"",""Glamorgan""]}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testoutofhours"",""ExpectedResponseDateTime"":""2024-04-27T15:57:31"",""MessageDescription"":""Service is not currently available.System has queued your request,please poll at specified time.""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void LandChargesFullSearch_3_OOH()
        {
#line 32
this.LandChargesFullSearch("3-OOH", "LCFullSearch", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testoutofhours"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""Bguser1""},""Property"":{""ExpectedPrice"":4.0},""SearchParty"":{""ContinueIfFeeExceeds"":false,""SearchType"":""10"", ""Applicants"":[{""Surname"":""John"",""Forename"":""Smith"",""From"":""1970-01-01"",""To"":""2000-01-01""}],""County"":[""Avon"",""Blackpool"",""Cornwall"",""Devon"",""Essex"",""Glamorgan""]}}", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testoutofhours"",""ExpectedResponseDateTime"":""2024-04-27T15:57:31"",""MessageDescription"":""Service is not currently available.System has queued your request,please poll at specified time.""}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("LandChargesFullSearch: 4-AccessDenied")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LandCharges")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LandChargesFullSearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "4-AccessDenied")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "4-AccessDenied")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "LCFullSearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testaccessdenied"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""Bguser1""},""Property"":{""ExpectedPrice"":4.0},""SearchParty"":{""ContinueIfFeeExceeds"":true,""SearchType"":""10"", ""Applicants"":[{""Surname"":""John"",""Forename"":""Smith"",""From"":""1970-01-01"",""To"":""2000-01-01""}],""County"":[""Avon"",""Blackpool"",""Cornwall"",""Devon"",""Essex"",""Glamorgan""]}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"SystemError\":{\"Description\":\"You do not have the necessary rights to access thi" +
            "s service.\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void LandChargesFullSearch_4_AccessDenied()
        {
#line 32
this.LandChargesFullSearch("4-AccessDenied", "LCFullSearch", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testaccessdenied"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""Bguser1""},""Property"":{""ExpectedPrice"":4.0},""SearchParty"":{""ContinueIfFeeExceeds"":true,""SearchType"":""10"", ""Applicants"":[{""Surname"":""John"",""Forename"":""Smith"",""From"":""1970-01-01"",""To"":""2000-01-01""}],""County"":[""Avon"",""Blackpool"",""Cornwall"",""Devon"",""Essex"",""Glamorgan""]}}", "{\"SystemError\":{\"Description\":\"You do not have the necessary rights to access thi" +
                    "s service.\"}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("LandChargesFullSearch: 5-InvalidNames")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LandCharges")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LandChargesFullSearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "5-InvalidNames")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "5-InvalidNames")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "LCFullSearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testinvalidname"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""Bguser1""},""Property"":{""ExpectedPrice"":4.0},""SearchParty"":{""ContinueIfFeeExceeds"":true,""SearchType"":""20"", ""Applicants"":[{""CompanyName"":""Big Company"",""From"":""1900-01-01"",""To"":""2000-01-01""}],""County"":[""Avon"",""Blackpool"",""Cornwall"",""Devon"",""Essex"",""Glamorgan""]}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Rejection"",""Rejection"":{""ExternalReference"":""ExternalRef"",""RejectionResponse"":{""Reason"":""BatchException"",""Code"":""BatchExceptionCode"",""Errors"":[{""Code"":""bg.invalid.search.name.detailed"",""Description"":""Search Name The Company is invalid""}]}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void LandChargesFullSearch_5_InvalidNames()
        {
#line 32
this.LandChargesFullSearch("5-InvalidNames", "LCFullSearch", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testinvalidname"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""Bguser1""},""Property"":{""ExpectedPrice"":4.0},""SearchParty"":{""ContinueIfFeeExceeds"":true,""SearchType"":""20"", ""Applicants"":[{""CompanyName"":""Big Company"",""From"":""1900-01-01"",""To"":""2000-01-01""}],""County"":[""Avon"",""Blackpool"",""Cornwall"",""Devon"",""Essex"",""Glamorgan""]}}", @"{""Response"":{""Status"":""Rejection"",""Rejection"":{""ExternalReference"":""ExternalRef"",""RejectionResponse"":{""Reason"":""BatchException"",""Code"":""BatchExceptionCode"",""Errors"":[{""Code"":""bg.invalid.search.name.detailed"",""Description"":""Search Name The Company is invalid""}]}}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("LandChargesFullSearch: 6-FeeMismatch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LandCharges")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LandChargesFullSearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "6-FeeMismatch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "6-FeeMismatch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "LCFullSearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testfeemismatch"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""Bguser1""},""Property"":{""ExpectedPrice"":1.0},""SearchParty"":{""ContinueIfFeeExceeds"":false,""SearchType"":""10"", ""Applicants"":[{""Surname"":""John"",""Forename"":""Smith"",""From"":""1970-01-01"",""To"":""2000-01-01""}],""County"":[""Avon"",""Blackpool"",""Cornwall"",""Devon"",""Essex"",""Glamorgan""]}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Rejection"",""Rejection"":{""ExternalReference"":""ExternalRef"",""RejectionResponse"":{""Reason"":""BatchException"",""Code"":""BatchExceptionCode"",""Errors"":[{""Code"":""bg.fee.feeMismatch"",""Description"":""Fee Amount provided does not match with the fee calculated by Land Registry.""}]}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void LandChargesFullSearch_6_FeeMismatch()
        {
#line 32
this.LandChargesFullSearch("6-FeeMismatch", "LCFullSearch", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testfeemismatch"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""Bguser1""},""Property"":{""ExpectedPrice"":1.0},""SearchParty"":{""ContinueIfFeeExceeds"":false,""SearchType"":""10"", ""Applicants"":[{""Surname"":""John"",""Forename"":""Smith"",""From"":""1970-01-01"",""To"":""2000-01-01""}],""County"":[""Avon"",""Blackpool"",""Cornwall"",""Devon"",""Essex"",""Glamorgan""]}}", @"{""Response"":{""Status"":""Rejection"",""Rejection"":{""ExternalReference"":""ExternalRef"",""RejectionResponse"":{""Reason"":""BatchException"",""Code"":""BatchExceptionCode"",""Errors"":[{""Code"":""bg.fee.feeMismatch"",""Description"":""Fee Amount provided does not match with the fee calculated by Land Registry.""}]}}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("LandChargesFullSearch: 7-InvalidCounty")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LandCharges")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LandChargesFullSearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "7-InvalidCounty")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "7-InvalidCounty")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "LCFullSearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testinvalidcounties"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""Bguser1""},""Property"":{""ExpectedPrice"":4.0},""SearchParty"":{""ContinueIfFeeExceeds"":false,""SearchType"":""10"", ""Applicants"":[{""Surname"":""John"",""Forename"":""Smith"",""From"":""1970-01-01"",""To"":""2000-01-01""}],""County"":[""Bristol""]}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Rejection"",""Rejection"":{""ExternalReference"":""ExternalRef"",""RejectionResponse"":{""Reason"":""BatchException"",""Code"":""BatchExceptionCode"",""Errors"":[{""Code"":""bg.full.invalid.county"",""Description"":""County/Administrative Area is invalid""}]}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void LandChargesFullSearch_7_InvalidCounty()
        {
#line 32
this.LandChargesFullSearch("7-InvalidCounty", "LCFullSearch", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testinvalidcounties"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""Bguser1""},""Property"":{""ExpectedPrice"":4.0},""SearchParty"":{""ContinueIfFeeExceeds"":false,""SearchType"":""10"", ""Applicants"":[{""Surname"":""John"",""Forename"":""Smith"",""From"":""1970-01-01"",""To"":""2000-01-01""}],""County"":[""Bristol""]}}", @"{""Response"":{""Status"":""Rejection"",""Rejection"":{""ExternalReference"":""ExternalRef"",""RejectionResponse"":{""Reason"":""BatchException"",""Code"":""BatchExceptionCode"",""Errors"":[{""Code"":""bg.full.invalid.county"",""Description"":""County/Administrative Area is invalid""}]}}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("LandChargesFullSearch: 8-MultiErrors")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LandCharges")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LandChargesFullSearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "8-MultiErrors")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "8-MultiErrors")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "LCFullSearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testmultipleerrors"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""Bguser1""},""Property"":{""ExpectedPrice"":2.0},""SearchParty"":{""ContinueIfFeeExceeds"":true,""SearchType"":""30"", ""Applicants"":[{""ComplexName"":""The Company"",""From"":""2000-01-01"",""To"":""1970-01-01""}],""County"":[""Bristol""]}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Rejection"",""Rejection"":{""ExternalReference"":""ExternalRef"",""RejectionResponse"":{""Reason"":""BatchException"",""Code"":""BatchExceptionCode"",""Errors"":[{""Code"":""bg.full.invalid.county"",""Description"":""County/Administrative Area is invalid""},{""Code"":""bg.full.invalid.name"",""Description"":""Not a valid limited company name""},{""Code"":""bg.full.invalid.dates"",""Description"":""Provide a Search To date that occurs after the Search From date""}]}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void LandChargesFullSearch_8_MultiErrors()
        {
#line 32
this.LandChargesFullSearch("8-MultiErrors", "LCFullSearch", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testmultipleerrors"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""Bguser1""},""Property"":{""ExpectedPrice"":2.0},""SearchParty"":{""ContinueIfFeeExceeds"":true,""SearchType"":""30"", ""Applicants"":[{""ComplexName"":""The Company"",""From"":""2000-01-01"",""To"":""1970-01-01""}],""County"":[""Bristol""]}}", @"{""Response"":{""Status"":""Rejection"",""Rejection"":{""ExternalReference"":""ExternalRef"",""RejectionResponse"":{""Reason"":""BatchException"",""Code"":""BatchExceptionCode"",""Errors"":[{""Code"":""bg.full.invalid.county"",""Description"":""County/Administrative Area is invalid""},{""Code"":""bg.full.invalid.name"",""Description"":""Not a valid limited company name""},{""Code"":""bg.full.invalid.dates"",""Description"":""Provide a Search To date that occurs after the Search From date""}]}}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("LandChargesFullSearch: 9-InvalidDates")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LandCharges")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LandChargesFullSearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "9-InvalidDates")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "9-InvalidDates")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "LCFullSearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testinvaliddates"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""Bguser1""},""Property"":{""ExpectedPrice"":2.0},""SearchParty"":{""ContinueIfFeeExceeds"":true,""SearchType"":""10"", ""Applicants"":[{""Surname"":""John"",""Forename"":""Smith"",""From"":""2000-01-01"",""To"":""1979-01-01""}],""County"":[""Avon"",""Blackpool"",""Cornwall"",""Devon"",""Essex"",""Glamorgan""]}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Rejection"",""Rejection"":{""ExternalReference"":""ExternalRef"",""RejectionResponse"":{""Reason"":""BatchException"",""Code"":""BatchExceptionCode"",""Errors"":[{""Code"":""bg.full.invalid.dates"",""Description"":""Provide a Search To date that occurs after the Search From date""}]}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void LandChargesFullSearch_9_InvalidDates()
        {
#line 32
this.LandChargesFullSearch("9-InvalidDates", "LCFullSearch", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testinvaliddates"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""Bguser1""},""Property"":{""ExpectedPrice"":2.0},""SearchParty"":{""ContinueIfFeeExceeds"":true,""SearchType"":""10"", ""Applicants"":[{""Surname"":""John"",""Forename"":""Smith"",""From"":""2000-01-01"",""To"":""1979-01-01""}],""County"":[""Avon"",""Blackpool"",""Cornwall"",""Devon"",""Essex"",""Glamorgan""]}}", @"{""Response"":{""Status"":""Rejection"",""Rejection"":{""ExternalReference"":""ExternalRef"",""RejectionResponse"":{""Reason"":""BatchException"",""Code"":""BatchExceptionCode"",""Errors"":[{""Code"":""bg.full.invalid.dates"",""Description"":""Provide a Search To date that occurs after the Search From date""}]}}}}", "", ((string[])(null)));
#line hidden
        }
        
        public virtual void LandChargesFullSearchPoll(string test, string request, string userName, string password, string payload, string response, string messageDetails, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "LandChargesFullSearchPoll"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Test", test);
            argumentsOfScenario.Add("Request", request);
            argumentsOfScenario.Add("UserName", userName);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Payload", payload);
            argumentsOfScenario.Add("Response", response);
            argumentsOfScenario.Add("MessageDetails", messageDetails);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("LandChargesFullSearchPoll", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 53
 testRunner.Given(string.Format("For a given property detail {0}", payload), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 54
 testRunner.And(string.Format("The Expected Message Details will be {0}", messageDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 55
 testRunner.And(string.Format("A different {0} and {1}", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 56
 testRunner.When(string.Format("I call the land registy {0}", request), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 57
 testRunner.Then(string.Format("I should receive {0}", response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("LandChargesFullSearchPoll: 10-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LandCharges")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LandChargesFullSearchPoll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "10-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "10-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "PollLCFullSearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"pollstilloutofhours\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Acknowledgement\",\"Acknowledgement\":{\"UniqueMsgId\":\"testout" +
            "ofhours\",\"ExpectedResponseDateTime\":\"2011-06-16T10:37:29\",\"MessageDescription\":\"" +
            "Request has not yet been processed.\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void LandChargesFullSearchPoll_10_OOH()
        {
#line 52
this.LandChargesFullSearchPoll("10-OOH", "PollLCFullSearch", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"pollstilloutofhours\"}}", "{\"Response\":{\"Status\":\"Acknowledgement\",\"Acknowledgement\":{\"UniqueMsgId\":\"testout" +
                    "ofhours\",\"ExpectedResponseDateTime\":\"2011-06-16T10:37:29\",\"MessageDescription\":\"" +
                    "Request has not yet been processed.\"}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("LandChargesFullSearchPoll: 11-NoResults")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LandCharges")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LandChargesFullSearchPoll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "11-NoResults")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "11-NoResults")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "PollLCFullSearch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"pollsuccessnoresults\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"Ext_ref\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"HMLRReference\":\"10631D\",\"ActualPrice\":6.00,\"Attachment\":{\"EmbeddedFileBinaryObj" +
            "ect\":{\"format\":\"PDF\"}},\"ResultTypeCode\":\"10\"}")]
        public void LandChargesFullSearchPoll_11_NoResults()
        {
#line 52
this.LandChargesFullSearchPoll("11-NoResults", "PollLCFullSearch", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"pollsuccessnoresults\"}}", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"Ext_ref\"}}}", "{\"HMLRReference\":\"10631D\",\"ActualPrice\":6.00,\"Attachment\":{\"EmbeddedFileBinaryObj" +
                    "ect\":{\"format\":\"PDF\"}},\"ResultTypeCode\":\"10\"}", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
