Feature: LandCharges

A short summary of the feature

@LandChargesBankruptcySearch
Scenario: LandChargesBankruptcySearch
	Given For a given property detail <Payload>
	And The Expected Message Details will be <MessageDetails>
	And A different <UserName> and <Password>
	When I call the land registy <Request>
	Then I should receive <Response>
Examples: 
| Test           | Request            | UserName  | Password   | Payload                                                                                                                                                                                                                                                                          | Response                                                                                                                                                                                                                                                              | MessageDetails                                                                                                                                        |
| 1-Standard     | LCBankruptcySearch | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testsuccesselectronic","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"ExpectedPrice":4.0},"SearchParty":{"ContinueIfFeeExceeds":false,"SearchType":"10", "Applicants":[{"Surname":"Bloggs","Forename":"Fred"}]}}       | {"Response":{"Status":"Success","Results":{"ExternalReference":"ExternalRef"}}}                                                                                                                                                                                       | {"HMLRReference":"1234D","ActualPrice":6.0,"Attachment":{"EmbeddedFileBinaryObject":{"format":"PDF"}},"ResultTypeCode":"10"}                          |
| 2-ComplexNames | LCBankruptcySearch | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testsuccesscomplex","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"ExpectedPrice":4.0},"SearchParty":{"ContinueIfFeeExceeds":false,"SearchType":"30", "Applicants":[{"ComplexName":"name1"},{"ComplexName":"name2"}]}} | {"Response":{"Status":"Success","Results":{"ExternalReference":"ExternalRef"}}}                                                                                                                                                                                       | {"Description":"The application has been accepted. The certificate of result of search will be sent by post","ActualPrice":12.0,"ResultTypeCode":"30"} |
| 3-OOH          | LCBankruptcySearch | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testoutofhours","ExternalRef":"ExternalRef","CustomerRef":"Bguser1"},"Property":{"ExpectedPrice":4.0},"SearchParty":{"ContinueIfFeeExceeds":false,"SearchType":"10", "Applicants":[{"Surname":"Bloggs","Forename":"Fred"}]}}                        | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"testoutofhours","ExpectedResponseDateTime":"2024-04-27T15:57:31","MessageDescription":"Service is not currently available.System has queued your request,please poll at specified time."}}} |                                                                                                                                                       |
| 4-AccessDenied | LCBankruptcySearch | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testaccessdenied","ExternalRef":"ExternalRef","CustomerRef":"Bguser1"},"Property":{"ExpectedPrice":4.0},"SearchParty":{"ContinueIfFeeExceeds":false,"SearchType":"10", "Applicants":[{"Surname":"Bloggs","Forename":"Fred"}]}}                      | {"SystemError":{"Description":"You do not have the necessary rights to access this service."}}                                                                                                                                                                        |                                                                                                                                                       |

@LandChargesBankruptcySearchPoll
Scenario: LandChargesBankruptcySearchPoll
	Given For a given property detail <Payload>
	And The Expected Message Details will be <MessageDetails>
	And A different <UserName> and <Password>
	When I call the land registy <Request>
	Then I should receive <Response>
Examples: 
| Test        | Request                | UserName  | Password   | Payload                                              | Response                                                                                                                                                                                                 | MessageDetails                                                                                                                |
| 5-OOH       | PollLCBankruptcySearch | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"pollstilloutofhours"}}  | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"testoutofhours","ExpectedResponseDateTime":"2011-06-16T10:37:29","MessageDescription":"Request has not yet been processed."}}} |                                                                                                                               |
| 6-NoResults | PollLCBankruptcySearch | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"pollsuccessnoresults"}} | {"Response":{"Status":"Success","Results":{"ExternalReference":"Ext_Ref"}}}                                                                                                                              | {"HMLRReference":"10632D","ActualPrice":6.0,"Attachment":{"EmbeddedFileBinaryObject":{"format":"PDF"}},"ResultTypeCode":"10"} |

@LandChargesFullSearch
Scenario: LandChargesFullSearch
	Given For a given property detail <Payload>
	And The Expected Message Details will be <MessageDetails>
	And A different <UserName> and <Password>
	When I call the land registy <Request>
	Then I should receive <Response>
Examples: 
| Test            | Request      | UserName  | Password   | Payload                                                                                                                                                                                                                                                                                                                                                                                                  | Response                                                                                                                                                                                                                                                                                                                                                                                                                                                             | MessageDetails                                                                                                                                        |
| 1-Standard      | LCFullSearch | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testsuccesselectronic","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"ExpectedPrice":2.0},"SearchParty":{"ContinueIfFeeExceeds":true,"SearchType":"10", "Applicants":[{"Surname":"John","Forename":"Smith","From":"1970-01-01","To":"2000-01-01"}],"County":["Avon","Blackpool","Cornwall","Devon","Essex","Glamorgan"]}}                                  | {"Response":{"Status":"Success","Results":{"ExternalReference":"ExternalRef"}}}                                                                                                                                                                                                                                                                                                                                                                                      | {"HMLRReference":"1234D","ActualPrice":6.0,"Attachment":{"EmbeddedFileBinaryObject":{"format":"PDF"}},"ResultTypeCode":"10"}                          |
| 2-ComplexNames  | LCFullSearch | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testsuccesscomplex","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"ExpectedPrice":4.0},"SearchParty":{"ContinueIfFeeExceeds":true,"SearchType":"30", "Applicants":[{"ComplexName":"name1","From":"1900-01-01","To":"2000-01-01"},{"ComplexName":"name2","From":"1900-01-01","To":"2000-01-01"}],"County":["Avon","Blackpool","Cornwall","Devon","Essex","Glamorgan"]}} | {"Response":{"Status":"Success","Results":{"ExternalReference":"ExternalRef"}}}                                                                                                                                                                                                                                                                                                                                                                                      | {"Description":"The application has been accepted. The certificate of result of search will be sent by post","ActualPrice":12.0,"ResultTypeCode":"30"} |
| 3-OOH           | LCFullSearch | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testoutofhours","ExternalRef":"ExternalRef","CustomerRef":"Bguser1"},"Property":{"ExpectedPrice":4.0},"SearchParty":{"ContinueIfFeeExceeds":false,"SearchType":"10", "Applicants":[{"Surname":"John","Forename":"Smith","From":"1970-01-01","To":"2000-01-01"}],"County":["Avon","Blackpool","Cornwall","Devon","Essex","Glamorgan"]}}                                                  | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"testoutofhours","ExpectedResponseDateTime":"2024-04-27T15:57:31","MessageDescription":"Service is not currently available.System has queued your request,please poll at specified time."}}}                                                                                                                                                                                                |                                                                                                                                                       |
| 4-AccessDenied  | LCFullSearch | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testaccessdenied","ExternalRef":"ExternalRef","CustomerRef":"Bguser1"},"Property":{"ExpectedPrice":4.0},"SearchParty":{"ContinueIfFeeExceeds":true,"SearchType":"10", "Applicants":[{"Surname":"John","Forename":"Smith","From":"1970-01-01","To":"2000-01-01"}],"County":["Avon","Blackpool","Cornwall","Devon","Essex","Glamorgan"]}}                                                 | {"SystemError":{"Description":"You do not have the necessary rights to access this service."}}                                                                                                                                                                                                                                                                                                                                                                       |                                                                                                                                                       |
| 5-InvalidNames  | LCFullSearch | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testinvalidname","ExternalRef":"ExternalRef","CustomerRef":"Bguser1"},"Property":{"ExpectedPrice":4.0},"SearchParty":{"ContinueIfFeeExceeds":true,"SearchType":"20", "Applicants":[{"CompanyName":"Big Company","From":"1900-01-01","To":"2000-01-01"}],"County":["Avon","Blackpool","Cornwall","Devon","Essex","Glamorgan"]}}                                                          | {"Response":{"Status":"Rejection","Rejection":{"ExternalReference":"ExternalRef","RejectionResponse":{"Reason":"BatchException","Code":"BatchExceptionCode","Errors":[{"Code":"bg.invalid.search.name.detailed","Description":"Search Name The Company is invalid"}]}}}}                                                                                                                                                                                             |                                                                                                                                                       |
| 6-FeeMismatch   | LCFullSearch | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testfeemismatch","ExternalRef":"ExternalRef","CustomerRef":"Bguser1"},"Property":{"ExpectedPrice":1.0},"SearchParty":{"ContinueIfFeeExceeds":false,"SearchType":"10", "Applicants":[{"Surname":"John","Forename":"Smith","From":"1970-01-01","To":"2000-01-01"}],"County":["Avon","Blackpool","Cornwall","Devon","Essex","Glamorgan"]}}                                                 | {"Response":{"Status":"Rejection","Rejection":{"ExternalReference":"ExternalRef","RejectionResponse":{"Reason":"BatchException","Code":"BatchExceptionCode","Errors":[{"Code":"bg.fee.feeMismatch","Description":"Fee Amount provided does not match with the fee calculated by Land Registry."}]}}}}                                                                                                                                                                |                                                                                                                                                       |
| 7-InvalidCounty | LCFullSearch | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testinvalidcounties","ExternalRef":"ExternalRef","CustomerRef":"Bguser1"},"Property":{"ExpectedPrice":4.0},"SearchParty":{"ContinueIfFeeExceeds":false,"SearchType":"10", "Applicants":[{"Surname":"John","Forename":"Smith","From":"1970-01-01","To":"2000-01-01"}],"County":["Bristol"]}}                                                                                             | {"Response":{"Status":"Rejection","Rejection":{"ExternalReference":"ExternalRef","RejectionResponse":{"Reason":"BatchException","Code":"BatchExceptionCode","Errors":[{"Code":"bg.full.invalid.county","Description":"County/Administrative Area is invalid"}]}}}}                                                                                                                                                                                                   |                                                                                                                                                       |
| 8-MultiErrors   | LCFullSearch | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testmultipleerrors","ExternalRef":"ExternalRef","CustomerRef":"Bguser1"},"Property":{"ExpectedPrice":2.0},"SearchParty":{"ContinueIfFeeExceeds":true,"SearchType":"30", "Applicants":[{"ComplexName":"The Company","From":"2000-01-01","To":"1970-01-01"}],"County":["Bristol"]}}                                                                                                       | {"Response":{"Status":"Rejection","Rejection":{"ExternalReference":"ExternalRef","RejectionResponse":{"Reason":"BatchException","Code":"BatchExceptionCode","Errors":[{"Code":"bg.full.invalid.county","Description":"County/Administrative Area is invalid"},{"Code":"bg.full.invalid.name","Description":"Not a valid limited company name"},{"Code":"bg.full.invalid.dates","Description":"Provide a Search To date that occurs after the Search From date"}]}}}} |                                                                                                                                                       |
| 9-InvalidDates  | LCFullSearch | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testinvaliddates","ExternalRef":"ExternalRef","CustomerRef":"Bguser1"},"Property":{"ExpectedPrice":2.0},"SearchParty":{"ContinueIfFeeExceeds":true,"SearchType":"10", "Applicants":[{"Surname":"John","Forename":"Smith","From":"2000-01-01","To":"1979-01-01"}],"County":["Avon","Blackpool","Cornwall","Devon","Essex","Glamorgan"]}}                                                 | {"Response":{"Status":"Rejection","Rejection":{"ExternalReference":"ExternalRef","RejectionResponse":{"Reason":"BatchException","Code":"BatchExceptionCode","Errors":[{"Code":"bg.full.invalid.dates","Description":"Provide a Search To date that occurs after the Search From date"}]}}}}                                                                                                                                                                          |                                                                                                                                                       |


@LandChargesFullSearchPoll
Scenario: LandChargesFullSearchPoll
	Given For a given property detail <Payload>
	And The Expected Message Details will be <MessageDetails>
	And A different <UserName> and <Password>
	When I call the land registy <Request>
	Then I should receive <Response>
Examples: 
| Test         | Request          | UserName  | Password   | Payload                                              | Response                                                                                                                                                                                                 | MessageDetails                                                                                                                 |
| 10-OOH       | PollLCFullSearch | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"pollstilloutofhours"}}  | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"testoutofhours","ExpectedResponseDateTime":"2011-06-16T10:37:29","MessageDescription":"Request has not yet been processed."}}} |                                                                                                                                |
| 11-NoResults | PollLCFullSearch | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"pollsuccessnoresults"}} | {"Response":{"Status":"Success","Results":{"ExternalReference":"Ext_ref"}}}                                                                                                                              | {"HMLRReference":"10631D","ActualPrice":6.00,"Attachment":{"EmbeddedFileBinaryObject":{"format":"PDF"}},"ResultTypeCode":"10"} |

