Feature: OfficialSearchWhole

A short summary of the feature

@OfficialSearchWhole
Scenario: OfficialSearchWhole
	Given For a given property detail <Payload>
	And The Expected Message Details will be <MessageDetails>
	And A different <UserName> and <Password>
	When I call the land registy <Request>
	Then I should receive <Response>
Examples: 
| Test                      | Request             | UserName  | Password   | Payload                                                                                                                                                                                                                                                                                                                                                                                                      | Response                                                                                                                                                                                                                                                                                                                               | MessageDetails                                                                                                                                              |
| 1-InvalidTitle            | OfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testtitlenumber","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"IV123456","ExpectedPrice":12.0},"PrioritySearch":{"PriorityType":"Purchase","PropertyDescription":"A House","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit"}}                                            | {"Response":{"Status":"Rejection","Rejection":{"ExternalReference":"ExternalRef","RejectionResponse":{"Reason":"Title number is invalid.","Code":"bg.title.invalid","Errors":[]}}}}                                                                                                                                                    |                                                                                                                                                             |
| 2-CautionTitle            | OfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"EXC10040","ExpectedPrice":12.0},"PrioritySearch":{"PriorityType":"Purchase","PropertyDescription":"A House","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit"}}                                                                            | {"Response":{"Status":"Rejection","Rejection":{"ExternalReference":"ExternalRef","RejectionResponse":{"Reason":"Official Search cannot be lodged against a Caution Title.","Code":"bg.title.caution","Errors":[]}}}}                                                                                                                   |                                                                                                                                                             |
| 3-ClosedTitle             | OfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testtitlenumber","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"CL123456","ExpectedPrice":12.0},"PrioritySearch":{"PriorityType":"Purchase","PropertyDescription":"A House","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit"}}                                            | {"Response":{"Status":"Rejection","Rejection":{"ExternalReference":"ExternalRef","RejectionResponse":{"Reason":"This title number is closed.","Code":"bg.title.closed","Errors":[]}}}}                                                                                                                                                 |                                                                                                                                                             |
| 4-NotPendDateFut          | OfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"ST500681","ExpectedPrice":12.0},"PrioritySearch":{"PriorityType":"Purchase","PropertyDescription":"A House","SearchFrom":"2026-07-16","PropreietorOrFirstApplicant":"Prynne","ApplicantNames":"Albert Fidgit"}}                                                                                      | {"Response":{"Status":"Rejection","Rejection":{"ExternalReference":"ExternalRef","RejectionResponse":{"Reason":"Search from date is invalid.","Code":"bg.date.futuredate","Errors":[]}}}}                                                                                                                                              |                                                                                                                                                             |
| 5-NotPendDateValid        | OfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"ST500681","ExpectedPrice":12.0},"PrioritySearch":{"PriorityType":"Purchase","PropertyDescription":"A House","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Prynne","ApplicantNames":"Albert Fidgit"}}                                                                                      | {"Response":{"Status":"Success","Results":{"ExternalReference":"ExternalRef"}}}                                                                                                                                                                                                                                                        | {"HMLRReference":"X45CCCC","ActualPrice":7.0,"Attachment":{"EmbeddedFileBinaryObject":{"format":"PDF"},"Date":"0001-01-01T00:00:00"},"ResultTypeCode":"10"} |
| 6-NameMisMatch            | OfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"ST500681","ExpectedPrice":12.0},"PrioritySearch":{"PriorityType":"Purchase","PropertyDescription":"A House","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Jenkins","ApplicantNames":"Albert Fidgit"}}                                                                                     | {"Response":{"Status":"Rejection","Rejection":{"ExternalReference":"ExternalRef","RejectionResponse":{"Reason":"There is no name match for this title number.","Code":"bg.state.nonamematch","Errors":[]}}}}                                                                                                                           |                                                                                                                                                             |
| 7-NameMisMatchContinue    | OfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"ST500681","ExpectedPrice":12.0},"PrioritySearch":{"PriorityType":"Purchase","PropertyDescription":"A House","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Jenkins","ApplicantNames":"Albert Fidgit", "ContinueIfNameMismatch": "true"}}                                                   | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"054a3833-f97c-4884-8fc7-f403e122e562","ExpectedResponseDateTime":"0001-01-01T00:00:00","MessageDescription":"We have accepted your application for an official search with priority. Priority begins now and expires on","HMLRReference":null}}}             |                                                                                                                                                             |
| 8-PendingSearches         | OfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testtitlenumber","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"SP123456","ExpectedPrice":12.0},"PrioritySearch":{"PriorityType":"Purchase","PropertyDescription":"A House","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit"}}                                            | {"Response":{"Status":"Rejection","Rejection":{"ExternalReference":"ExternalRef","RejectionResponse":{"Reason":"The title has applications of part pending against it. If you intend to take a registrable disposition of part you should apply for an official search of part.","Code":"bg.title.pendingsearchofpart","Errors":[]}}}} |                                                                                                                                                             |
| 9-PendingSearchesContinue | OfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testtitlenumber","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"SP123456","ExpectedPrice":12.0},"PrioritySearch":{"PriorityType":"Purchase","PropertyDescription":"A House","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit", "ContinueIfPendingSearchesOfPart": "true"}} | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"testtitlenumber","ExpectedResponseDateTime":"0001-01-01T00:00:00","MessageDescription":"We have accepted your application for an official search with priority. Priority begins now and expires on"}}}                                                       |                                                                                                                                                             |
| 10-DeveloperTitle         | OfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testtitlenumber","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"DV123456","ExpectedPrice":12.0},"PrioritySearch":{"PriorityType":"Purchase","PropertyDescription":"A House","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit"}}                                            | {"Response":{"Status":"Rejection","Rejection":{"ExternalReference":"ExternalRef","RejectionResponse":{"Reason":"This is a developing title. If you intend to take a registrable disposition of part you should apply for an official search with priority of part. ","Code":"bg.title.developertitle","Errors":[]}}}}                  |                                                                                                                                                             |
| 11-DeveloperTitleNotCont  | OfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testtitlenumber","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"DV123456","ExpectedPrice":12.0},"PrioritySearch":{"PriorityType":"Purchase","PropertyDescription":"A House","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit", "ContinueIfDeveloperTitle":"true"}}         | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"testtitlenumber","ExpectedResponseDateTime":"0001-01-01T00:00:00","MessageDescription":"We have accepted your application for an official search with priority. Priority begins now and expires on"}}}                                                       |                                                                                                                                                             |
| 12-FeeToLow               | OfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"ST500681","ExpectedPrice":2.0},"PrioritySearch":{"PriorityType":"Purchase","PropertyDescription":"A House","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Prynne","ApplicantNames":"Albert Fidgit"}}                                                                                       | {"Response":{"Status":"Rejection","Rejection":{"ExternalReference":"ExternalRef","RejectionResponse":{"Reason":"Fee Amount provided does not match with the fee calculated by Land Registry.","Code":"bg.fee.feeMismatch","Errors":[]}}}}                                                                                              |                                                                                                                                                             |
| 13-FeeToLowContinue       | OfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"ST500681","ExpectedPrice":2.0},"PrioritySearch":{"PriorityType":"Purchase","PropertyDescription":"A House","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Prynne","ApplicantNames":"Albert Fidgit", "ContinueIfFeeExceeds":"true"}}                                                        | {"Response":{"Status":"Success","Results":{"ExternalReference":"ExternalRef"}}}                                                                                                                                                                                                                                                        | {"HMLRReference":"X45CCCC","ActualPrice":7.0,"Attachment":{"EmbeddedFileBinaryObject":{"format":"PDF"},"Date":"0001-01-01T00:00:00"},"ResultTypeCode":"10"} |
| 14-Unavailable            | OfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"NOE1000","ExpectedPrice":12.0},"PrioritySearch":{"PriorityType":"Purchase","PropertyDescription":"A House","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit"}}                                                                             | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"921f921a-003a-4a77-8e48-d36b2f2585ef","ExpectedResponseDateTime":"0001-01-01T00:00:00","MessageDescription":"We have accepted your application for an official search with priority. Priority begins now and expires on"}}}                                  |                                                                                                                                                             |
| 15a-Success               | OfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"ST500681","ExpectedPrice":12.0},"PrioritySearch":{"PriorityType":"Purchase","PropertyDescription":"A House","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Prynne","ApplicantNames":"Albert Fidgit"}}                                                                                      | {"Response":{"Status":"Success","Results":{"ExternalReference":"ExternalRef"}}}                                                                                                                                                                                                                                                        | {"HMLRReference":"X45CCCC","ActualPrice":7.0,"Attachment":{"EmbeddedFileBinaryObject":{"format":"PDF"},"Date":"0001-01-01T00:00:00"},"ResultTypeCode":"10"} |
| 16a-SuccessOtherValid     | OfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"GN12345","ExpectedPrice":12.0},"PrioritySearch":{"PriorityType":"Purchase","PropertyDescription":"A House","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit"}}                                                                             | {"Response":{"Status":"Success","Results":{"ExternalReference":"ExternalRef"}}}                                                                                                                                                                                                                                                        | {"HMLRReference":"X45DDDD","ActualPrice":7.0,"Attachment":{"EmbeddedFileBinaryObject":{"format":"PDF"},"Date":"0001-01-01T00:00:00"},"ResultTypeCode":"10"} |
| 16b-OOH                   | OfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testoutofhours","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"GN12345","ExpectedPrice":12.0},"PrioritySearch":{"PriorityType":"Purchase","PropertyDescription":"A House","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit"}}                                              | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"testoutofhours","ExpectedResponseDateTime":"2024-05-02T17:11:14","MessageDescription":"Service is not currently available.System has queued your request,please poll at specified time."}}}                                                                  |                                                                                                                                                             |
| 17-Success                | OfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"GR518195","ExpectedPrice":12.0},"PrioritySearch":{"PriorityType":"Lease","PropertyDescription":"A House","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Benjamin","ApplicantNames":"Albert Fidgit"}}                                                                                       | {"Response":{"Status":"Success","Results":{"ExternalReference":"ExternalRef"}}}                                                                                                                                                                                                                                                        | {"HMLRReference":"X45CCCC","ActualPrice":7.0,"Attachment":{"EmbeddedFileBinaryObject":{"format":"PDF"},"Date":"0001-01-01T00:00:00"},"ResultTypeCode":"10"} |
| 18-Success                | OfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"HP725760","ExpectedPrice":12.0},"PrioritySearch":{"PriorityType":"Charge","PropertyDescription":"A House","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Bloggs","ApplicantNames":"Albert Fidgit"}}                                                                                        | {"Response":{"Status":"Success","Results":{"ExternalReference":"ExternalRef"}}}                                                                                                                                                                                                                                                        | {"HMLRReference":"X45CCCC","ActualPrice":7.0,"Attachment":{"EmbeddedFileBinaryObject":{"format":"PDF"},"Date":"0001-01-01T00:00:00"},"ResultTypeCode":"10"} |

@OfficialSearchWholePoll
Scenario: OfficialSearchWholePoll
	Given For a given property detail <Payload>
	And The Expected Message Details will be <MessageDetails>
	And A different <UserName> and <Password>
	When I call the land registy <Request>
	Then I should receive <Response>
Examples: 
| Test        | Request                 | UserName  | Password   | Payload                                         | Response                                                                                                                                                                                                                                                                                         | MessageDetails                                                                                                                                              |
| 15b-Success | PollOfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"pollST500681"}}    | {"Response": {"Status": "Success","Results": {"ExternalReference": "er1"}}}                                                                                                                                                                                                                      | {"HMLRReference":"X45CCCC","ActualPrice":7.0,"Attachment":{"EmbeddedFileBinaryObject":{"format":"PDF"},"Date":"0001-01-01T00:00:00"},"ResultTypeCode":"10"} |
| 16c-Success | PollOfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{}}                                | {"Response": {"Status": "Success","Results": {"ExternalReference": "er1"}}}                                                                                                                                                                                                                      | {"HMLRReference":"X45CCCC","ActualPrice":7.0,"Attachment":{"EmbeddedFileBinaryObject":{"format":"PDF"},"Date":"0001-01-01T00:00:00"},"ResultTypeCode":"10"} |
| 19-OOH      | PollOfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"polloutofhours"}}  | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"polloutofhours","ExpectedResponseDateTime":"2013-03-13T10:32:53","MessageDescription":"Service is not currently available.System has queued your request,please poll at specified time."}}}                            |                                                                                                                                                             |
| 20-Manual   | PollOfficialSearchWhole | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"pollunavailable"}} | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"polloutofhours4453","ExpectedResponseDateTime":"0001-01-01T00:00:00","MessageDescription":"We have accepted your application for an official search with priority. Priority begins now and expires on 12 Apr 2013."}}} |                                                                                                                                                             |





