// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace KnightFrank.Hub.LandRegistry.ServiceTests
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class OfficialSearchWholeFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "OfficialSearchWhole.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "", "OfficialSearchWhole", "A short summary of the feature", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "OfficialSearchWhole")))
            {
                global::KnightFrank.Hub.LandRegistry.ServiceTests.OfficialSearchWholeFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void OfficialSearchWhole(string test, string request, string userName, string password, string payload, string response, string messageDetails, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "OfficialSearchWhole"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Test", test);
            argumentsOfScenario.Add("Request", request);
            argumentsOfScenario.Add("UserName", userName);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Payload", payload);
            argumentsOfScenario.Add("Response", response);
            argumentsOfScenario.Add("MessageDetails", messageDetails);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("OfficialSearchWhole", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
 testRunner.Given(string.Format("For a given property detail {0}", payload), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
 testRunner.And(string.Format("The Expected Message Details will be {0}", messageDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 9
 testRunner.And(string.Format("A different {0} and {1}", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
 testRunner.When(string.Format("I call the land registy {0}", request), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 11
 testRunner.Then(string.Format("I should receive {0}", response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWhole: 1-InvalidTitle")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "1-InvalidTitle")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "1-InvalidTitle")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testtitlenumber"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""IV123456"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit""}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
            "\"RejectionResponse\":{\"Reason\":\"Title number is invalid.\",\"Code\":\"bg.title.invali" +
            "d\",\"Errors\":[]}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchWhole_1_InvalidTitle()
        {
#line 6
this.OfficialSearchWhole("1-InvalidTitle", "OfficialSearchWhole", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testtitlenumber"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""IV123456"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit""}}", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
                    "\"RejectionResponse\":{\"Reason\":\"Title number is invalid.\",\"Code\":\"bg.title.invali" +
                    "d\",\"Errors\":[]}}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWhole: 2-CautionTitle")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "2-CautionTitle")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "2-CautionTitle")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""EXC10040"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit""}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
            "\"RejectionResponse\":{\"Reason\":\"Official Search cannot be lodged against a Cautio" +
            "n Title.\",\"Code\":\"bg.title.caution\",\"Errors\":[]}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchWhole_2_CautionTitle()
        {
#line 6
this.OfficialSearchWhole("2-CautionTitle", "OfficialSearchWhole", "BGUser001", "landreg001", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""EXC10040"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit""}}", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
                    "\"RejectionResponse\":{\"Reason\":\"Official Search cannot be lodged against a Cautio" +
                    "n Title.\",\"Code\":\"bg.title.caution\",\"Errors\":[]}}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWhole: 3-ClosedTitle")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "3-ClosedTitle")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "3-ClosedTitle")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testtitlenumber"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""CL123456"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit""}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
            "\"RejectionResponse\":{\"Reason\":\"This title number is closed.\",\"Code\":\"bg.title.cl" +
            "osed\",\"Errors\":[]}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchWhole_3_ClosedTitle()
        {
#line 6
this.OfficialSearchWhole("3-ClosedTitle", "OfficialSearchWhole", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testtitlenumber"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""CL123456"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit""}}", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
                    "\"RejectionResponse\":{\"Reason\":\"This title number is closed.\",\"Code\":\"bg.title.cl" +
                    "osed\",\"Errors\":[]}}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWhole: 4-NotPendDateFut")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "4-NotPendDateFut")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "4-NotPendDateFut")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""ST500681"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""2026-07-16"",""PropreietorOrFirstApplicant"":""Prynne"",""ApplicantNames"":""Albert Fidgit""}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
            "\"RejectionResponse\":{\"Reason\":\"Search from date is invalid.\",\"Code\":\"bg.date.fut" +
            "uredate\",\"Errors\":[]}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchWhole_4_NotPendDateFut()
        {
#line 6
this.OfficialSearchWhole("4-NotPendDateFut", "OfficialSearchWhole", "BGUser001", "landreg001", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""ST500681"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""2026-07-16"",""PropreietorOrFirstApplicant"":""Prynne"",""ApplicantNames"":""Albert Fidgit""}}", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
                    "\"RejectionResponse\":{\"Reason\":\"Search from date is invalid.\",\"Code\":\"bg.date.fut" +
                    "uredate\",\"Errors\":[]}}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWhole: 5-NotPendDateValid")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "5-NotPendDateValid")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "5-NotPendDateValid")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""ST500681"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Prynne"",""ApplicantNames"":""Albert Fidgit""}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"HMLRReference\":\"X45CCCC\",\"ActualPrice\":7.0,\"Attachment\":{\"EmbeddedFileBinaryObj" +
            "ect\":{\"format\":\"PDF\"},\"Date\":\"0001-01-01T00:00:00\"},\"ResultTypeCode\":\"10\"}")]
        public void OfficialSearchWhole_5_NotPendDateValid()
        {
#line 6
this.OfficialSearchWhole("5-NotPendDateValid", "OfficialSearchWhole", "BGUser001", "landreg001", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""ST500681"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Prynne"",""ApplicantNames"":""Albert Fidgit""}}", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}", "{\"HMLRReference\":\"X45CCCC\",\"ActualPrice\":7.0,\"Attachment\":{\"EmbeddedFileBinaryObj" +
                    "ect\":{\"format\":\"PDF\"},\"Date\":\"0001-01-01T00:00:00\"},\"ResultTypeCode\":\"10\"}", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWhole: 6-NameMisMatch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "6-NameMisMatch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "6-NameMisMatch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""ST500681"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Jenkins"",""ApplicantNames"":""Albert Fidgit""}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
            "\"RejectionResponse\":{\"Reason\":\"There is no name match for this title number.\",\"C" +
            "ode\":\"bg.state.nonamematch\",\"Errors\":[]}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchWhole_6_NameMisMatch()
        {
#line 6
this.OfficialSearchWhole("6-NameMisMatch", "OfficialSearchWhole", "BGUser001", "landreg001", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""ST500681"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Jenkins"",""ApplicantNames"":""Albert Fidgit""}}", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
                    "\"RejectionResponse\":{\"Reason\":\"There is no name match for this title number.\",\"C" +
                    "ode\":\"bg.state.nonamematch\",\"Errors\":[]}}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWhole: 7-NameMisMatchContinue")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "7-NameMisMatchContinue")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "7-NameMisMatchContinue")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""ST500681"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Jenkins"",""ApplicantNames"":""Albert Fidgit"", ""ContinueIfNameMismatch"": ""true""}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""054a3833-f97c-4884-8fc7-f403e122e562"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""We have accepted your application for an official search with priority. Priority begins now and expires on"",""HMLRReference"":null}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchWhole_7_NameMisMatchContinue()
        {
#line 6
this.OfficialSearchWhole("7-NameMisMatchContinue", "OfficialSearchWhole", "BGUser001", "landreg001", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""ST500681"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Jenkins"",""ApplicantNames"":""Albert Fidgit"", ""ContinueIfNameMismatch"": ""true""}}", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""054a3833-f97c-4884-8fc7-f403e122e562"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""We have accepted your application for an official search with priority. Priority begins now and expires on"",""HMLRReference"":null}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWhole: 8-PendingSearches")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "8-PendingSearches")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "8-PendingSearches")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testtitlenumber"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""SP123456"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit""}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Rejection"",""Rejection"":{""ExternalReference"":""ExternalRef"",""RejectionResponse"":{""Reason"":""The title has applications of part pending against it. If you intend to take a registrable disposition of part you should apply for an official search of part."",""Code"":""bg.title.pendingsearchofpart"",""Errors"":[]}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchWhole_8_PendingSearches()
        {
#line 6
this.OfficialSearchWhole("8-PendingSearches", "OfficialSearchWhole", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testtitlenumber"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""SP123456"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit""}}", @"{""Response"":{""Status"":""Rejection"",""Rejection"":{""ExternalReference"":""ExternalRef"",""RejectionResponse"":{""Reason"":""The title has applications of part pending against it. If you intend to take a registrable disposition of part you should apply for an official search of part."",""Code"":""bg.title.pendingsearchofpart"",""Errors"":[]}}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWhole: 9-PendingSearchesContinue")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "9-PendingSearchesContinue")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "9-PendingSearchesContinue")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testtitlenumber"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""SP123456"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"", ""ContinueIfPendingSearchesOfPart"": ""true""}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testtitlenumber"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""We have accepted your application for an official search with priority. Priority begins now and expires on""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchWhole_9_PendingSearchesContinue()
        {
#line 6
this.OfficialSearchWhole("9-PendingSearchesContinue", "OfficialSearchWhole", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testtitlenumber"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""SP123456"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"", ""ContinueIfPendingSearchesOfPart"": ""true""}}", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testtitlenumber"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""We have accepted your application for an official search with priority. Priority begins now and expires on""}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWhole: 10-DeveloperTitle")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "10-DeveloperTitle")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "10-DeveloperTitle")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testtitlenumber"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DV123456"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit""}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Rejection"",""Rejection"":{""ExternalReference"":""ExternalRef"",""RejectionResponse"":{""Reason"":""This is a developing title. If you intend to take a registrable disposition of part you should apply for an official search with priority of part. "",""Code"":""bg.title.developertitle"",""Errors"":[]}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchWhole_10_DeveloperTitle()
        {
#line 6
this.OfficialSearchWhole("10-DeveloperTitle", "OfficialSearchWhole", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testtitlenumber"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DV123456"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit""}}", @"{""Response"":{""Status"":""Rejection"",""Rejection"":{""ExternalReference"":""ExternalRef"",""RejectionResponse"":{""Reason"":""This is a developing title. If you intend to take a registrable disposition of part you should apply for an official search with priority of part. "",""Code"":""bg.title.developertitle"",""Errors"":[]}}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWhole: 11-DeveloperTitleNotCont")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "11-DeveloperTitleNotCont")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "11-DeveloperTitleNotCont")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testtitlenumber"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DV123456"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"", ""ContinueIfDeveloperTitle"":""true""}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testtitlenumber"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""We have accepted your application for an official search with priority. Priority begins now and expires on""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchWhole_11_DeveloperTitleNotCont()
        {
#line 6
this.OfficialSearchWhole("11-DeveloperTitleNotCont", "OfficialSearchWhole", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testtitlenumber"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DV123456"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"", ""ContinueIfDeveloperTitle"":""true""}}", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testtitlenumber"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""We have accepted your application for an official search with priority. Priority begins now and expires on""}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWhole: 12-FeeToLow")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "12-FeeToLow")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "12-FeeToLow")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""ST500681"",""ExpectedPrice"":2.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Prynne"",""ApplicantNames"":""Albert Fidgit""}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
            "\"RejectionResponse\":{\"Reason\":\"Fee Amount provided does not match with the fee c" +
            "alculated by Land Registry.\",\"Code\":\"bg.fee.feeMismatch\",\"Errors\":[]}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchWhole_12_FeeToLow()
        {
#line 6
this.OfficialSearchWhole("12-FeeToLow", "OfficialSearchWhole", "BGUser001", "landreg001", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""ST500681"",""ExpectedPrice"":2.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Prynne"",""ApplicantNames"":""Albert Fidgit""}}", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
                    "\"RejectionResponse\":{\"Reason\":\"Fee Amount provided does not match with the fee c" +
                    "alculated by Land Registry.\",\"Code\":\"bg.fee.feeMismatch\",\"Errors\":[]}}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWhole: 13-FeeToLowContinue")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "13-FeeToLowContinue")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "13-FeeToLowContinue")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""ST500681"",""ExpectedPrice"":2.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Prynne"",""ApplicantNames"":""Albert Fidgit"", ""ContinueIfFeeExceeds"":""true""}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"HMLRReference\":\"X45CCCC\",\"ActualPrice\":7.0,\"Attachment\":{\"EmbeddedFileBinaryObj" +
            "ect\":{\"format\":\"PDF\"},\"Date\":\"0001-01-01T00:00:00\"},\"ResultTypeCode\":\"10\"}")]
        public void OfficialSearchWhole_13_FeeToLowContinue()
        {
#line 6
this.OfficialSearchWhole("13-FeeToLowContinue", "OfficialSearchWhole", "BGUser001", "landreg001", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""ST500681"",""ExpectedPrice"":2.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Prynne"",""ApplicantNames"":""Albert Fidgit"", ""ContinueIfFeeExceeds"":""true""}}", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}", "{\"HMLRReference\":\"X45CCCC\",\"ActualPrice\":7.0,\"Attachment\":{\"EmbeddedFileBinaryObj" +
                    "ect\":{\"format\":\"PDF\"},\"Date\":\"0001-01-01T00:00:00\"},\"ResultTypeCode\":\"10\"}", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWhole: 14-Unavailable")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "14-Unavailable")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "14-Unavailable")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""NOE1000"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit""}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""921f921a-003a-4a77-8e48-d36b2f2585ef"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""We have accepted your application for an official search with priority. Priority begins now and expires on""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchWhole_14_Unavailable()
        {
#line 6
this.OfficialSearchWhole("14-Unavailable", "OfficialSearchWhole", "BGUser001", "landreg001", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""NOE1000"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit""}}", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""921f921a-003a-4a77-8e48-d36b2f2585ef"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""We have accepted your application for an official search with priority. Priority begins now and expires on""}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWhole: 15a-Success")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "15a-Success")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "15a-Success")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""ST500681"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Prynne"",""ApplicantNames"":""Albert Fidgit""}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"HMLRReference\":\"X45CCCC\",\"ActualPrice\":7.0,\"Attachment\":{\"EmbeddedFileBinaryObj" +
            "ect\":{\"format\":\"PDF\"},\"Date\":\"0001-01-01T00:00:00\"},\"ResultTypeCode\":\"10\"}")]
        public void OfficialSearchWhole_15A_Success()
        {
#line 6
this.OfficialSearchWhole("15a-Success", "OfficialSearchWhole", "BGUser001", "landreg001", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""ST500681"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Prynne"",""ApplicantNames"":""Albert Fidgit""}}", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}", "{\"HMLRReference\":\"X45CCCC\",\"ActualPrice\":7.0,\"Attachment\":{\"EmbeddedFileBinaryObj" +
                    "ect\":{\"format\":\"PDF\"},\"Date\":\"0001-01-01T00:00:00\"},\"ResultTypeCode\":\"10\"}", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWhole: 16a-SuccessOtherValid")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "16a-SuccessOtherValid")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "16a-SuccessOtherValid")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""GN12345"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit""}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"HMLRReference\":\"X45DDDD\",\"ActualPrice\":7.0,\"Attachment\":{\"EmbeddedFileBinaryObj" +
            "ect\":{\"format\":\"PDF\"},\"Date\":\"0001-01-01T00:00:00\"},\"ResultTypeCode\":\"10\"}")]
        public void OfficialSearchWhole_16A_SuccessOtherValid()
        {
#line 6
this.OfficialSearchWhole("16a-SuccessOtherValid", "OfficialSearchWhole", "BGUser001", "landreg001", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""GN12345"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit""}}", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}", "{\"HMLRReference\":\"X45DDDD\",\"ActualPrice\":7.0,\"Attachment\":{\"EmbeddedFileBinaryObj" +
                    "ect\":{\"format\":\"PDF\"},\"Date\":\"0001-01-01T00:00:00\"},\"ResultTypeCode\":\"10\"}", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWhole: 16b-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "16b-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "16b-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testoutofhours"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""GN12345"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit""}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testoutofhours"",""ExpectedResponseDateTime"":""2024-05-02T17:11:14"",""MessageDescription"":""Service is not currently available.System has queued your request,please poll at specified time.""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchWhole_16B_OOH()
        {
#line 6
this.OfficialSearchWhole("16b-OOH", "OfficialSearchWhole", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testoutofhours"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""GN12345"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit""}}", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testoutofhours"",""ExpectedResponseDateTime"":""2024-05-02T17:11:14"",""MessageDescription"":""Service is not currently available.System has queued your request,please poll at specified time.""}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWhole: 17-Success")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "17-Success")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "17-Success")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""GR518195"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Lease"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Benjamin"",""ApplicantNames"":""Albert Fidgit""}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"HMLRReference\":\"X45CCCC\",\"ActualPrice\":7.0,\"Attachment\":{\"EmbeddedFileBinaryObj" +
            "ect\":{\"format\":\"PDF\"},\"Date\":\"0001-01-01T00:00:00\"},\"ResultTypeCode\":\"10\"}")]
        public void OfficialSearchWhole_17_Success()
        {
#line 6
this.OfficialSearchWhole("17-Success", "OfficialSearchWhole", "BGUser001", "landreg001", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""GR518195"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Lease"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Benjamin"",""ApplicantNames"":""Albert Fidgit""}}", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}", "{\"HMLRReference\":\"X45CCCC\",\"ActualPrice\":7.0,\"Attachment\":{\"EmbeddedFileBinaryObj" +
                    "ect\":{\"format\":\"PDF\"},\"Date\":\"0001-01-01T00:00:00\"},\"ResultTypeCode\":\"10\"}", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWhole: 18-Success")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "18-Success")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "18-Success")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""HP725760"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Charge"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Bloggs"",""ApplicantNames"":""Albert Fidgit""}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"HMLRReference\":\"X45CCCC\",\"ActualPrice\":7.0,\"Attachment\":{\"EmbeddedFileBinaryObj" +
            "ect\":{\"format\":\"PDF\"},\"Date\":\"0001-01-01T00:00:00\"},\"ResultTypeCode\":\"10\"}")]
        public void OfficialSearchWhole_18_Success()
        {
#line 6
this.OfficialSearchWhole("18-Success", "OfficialSearchWhole", "BGUser001", "landreg001", @"{""Reference"":{""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""HP725760"",""ExpectedPrice"":12.0},""PrioritySearch"":{""PriorityType"":""Charge"",""PropertyDescription"":""A House"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Bloggs"",""ApplicantNames"":""Albert Fidgit""}}", "{\"Response\":{\"Status\":\"Success\",\"Results\":{\"ExternalReference\":\"ExternalRef\"}}}", "{\"HMLRReference\":\"X45CCCC\",\"ActualPrice\":7.0,\"Attachment\":{\"EmbeddedFileBinaryObj" +
                    "ect\":{\"format\":\"PDF\"},\"Date\":\"0001-01-01T00:00:00\"},\"ResultTypeCode\":\"10\"}", ((string[])(null)));
#line hidden
        }
        
        public virtual void OfficialSearchWholePoll(string test, string request, string userName, string password, string payload, string response, string messageDetails, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "OfficialSearchWholePoll"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Test", test);
            argumentsOfScenario.Add("Request", request);
            argumentsOfScenario.Add("UserName", userName);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Payload", payload);
            argumentsOfScenario.Add("Response", response);
            argumentsOfScenario.Add("MessageDetails", messageDetails);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("OfficialSearchWholePoll", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 36
 testRunner.Given(string.Format("For a given property detail {0}", payload), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 37
 testRunner.And(string.Format("The Expected Message Details will be {0}", messageDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 38
 testRunner.And(string.Format("A different {0} and {1}", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 39
 testRunner.When(string.Format("I call the land registy {0}", request), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 40
 testRunner.Then(string.Format("I should receive {0}", response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWholePoll: 15b-Success")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWholePoll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "15b-Success")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "15b-Success")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "PollOfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"pollST500681\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"er1\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"HMLRReference\":\"X45CCCC\",\"ActualPrice\":7.0,\"Attachment\":{\"EmbeddedFileBinaryObj" +
            "ect\":{\"format\":\"PDF\"},\"Date\":\"0001-01-01T00:00:00\"},\"ResultTypeCode\":\"10\"}")]
        public void OfficialSearchWholePoll_15B_Success()
        {
#line 35
this.OfficialSearchWholePoll("15b-Success", "PollOfficialSearchWhole", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"pollST500681\"}}", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"er1\"}}}", "{\"HMLRReference\":\"X45CCCC\",\"ActualPrice\":7.0,\"Attachment\":{\"EmbeddedFileBinaryObj" +
                    "ect\":{\"format\":\"PDF\"},\"Date\":\"0001-01-01T00:00:00\"},\"ResultTypeCode\":\"10\"}", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWholePoll: 16c-Success")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWholePoll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "16c-Success")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "16c-Success")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "PollOfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"er1\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"HMLRReference\":\"X45CCCC\",\"ActualPrice\":7.0,\"Attachment\":{\"EmbeddedFileBinaryObj" +
            "ect\":{\"format\":\"PDF\"},\"Date\":\"0001-01-01T00:00:00\"},\"ResultTypeCode\":\"10\"}")]
        public void OfficialSearchWholePoll_16C_Success()
        {
#line 35
this.OfficialSearchWholePoll("16c-Success", "PollOfficialSearchWhole", "BGUser001", "landreg001", "{\"Reference\":{}}", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"er1\"}}}", "{\"HMLRReference\":\"X45CCCC\",\"ActualPrice\":7.0,\"Attachment\":{\"EmbeddedFileBinaryObj" +
                    "ect\":{\"format\":\"PDF\"},\"Date\":\"0001-01-01T00:00:00\"},\"ResultTypeCode\":\"10\"}", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWholePoll: 19-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWholePoll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "19-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "19-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "PollOfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"polloutofhours\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""polloutofhours"",""ExpectedResponseDateTime"":""2013-03-13T10:32:53"",""MessageDescription"":""Service is not currently available.System has queued your request,please poll at specified time.""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchWholePoll_19_OOH()
        {
#line 35
this.OfficialSearchWholePoll("19-OOH", "PollOfficialSearchWhole", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"polloutofhours\"}}", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""polloutofhours"",""ExpectedResponseDateTime"":""2013-03-13T10:32:53"",""MessageDescription"":""Service is not currently available.System has queued your request,please poll at specified time.""}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchWholePoll: 20-Manual")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchWholePoll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "20-Manual")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "20-Manual")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "PollOfficialSearchWhole")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"pollunavailable\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""polloutofhours4453"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""We have accepted your application for an official search with priority. Priority begins now and expires on 12 Apr 2013.""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchWholePoll_20_Manual()
        {
#line 35
this.OfficialSearchWholePoll("20-Manual", "PollOfficialSearchWhole", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"pollunavailable\"}}", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""polloutofhours4453"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""We have accepted your application for an official search with priority. Priority begins now and expires on 12 Apr 2013.""}}}", "", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
