// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace KnightFrank.Hub.LandRegistry.ServiceTests
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class OfficialSearchPartFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "OfficialSearchPart.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "", "OfficialSearchPart", "A short summary of the feature", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "OfficialSearchPart")))
            {
                global::KnightFrank.Hub.LandRegistry.ServiceTests.OfficialSearchPartFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void OfficialSearchPart(string test, string request, string userName, string password, string payload, string response, string messageDetails, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "OfficialSearchPart"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Test", test);
            argumentsOfScenario.Add("Request", request);
            argumentsOfScenario.Add("UserName", userName);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Payload", payload);
            argumentsOfScenario.Add("Response", response);
            argumentsOfScenario.Add("MessageDetails", messageDetails);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("OfficialSearchPart", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
 testRunner.Given(string.Format("For a given property detail {0}", payload), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
 testRunner.And(string.Format("The Expected Message Details will be {0}", messageDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 9
 testRunner.And(string.Format("A different {0} and {1}", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
 testRunner.When(string.Format("I call the land registy {0}", request), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 11
 testRunner.Then(string.Format("I should receive {0}", response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchPart: 1-PostalReturn")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "1-PostalReturn")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "1-PostalReturn")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testnoplan"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":4.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""true"",""PropertyIdentification"":{""PropertyDescription"":""A House""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testnoplan"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services.""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchPart_1_PostalReturn()
        {
#line 6
this.OfficialSearchPart("1-PostalReturn", "OfficialSearchPart", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testnoplan"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":4.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""true"",""PropertyIdentification"":{""PropertyDescription"":""A House""}}}", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testnoplan"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services.""}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchPart: 2-NoAuthority")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "2-NoAuthority")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "2-NoAuthority")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testnoauthority"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":4.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""true"",""PropertyIdentification"":{""PropertyDescription"":""A House""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"SystemError\":{\"Description\":\"You do not have the necessary rights to access thi" +
            "s service.\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchPart_2_NoAuthority()
        {
#line 6
this.OfficialSearchPart("2-NoAuthority", "OfficialSearchPart", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testnoauthority"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":4.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""true"",""PropertyIdentification"":{""PropertyDescription"":""A House""}}}", "{\"SystemError\":{\"Description\":\"You do not have the necessary rights to access thi" +
                    "s service.\"}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchPart: 3-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "3-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "3-OOH")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testoutofhours"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":4.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""true"",""PropertyIdentification"":{""PropertyDescription"":""A House""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testoutofhours"",""ExpectedResponseDateTime"":""2024-05-02T17:11:14"",""MessageDescription"":""Service is not currently available.System has queued your request,please poll at specified time.""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchPart_3_OOH()
        {
#line 6
this.OfficialSearchPart("3-OOH", "OfficialSearchPart", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testoutofhours"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":4.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""true"",""PropertyIdentification"":{""PropertyDescription"":""A House""}}}", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testoutofhours"",""ExpectedResponseDateTime"":""2024-05-02T17:11:14"",""MessageDescription"":""Service is not currently available.System has queued your request,please poll at specified time.""}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchPart: 4-NoName")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "4-NoName")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "4-NoName")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testnonamematchnoplan"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":4.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""false"",""PropertyIdentification"":{""PropertyDescription"":""A House""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
            "\"RejectionResponse\":{\"Reason\":\"There is no name match for this title number.\",\"C" +
            "ode\":\"bg.state.nonamematch\",\"Errors\":[]}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchPart_4_NoName()
        {
#line 6
this.OfficialSearchPart("4-NoName", "OfficialSearchPart", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testnonamematchnoplan"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":4.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""false"",""PropertyIdentification"":{""PropertyDescription"":""A House""}}}", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
                    "\"RejectionResponse\":{\"Reason\":\"There is no name match for this title number.\",\"C" +
                    "ode\":\"bg.state.nonamematch\",\"Errors\":[]}}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchPart: 5-TitlePlan")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "5-TitlePlan")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "5-TitlePlan")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testnonamematchwithplan"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":4.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""true"",""PropertyIdentification"":{""TitlePlan"":{""TitlePlanNumber"":""ABC12345Z"",""Reference"":""Reference""}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testnonamematchwithplan"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services.""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchPart_5_TitlePlan()
        {
#line 6
this.OfficialSearchPart("5-TitlePlan", "OfficialSearchPart", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testnonamematchwithplan"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":4.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""true"",""PropertyIdentification"":{""TitlePlan"":{""TitlePlanNumber"":""ABC12345Z"",""Reference"":""Reference""}}}}", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testnonamematchwithplan"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services.""}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchPart: 6-NameMismatch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "6-NameMismatch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "6-NameMismatch")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testnonamematchnocontinue"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":4.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""false"",""PropertyIdentification"":{""PropertyDescription"":""A House""},""TimeshareDetails"":{""TimeshareLease"":false,""TimePeriod"":""TimePeriod""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
            "\"RejectionResponse\":{\"Reason\":\"There is no name match for this title number.\",\"C" +
            "ode\":\"bg.state.nonamematch\",\"Errors\":[]}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchPart_6_NameMismatch()
        {
#line 6
this.OfficialSearchPart("6-NameMismatch", "OfficialSearchPart", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testnonamematchnocontinue"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":4.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""false"",""PropertyIdentification"":{""PropertyDescription"":""A House""},""TimeshareDetails"":{""TimeshareLease"":false,""TimePeriod"":""TimePeriod""}}}", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
                    "\"RejectionResponse\":{\"Reason\":\"There is no name match for this title number.\",\"C" +
                    "ode\":\"bg.state.nonamematch\",\"Errors\":[]}}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchPart: 7-EstatePlan")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "7-EstatePlan")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "7-EstatePlan")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testwithplotdetails"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":4.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""false"",""PropertyIdentification"":{""EstatePlan"":{""ApprovalDate"":""2021-02-26"",""PlotDetails"":""Plot Thickens""}},""TimeshareDetails"":{""TimeshareLease"":false,""TimePeriod"":""TimePeriod""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testwithplotdetails"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services.""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchPart_7_EstatePlan()
        {
#line 6
this.OfficialSearchPart("7-EstatePlan", "OfficialSearchPart", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testwithplotdetails"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":4.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""false"",""PropertyIdentification"":{""EstatePlan"":{""ApprovalDate"":""2021-02-26"",""PlotDetails"":""Plot Thickens""}},""TimeshareDetails"":{""TimeshareLease"":false,""TimePeriod"":""TimePeriod""}}}", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testwithplotdetails"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services.""}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchPart: 8-PropDesc")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "8-PropDesc")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "8-PropDesc")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testwithpropertydescription"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":4.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""false"",""PropertyIdentification"":{""PropertyDescription"":""A House""},""TimeshareDetails"":{""TimeshareLease"":false,""TimePeriod"":""TimePeriod""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testwithpropertydescription"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services.""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchPart_8_PropDesc()
        {
#line 6
this.OfficialSearchPart("8-PropDesc", "OfficialSearchPart", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testwithpropertydescription"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":4.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""false"",""PropertyIdentification"":{""PropertyDescription"":""A House""},""TimeshareDetails"":{""TimeshareLease"":false,""TimePeriod"":""TimePeriod""}}}", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testwithpropertydescription"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services.""}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchPart: 9-Attachment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "9-Attachment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "9-Attachment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testwithpropertydescription"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":4.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""true"",""PropertyIdentification"":{""PropertyDescription"":""A House""},""TimeshareDetails"":{""TimeshareLease"":false,""TimePeriod"":""TimePeriod""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testwithpropertydescription"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services.""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchPart_9_Attachment()
        {
#line 6
this.OfficialSearchPart("9-Attachment", "OfficialSearchPart", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testwithpropertydescription"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":4.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""true"",""PropertyIdentification"":{""PropertyDescription"":""A House""},""TimeshareDetails"":{""TimeshareLease"":false,""TimePeriod"":""TimePeriod""}}}", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testwithpropertydescription"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services.""}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchPart: 10a1-Fees-True")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "10a1-Fees-True")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "10a1-Fees-True")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testfeeindicator"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":5.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""true"",""PropertyIdentification"":{""PropertyDescription"":""A House""},""TimeshareDetails"":{""TimeshareLease"":false,""TimePeriod"":""TimePeriod""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testfeeindicator"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services.""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchPart_10A1_Fees_True()
        {
#line 6
this.OfficialSearchPart("10a1-Fees-True", "OfficialSearchPart", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testfeeindicator"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":5.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""true"",""PropertyIdentification"":{""PropertyDescription"":""A House""},""TimeshareDetails"":{""TimeshareLease"":false,""TimePeriod"":""TimePeriod""}}}", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testfeeindicator"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services.""}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchPart: 10a2-Fees-False")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "10a2-Fees-False")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "10a2-Fees-False")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testfeeindicator"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":5.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""false"",""ContinueIfNameMismatch"":""true"",""PropertyIdentification"":{""PropertyDescription"":""A House""},""TimeshareDetails"":{""TimeshareLease"":false,""TimePeriod"":""TimePeriod""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
            "\"RejectionResponse\":{\"Reason\":\"There is no name match for this title number.\",\"C" +
            "ode\":\"bg.fee.feeMismatch\",\"Errors\":[]}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchPart_10A2_Fees_False()
        {
#line 6
this.OfficialSearchPart("10a2-Fees-False", "OfficialSearchPart", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testfeeindicator"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":5.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""false"",""ContinueIfNameMismatch"":""true"",""PropertyIdentification"":{""PropertyDescription"":""A House""},""TimeshareDetails"":{""TimeshareLease"":false,""TimePeriod"":""TimePeriod""}}}", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
                    "\"RejectionResponse\":{\"Reason\":\"There is no name match for this title number.\",\"C" +
                    "ode\":\"bg.fee.feeMismatch\",\"Errors\":[]}}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchPart: 10b-Fees-LessThan4-True")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "10b-Fees-LessThan4-True")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "10b-Fees-LessThan4-True")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testfeeindicator"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":3.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""true"",""PropertyIdentification"":{""PropertyDescription"":""A House""},""TimeshareDetails"":{""TimeshareLease"":false,""TimePeriod"":""TimePeriod""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testfeeindicator"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services.""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchPart_10B_Fees_LessThan4_True()
        {
#line 6
this.OfficialSearchPart("10b-Fees-LessThan4-True", "OfficialSearchPart", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testfeeindicator"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":3.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""true"",""ContinueIfNameMismatch"":""true"",""PropertyIdentification"":{""PropertyDescription"":""A House""},""TimeshareDetails"":{""TimeshareLease"":false,""TimePeriod"":""TimePeriod""}}}", @"{""Response"":{""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testfeeindicator"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services.""}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchPart: 10c-Fees-LessThan4-False")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "10c-Fees-LessThan4-False")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "10c-Fees-LessThan4-False")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", @"{""Reference"":{""UniqueMsgId"":""testfeeindicator"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":3.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""false"",""ContinueIfNameMismatch"":""true"",""PropertyIdentification"":{""PropertyDescription"":""A House""},""TimeshareDetails"":{""TimeshareLease"":false,""TimePeriod"":""TimePeriod""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
            "\"RejectionResponse\":{\"Reason\":\"There is no name match for this title number.\",\"C" +
            "ode\":\"bg.fee.feeMismatch\",\"Errors\":[]}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchPart_10C_Fees_LessThan4_False()
        {
#line 6
this.OfficialSearchPart("10c-Fees-LessThan4-False", "OfficialSearchPart", "BGUser001", "landreg001", @"{""Reference"":{""UniqueMsgId"":""testfeeindicator"",""ExternalRef"":""ExternalRef"",""CustomerRef"":""CustomerReference""},""Property"":{""TitleNumber"":""DN100"",""ExpectedPrice"":3.0},""PrioritySearch"":{""PriorityType"":""Purchase"",""SearchFrom"":""1969-07-16"",""PropreietorOrFirstApplicant"":""Mr PropertyOwner"",""ApplicantNames"":""Albert Fidgit"",""ContinueIfFeeExceeds"":""false"",""ContinueIfNameMismatch"":""true"",""PropertyIdentification"":{""PropertyDescription"":""A House""},""TimeshareDetails"":{""TimeshareLease"":false,""TimePeriod"":""TimePeriod""}}}", "{\"Response\":{\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"ExternalRef\"," +
                    "\"RejectionResponse\":{\"Reason\":\"There is no name match for this title number.\",\"C" +
                    "ode\":\"bg.fee.feeMismatch\",\"Errors\":[]}}}}", "", ((string[])(null)));
#line hidden
        }
        
        public virtual void OfficialSearchPartPoll(string test, string request, string userName, string password, string payload, string response, string messageDetails, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "OfficialSearchPartPoll"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Test", test);
            argumentsOfScenario.Add("Request", request);
            argumentsOfScenario.Add("UserName", userName);
            argumentsOfScenario.Add("Password", password);
            argumentsOfScenario.Add("Payload", payload);
            argumentsOfScenario.Add("Response", response);
            argumentsOfScenario.Add("MessageDetails", messageDetails);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("OfficialSearchPartPoll", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 32
 testRunner.Given(string.Format("For a given property detail {0}", payload), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 33
 testRunner.And(string.Format("The Expected Message Details will be {0}", messageDetails), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 34
 testRunner.And(string.Format("A different {0} and {1}", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 35
 testRunner.When(string.Format("I call the land registy {0}", request), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 36
 testRunner.Then(string.Format("I should receive {0}", response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchPartPoll: 11-NYP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchPartPoll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "11-NYP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "11-NYP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "PollOfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"testpollstilloutofhours\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\": {\"Status\": \"Acknowledgement\",\"Acknowledgement\": {\"UniqueMsgId\": \"pol" +
            "loutofhours\",\"MessageDescription\": \"Request has not yet been processed.\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchPartPoll_11_NYP()
        {
#line 31
this.OfficialSearchPartPoll("11-NYP", "PollOfficialSearchPart", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"testpollstilloutofhours\"}}", "{\"Response\": {\"Status\": \"Acknowledgement\",\"Acknowledgement\": {\"UniqueMsgId\": \"pol" +
                    "loutofhours\",\"MessageDescription\": \"Request has not yet been processed.\"}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchPartPoll: 12-LodgedRes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchPartPoll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "12-LodgedRes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "12-LodgedRes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "PollOfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"testpolllodged\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", @"{""Response"": {""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testfeeindicator"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services.""}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchPartPoll_12_LodgedRes()
        {
#line 31
this.OfficialSearchPartPoll("12-LodgedRes", "PollOfficialSearchPart", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"testpolllodged\"}}", @"{""Response"": {""Status"":""Acknowledgement"",""Acknowledgement"":{""UniqueMsgId"":""testfeeindicator"",""ExpectedResponseDateTime"":""0001-01-01T00:00:00"",""MessageDescription"":""Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services.""}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchPartPoll: 13-Error")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchPartPoll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "13-Error")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "13-Error")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "PollOfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"testpollerror\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\": {\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"Ext_ref\",\"Re" +
            "jectionResponse\":{\"Reason\":\"There is no name match for this title number.\",\"Code" +
            "\":\"bg.state.nonamematch\",\"Errors\":[]}}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "")]
        public void OfficialSearchPartPoll_13_Error()
        {
#line 31
this.OfficialSearchPartPoll("13-Error", "PollOfficialSearchPart", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"testpollerror\"}}", "{\"Response\": {\"Status\":\"Rejection\",\"Rejection\":{\"ExternalReference\":\"Ext_ref\",\"Re" +
                    "jectionResponse\":{\"Reason\":\"There is no name match for this title number.\",\"Code" +
                    "\":\"bg.state.nonamematch\",\"Errors\":[]}}}}", "", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("OfficialSearchPartPoll: 14-ElecRes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "OfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OfficialSearchPartPoll")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "14-ElecRes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Test", "14-ElecRes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Request", "PollOfficialSearchPart")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:UserName", "BGUser001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Password", "landreg001")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Payload", "{\"Reference\":{\"UniqueMsgId\":\"testpollelectronicresult\"}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Response", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"zzz\"}}}")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:MessageDetails", "{\"HMLRReference\":\"Y0WCJVR\",\"ActualPrice\":7.00,\"Attachment\":{\"EmbeddedFileBinaryOb" +
            "ject\":{\"format\":\"pdf\"},\"Date\":\"0001-01-01T00:00:00\"},\"ResultTypeCode\":\"10\"}")]
        public void OfficialSearchPartPoll_14_ElecRes()
        {
#line 31
this.OfficialSearchPartPoll("14-ElecRes", "PollOfficialSearchPart", "BGUser001", "landreg001", "{\"Reference\":{\"UniqueMsgId\":\"testpollelectronicresult\"}}", "{\"Response\": {\"Status\": \"Success\",\"Results\": {\"ExternalReference\": \"zzz\"}}}", "{\"HMLRReference\":\"Y0WCJVR\",\"ActualPrice\":7.00,\"Attachment\":{\"EmbeddedFileBinaryOb" +
                    "ject\":{\"format\":\"pdf\"},\"Date\":\"0001-01-01T00:00:00\"},\"ResultTypeCode\":\"10\"}", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
