Feature: OfficialSearchPart

A short summary of the feature

@OfficialSearchPart
Scenario: OfficialSearchPart
	Given For a given property detail <Payload>
	And The Expected Message Details will be <MessageDetails>
	And A different <UserName> and <Password>
	When I call the land registy <Request>
	Then I should receive <Response>
Examples: 
| Test                    | Request            | UserName  | Password   | Payload                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | Response                                                                                                                                                                                                                                                                                                                                                                                     | MessageDetails |
| 1-PostalReturn          | OfficialSearchPart | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testnoplan","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"DN100","ExpectedPrice":4.0},"PrioritySearch":{"PriorityType":"Purchase","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit","ContinueIfFeeExceeds":"true","ContinueIfNameMismatch":"true","PropertyIdentification":{"PropertyDescription":"A House"}}}                                                                                                                          | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"testnoplan","ExpectedResponseDateTime":"0001-01-01T00:00:00","MessageDescription":"Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services."}}}                  |                |
| 2-NoAuthority           | OfficialSearchPart | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testnoauthority","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"DN100","ExpectedPrice":4.0},"PrioritySearch":{"PriorityType":"Purchase","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit","ContinueIfFeeExceeds":"true","ContinueIfNameMismatch":"true","PropertyIdentification":{"PropertyDescription":"A House"}}}                                                                                                                     | {"SystemError":{"Description":"You do not have the necessary rights to access this service."}}                                                                                                                                                                                                                                                                                               |                |
| 3-OOH                   | OfficialSearchPart | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testoutofhours","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"DN100","ExpectedPrice":4.0},"PrioritySearch":{"PriorityType":"Purchase","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit","ContinueIfFeeExceeds":"true","ContinueIfNameMismatch":"true","PropertyIdentification":{"PropertyDescription":"A House"}}}                                                                                                                      | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"testoutofhours","ExpectedResponseDateTime":"2024-05-02T17:11:14","MessageDescription":"Service is not currently available.System has queued your request,please poll at specified time."}}}                                                                                                                        |                |
| 4-NoName                | OfficialSearchPart | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testnonamematchnoplan","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"DN100","ExpectedPrice":4.0},"PrioritySearch":{"PriorityType":"Purchase","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit","ContinueIfFeeExceeds":"true","ContinueIfNameMismatch":"false","PropertyIdentification":{"PropertyDescription":"A House"}}}                                                                                                              | {"Response":{"Status":"Rejection","Rejection":{"ExternalReference":"ExternalRef","RejectionResponse":{"Reason":"There is no name match for this title number.","Code":"bg.state.nonamematch","Errors":[]}}}}                                                                                                                                                                                 |                |
| 5-TitlePlan             | OfficialSearchPart | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testnonamematchwithplan","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"DN100","ExpectedPrice":4.0},"PrioritySearch":{"PriorityType":"Purchase","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit","ContinueIfFeeExceeds":"true","ContinueIfNameMismatch":"true","PropertyIdentification":{"TitlePlan":{"TitlePlanNumber":"ABC12345Z","Reference":"Reference"}}}}                                                                         | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"testnonamematchwithplan","ExpectedResponseDateTime":"0001-01-01T00:00:00","MessageDescription":"Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services."}}}     |                |
| 6-NameMismatch          | OfficialSearchPart | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testnonamematchnocontinue","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"DN100","ExpectedPrice":4.0},"PrioritySearch":{"PriorityType":"Purchase","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit","ContinueIfFeeExceeds":"true","ContinueIfNameMismatch":"false","PropertyIdentification":{"PropertyDescription":"A House"},"TimeshareDetails":{"TimeshareLease":false,"TimePeriod":"TimePeriod"}}}                                    | {"Response":{"Status":"Rejection","Rejection":{"ExternalReference":"ExternalRef","RejectionResponse":{"Reason":"There is no name match for this title number.","Code":"bg.state.nonamematch","Errors":[]}}}}                                                                                                                                                                                 |                |
| 7-EstatePlan            | OfficialSearchPart | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testwithplotdetails","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"DN100","ExpectedPrice":4.0},"PrioritySearch":{"PriorityType":"Purchase","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit","ContinueIfFeeExceeds":"true","ContinueIfNameMismatch":"false","PropertyIdentification":{"EstatePlan":{"ApprovalDate":"2021-02-26","PlotDetails":"Plot Thickens"}},"TimeshareDetails":{"TimeshareLease":false,"TimePeriod":"TimePeriod"}}} | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"testwithplotdetails","ExpectedResponseDateTime":"0001-01-01T00:00:00","MessageDescription":"Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services."}}}         |                |
| 8-PropDesc              | OfficialSearchPart | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testwithpropertydescription","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"DN100","ExpectedPrice":4.0},"PrioritySearch":{"PriorityType":"Purchase","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit","ContinueIfFeeExceeds":"true","ContinueIfNameMismatch":"false","PropertyIdentification":{"PropertyDescription":"A House"},"TimeshareDetails":{"TimeshareLease":false,"TimePeriod":"TimePeriod"}}}                                  | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"testwithpropertydescription","ExpectedResponseDateTime":"0001-01-01T00:00:00","MessageDescription":"Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services."}}} |                |
| 9-Attachment            | OfficialSearchPart | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testwithpropertydescription","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"DN100","ExpectedPrice":4.0},"PrioritySearch":{"PriorityType":"Purchase","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit","ContinueIfFeeExceeds":"true","ContinueIfNameMismatch":"true","PropertyIdentification":{"PropertyDescription":"A House"},"TimeshareDetails":{"TimeshareLease":false,"TimePeriod":"TimePeriod"}}}                                  | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"testwithpropertydescription","ExpectedResponseDateTime":"0001-01-01T00:00:00","MessageDescription":"Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services."}}} |                |
| 10a1-Fees-True          | OfficialSearchPart | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testfeeindicator","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"DN100","ExpectedPrice":5.0},"PrioritySearch":{"PriorityType":"Purchase","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit","ContinueIfFeeExceeds":"true","ContinueIfNameMismatch":"true","PropertyIdentification":{"PropertyDescription":"A House"},"TimeshareDetails":{"TimeshareLease":false,"TimePeriod":"TimePeriod"}}}                                              | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"testfeeindicator","ExpectedResponseDateTime":"0001-01-01T00:00:00","MessageDescription":"Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services."}}}            |                |
#| 10a2-Fees-False         | OfficialSearchPart | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testfeeindicator","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"DN100","ExpectedPrice":5.0},"PrioritySearch":{"PriorityType":"Purchase","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit","ContinueIfFeeExceeds":"false","ContinueIfNameMismatch":"true","PropertyIdentification":{"PropertyDescription":"A House"},"TimeshareDetails":{"TimeshareLease":false,"TimePeriod":"TimePeriod"}}}                                             | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"testfeeindicator","ExpectedResponseDateTime":"0001-01-01T00:00:00","MessageDescription":"Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services."}}}            |                |
| 10a2-Fees-False         | OfficialSearchPart | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testfeeindicator","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"DN100","ExpectedPrice":5.0},"PrioritySearch":{"PriorityType":"Purchase","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit","ContinueIfFeeExceeds":"false","ContinueIfNameMismatch":"true","PropertyIdentification":{"PropertyDescription":"A House"},"TimeshareDetails":{"TimeshareLease":false,"TimePeriod":"TimePeriod"}}}                                             | {"Response":{"Status":"Rejection","Rejection":{"ExternalReference":"ExternalRef","RejectionResponse":{"Reason":"There is no name match for this title number.","Code":"bg.fee.feeMismatch","Errors":[]}}}}                                                                                                                                                                                   |                |
| 10b-Fees-LessThan4-True | OfficialSearchPart | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testfeeindicator","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"DN100","ExpectedPrice":3.0},"PrioritySearch":{"PriorityType":"Purchase","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit","ContinueIfFeeExceeds":"true","ContinueIfNameMismatch":"true","PropertyIdentification":{"PropertyDescription":"A House"},"TimeshareDetails":{"TimeshareLease":false,"TimePeriod":"TimePeriod"}}}                                              | {"Response":{"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"testfeeindicator","ExpectedResponseDateTime":"0001-01-01T00:00:00","MessageDescription":"Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services."}}}            |                |
| 10c-Fees-LessThan4-False | OfficialSearchPart | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testfeeindicator","ExternalRef":"ExternalRef","CustomerRef":"CustomerReference"},"Property":{"TitleNumber":"DN100","ExpectedPrice":3.0},"PrioritySearch":{"PriorityType":"Purchase","SearchFrom":"1969-07-16","PropreietorOrFirstApplicant":"Mr PropertyOwner","ApplicantNames":"Albert Fidgit","ContinueIfFeeExceeds":"false","ContinueIfNameMismatch":"true","PropertyIdentification":{"PropertyDescription":"A House"},"TimeshareDetails":{"TimeshareLease":false,"TimePeriod":"TimePeriod"}}}                                             | {"Response":{"Status":"Rejection","Rejection":{"ExternalReference":"ExternalRef","RejectionResponse":{"Reason":"There is no name match for this title number.","Code":"bg.fee.feeMismatch","Errors":[]}}}}                                                                                                                                                                                   |                |


@OfficialSearchPartPoll
Scenario: OfficialSearchPartPoll
	Given For a given property detail <Payload>
	And The Expected Message Details will be <MessageDetails>
	And A different <UserName> and <Password>
	When I call the land registy <Request>
	Then I should receive <Response>
Examples: 
| Test         | Request                | UserName  | Password   | Payload                                                  | Response                                                                                                                                                                                                                                                                                                                                                                           | MessageDetails                                                                                                                                               |
| 11-NYP       | PollOfficialSearchPart | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testpollstilloutofhours"}}  | {"Response": {"Status": "Acknowledgement","Acknowledgement": {"UniqueMsgId": "polloutofhours","MessageDescription": "Request has not yet been processed."}}}                                                                                                                                                                                                                       |                                                                                                                                                              |
| 12-LodgedRes | PollOfficialSearchPart | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testpolllodged"}}           | {"Response": {"Status":"Acknowledgement","Acknowledgement":{"UniqueMsgId":"testfeeindicator","ExpectedResponseDateTime":"0001-01-01T00:00:00","MessageDescription":"Your application has been entered on the day list. It will be dealt with in accordance with our service standards. See https://www.gov.uk/government/organisations/land-registry/about/about-our-services."}}} |                                                                                                                                                              |
| 13-Error     | PollOfficialSearchPart | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testpollerror"}}            | {"Response": {"Status":"Rejection","Rejection":{"ExternalReference":"Ext_ref","RejectionResponse":{"Reason":"There is no name match for this title number.","Code":"bg.state.nonamematch","Errors":[]}}}}                                                                                                                                                                          |                                                                                                                                                              |
| 14-ElecRes   | PollOfficialSearchPart | BGUser001 | landreg001 | {"Reference":{"UniqueMsgId":"testpollelectronicresult"}} | {"Response": {"Status": "Success","Results": {"ExternalReference": "zzz"}}}                                                                                                                                                                                                                                                                                                        | {"HMLRReference":"Y0WCJVR","ActualPrice":7.00,"Attachment":{"EmbeddedFileBinaryObject":{"format":"pdf"},"Date":"0001-01-01T00:00:00"},"ResultTypeCode":"10"} |





