<?xml version='1.0' encoding='UTF-8'?><definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://bankruptcyv2_1.ws.bg.lr.gov/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns="http://schemas.xmlsoap.org/wsdl/" name="BankruptcySearchV2_0WebService" targetNamespace="http://bankruptcyv2_1.ws.bg.lr.gov/">
  <types>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://bankruptcyv2_1.ws.bg.lr.gov/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns3="http://bankruptcyv2_1.ws.bg.lr.gov/" xmlns:ns2="http://www.oscre.org/ns/eReg-Final/2011/ResponseLandChargesBankruptcySearchV2_0" xmlns:ns1="http://www.oscre.org/ns/eReg-Final/2011/RequestLandChargesBankruptcySearchV2_1" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://bankruptcyv2_1.ws.bg.lr.gov/">
			
  <xsd:import namespace="http://www.oscre.org/ns/eReg-Final/2011/RequestLandChargesBankruptcySearchV2_1" schemaLocation="https://bgtest.landregistry.gov.uk/b2b/BGStubService/BankruptcySearchV2_1WebService?xsd=RequestLandChargesBankruptcySearchV2_1.xsd"/>
			
  <xsd:import namespace="http://www.oscre.org/ns/eReg-Final/2011/ResponseLandChargesBankruptcySearchV2_0" schemaLocation="https://bgtest.landregistry.gov.uk/b2b/BGStubService/BankruptcySearchV2_1WebService?xsd=ResponseLandChargesBankruptcySearchV2_0.xsd"/>
			
  <xsd:element name="SOAPEngineSystemException" nillable="true" type="xsd:string"/>
			
  <xsd:element name="bankruptcySearch" type="ns3:bankruptcySearch"/>
			
  <xsd:element name="bankruptcySearchResponse" type="ns3:bankruptcySearchResponse"/>
			
  <xsd:complexType name="bankruptcySearch">
				
    <xsd:sequence>
					
      <xsd:element minOccurs="0" name="arg0" type="ns1:RequestLandChargesBankruptcySearchV2_1Type"/>
				
    </xsd:sequence>
			
  </xsd:complexType>
			
  <xsd:complexType name="bankruptcySearchResponse">
				
    <xsd:sequence>
					
      <xsd:element minOccurs="0" name="return" type="ns2:ResponseLandChargesBankruptcySearchV2_0Type"/>
				
    </xsd:sequence>
			
  </xsd:complexType>
		
</xsd:schema>
  </types>
  <message name="bankruptcySearchResponse">
    <part element="tns:bankruptcySearchResponse" name="parameters">
    </part>
  </message>
  <message name="SOAPEngineSystemException">
    <part element="tns:SOAPEngineSystemException" name="fault">
    </part>
  </message>
  <message name="bankruptcySearch">
    <part element="tns:bankruptcySearch" name="parameters">
    </part>
  </message>
  <portType name="BankruptcySearchV2_1Service">
    <operation name="bankruptcySearch">
      <input message="tns:bankruptcySearch">
    </input>
      <output message="tns:bankruptcySearchResponse">
    </output>
      <fault message="tns:SOAPEngineSystemException" name="SOAPEngineSystemException">
    </fault>
    </operation>
  </portType>
  <binding name="BankruptcySearchV2_1WSImplPortBinding" type="tns:BankruptcySearchV2_1Service">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="bankruptcySearch">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="SOAPEngineSystemException">
        <soap:fault name="SOAPEngineSystemException" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="BankruptcySearchV2_1WebService">
    <port binding="tns:BankruptcySearchV2_1WSImplPortBinding" name="BankruptcySearchV2_1WSImplPort">
      <soap:address location="https://bgtest.landregistry.gov.uk/b2b/BGStubService/BankruptcySearchV2_1WebService"/>
    </port>
  </service>
</definitions>