<?xml version='1.0' encoding='UTF-8'?><definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://poll.fullsearchv2_0.ws.bg.lr.gov/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns="http://schemas.xmlsoap.org/wsdl/" name="FullSearchV2_0PollRequestWebService" targetNamespace="http://poll.fullsearchv2_0.ws.bg.lr.gov/">
  <types>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://poll.fullsearchv2_0.ws.bg.lr.gov/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns3="http://poll.fullsearchv2_0.ws.bg.lr.gov/" xmlns:ns2="http://www.oscre.org/ns/eReg-Final/2011/ResponseLandChargesFullSearchV2_0" xmlns:ns1="http://www.oscre.org/ns/eReg/MR01-20090605/PollRequest" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://poll.fullsearchv2_0.ws.bg.lr.gov/">
			
  <xsd:import namespace="http://www.oscre.org/ns/eReg/MR01-20090605/PollRequest" schemaLocation="https://bgtest.landregistry.gov.uk/b2b/BGStubService/FullSearchV2_0PollRequestWebService?xsd=PollRequest.xsd"/>
			
  <xsd:import namespace="http://www.oscre.org/ns/eReg-Final/2011/ResponseLandChargesFullSearchV2_0" schemaLocation="https://bgtest.landregistry.gov.uk/b2b/BGStubService/FullSearchV2_0PollRequestWebService?xsd=ResponseLandChargesFullSearchV2_0.xsd"/>
		        
  <xsd:element name="SOAPEngineSystemException" nillable="true" type="xsd:string"/>
				
  <xsd:element name="getResponse" type="ns3:getResponse"/>
				
  <xsd:element name="getResponseResponse" type="ns3:getResponseResponse"/>
				
  <xsd:complexType name="getResponse">
				    
    <xsd:sequence>
					     
      <xsd:element minOccurs="0" name="arg0" type="ns1:PollRequestType"/>
				    
    </xsd:sequence>
				
  </xsd:complexType>
				
  <xsd:complexType name="getResponseResponse">
					
    <xsd:sequence>
					     
      <xsd:element minOccurs="0" name="return" type="ns2:LandChargesFullSearchResponseV2_0Type"/>
				    
    </xsd:sequence>
				 
  </xsd:complexType>
  	 	
</xsd:schema>
  </types>
  <message name="SOAPEngineSystemException">
    <part element="tns:SOAPEngineSystemException" name="fault">
    </part>
  </message>
  <message name="fullSearchPollResponse">
    <part element="tns:getResponseResponse" name="parameters">
    </part>
  </message>
  <message name="fullSearchPollRequest">
    <part element="tns:getResponse" name="parameters">
    </part>
  </message>
  <portType name="FullSearchV2_0PollService">
    <operation name="getResponse">
      <input message="tns:fullSearchPollRequest">
    </input>
      <output message="tns:fullSearchPollResponse">
    </output>
      <fault message="tns:SOAPEngineSystemException" name="SOAPEngineSystemException">
    </fault>
    </operation>
  </portType>
  <binding name="FullSearchV2_0PollRequestWSImplPortBinding" type="tns:FullSearchV2_0PollService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="getResponse">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="SOAPEngineSystemException">
        <soap:fault name="SOAPEngineSystemException" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="FullSearchV2_0PollRequestWebService">
    <port binding="tns:FullSearchV2_0PollRequestWSImplPortBinding" name="FullSearchV2_0PollRequestWSImplPort">
      <soap:address location="https://bgtest.landregistry.gov.uk/b2b/BGStubService/FullSearchV2_0PollRequestWebService"/>
    </port>
  </service>
</definitions>