<?xml version='1.0' encoding='UTF-8'?><definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://searchofindexmapv2_0.ws.bg.lr.gov/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns="http://schemas.xmlsoap.org/wsdl/" name="searchofindexmapv2_0WebService" targetNamespace="http://searchofindexmapv2_0.ws.bg.lr.gov/">
  <types>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://searchofindexmapv2_0.ws.bg.lr.gov/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns3="http://searchofindexmapv2_0.ws.bg.lr.gov/" xmlns:ns2="http://www.oscre.org/ns/eReg-Final/2011/ResponseSearchOfIndexMapV2_0" xmlns:ns1="http://www.oscre.org/ns/eReg-Final/2011/RequestSearchOfIndexMapV2_0" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://searchofindexmapv2_0.ws.bg.lr.gov/">
			
  <xsd:import namespace="http://www.oscre.org/ns/eReg-Final/2011/RequestSearchOfIndexMapV2_0" schemaLocation="https://bgtest.landregistry.gov.uk/b2b/BGStubService/SearchOfIndexMapV2_0WebService?xsd=RequestSearchOfIndexMapV2_0.xsd"/>
			
  <xsd:import namespace="http://www.oscre.org/ns/eReg-Final/2011/ResponseSearchOfIndexMapV2_0" schemaLocation="https://bgtest.landregistry.gov.uk/b2b/BGStubService/SearchOfIndexMapV2_0WebService?xsd=ResponseSearchOfIndexMapV2_0.xsd"/>
			
  <xsd:element name="SOAPEngineSystemException" nillable="true" type="xsd:string"/>
			
  <xsd:element name="searchOfIndexMap" type="ns3:searchOfIndexMap"/>
			
  <xsd:element name="searchOfIndexMapResponse" type="ns3:searchOfIndexMapResponse"/>
			
  <xsd:complexType name="searchOfIndexMap">
				
    <xsd:sequence>
					
      <xsd:element minOccurs="0" name="arg0" type="ns1:RequestSearchOfIndexMapV2_0Type"/>
				
    </xsd:sequence>
			
  </xsd:complexType>
			
  <xsd:complexType name="searchOfIndexMapResponse">
				
    <xsd:sequence>
					
      <xsd:element minOccurs="0" name="return" type="ns2:SearchOfIndexMapResponseV2_0Type"/>
				
    </xsd:sequence>
			
  </xsd:complexType>
		
</xsd:schema>
  </types>
  <message name="searchOfIndexMap">
    <part element="tns:searchOfIndexMap" name="parameters">
    </part>
  </message>
  <message name="SOAPEngineSystemException">
    <part element="tns:SOAPEngineSystemException" name="fault">
    </part>
  </message>
  <message name="searchOfIndexMapResponse">
    <part element="tns:searchOfIndexMapResponse" name="parameters">
    </part>
  </message>
  <portType name="SearchOfIndexMapV2_0Service">
    <operation name="searchOfIndexMap">
      <input message="tns:searchOfIndexMap">
    </input>
      <output message="tns:searchOfIndexMapResponse">
    </output>
      <fault message="tns:SOAPEngineSystemException" name="SOAPEngineSystemException">
    </fault>
    </operation>
  </portType>
  <binding name="SearchOfIndexMapV2_0WSImplPortBinding" type="tns:SearchOfIndexMapV2_0Service">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="searchOfIndexMap">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="SOAPEngineSystemException">
        <soap:fault name="SOAPEngineSystemException" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="SearchOfIndexMapV2_0WebService">
    <port binding="tns:SearchOfIndexMapV2_0WSImplPortBinding" name="SearchOfIndexMapV2_0WSImplPort">
      <soap:address location="https://bgtest.landregistry.gov.uk/b2b/BGStubService/SearchOfIndexMapV2_0WebService"/>
    </port>
  </service>
</definitions>