@startuml
class FromTitleKnownOfficialCopy {
    + FromTitleKnownOfficialCopy()
}
class TitleOfficalCopyMessageDetailConverter {
    + Convert(source:Q1ResultsType5, destination:MessageDetails, context:ResolutionContext) : MessageDetails
}
class "ITypeConverter`2"<T1,T2> {
}
Profile <|-- FromTitleKnownOfficialCopy
"ITypeConverter`2" "<Q1ResultsType5,MessageDetails>" <|-- TitleOfficalCopyMessageDetailConverter
@enduml
