@startuml 
!include <C4/C4_Container>
!include <azure/AzureCommon>
!include <azure/Integration/AzureServiceBusTopic>
!include <azure/Web/AzureAPIManagement>

LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()
AddElementTag("microService", $shape=EightSidedShape(), $fontColor="white", $legendText="micro service\neight sided")
AddElementTag("storage", $shape=RoundedBoxShape(), $fontColor="white")

SHOW_PERSON_OUTLINE()
Person( user, User, "A User")
System(hub, "Hub") 
AzureServiceBusTopic(to, "New\Updated Properties", "Integration")
AzureServiceBusTopic(from, "Title/Deed References", "Integration")
AzureAPIManagement(apim, "APIM", "Management")
System(app, "Land Registry Service", "Requests details from the registry concerning ownership", $tags = "microService")  
System(doc, "DocMgr Service", "Document Management", $tags = "microService")
Container_Boundary(svc, "External Property Title Service", "Manages Property Titles", "") {
    System_Ext(lrsvc, "Land Registry", "UK Goverment Agency")    
    System_Ext(nimsvc, "Land Registry", "Nimbus")    
}

Rel(user, hub, "Adds a new property", "Https")
Rel(hub, to, "Hub Publish")
Rel(hub, from, "Hub Subscribe")
Rel_U(app, from, "Publish")
Rel_U(app, to, "Subscribe")

Rel(hub, apim, "Ad-hoc Rest API calls", "Https")
Rel(apim, app, "")
Rel(app, svc, "Request property title deeds", "Https")
Rel(app, doc, "Send Deed to DocMgr")
Rel(svc, app, "Report")

Rel_U(hub, user, "Notificition")

@enduml