@startuml
class ToOfficialSearchPart {
    + ToOfficialSearchPart()
    + Contact(cont:Contact) : Q1ContactType6[]
    + PriorityCodeType(type:string) : PriorityCodeContentType1
    + PropertyId(src:PropertyIdentification) : object
}
Profile <|-- ToOfficialSearchPart
@enduml
