@startuml
class FindResponse {
    + Status : string <<get>> <<set>>
    + AddressId : string <<get>> <<set>>
    + PropertyName : string <<get>> <<set>>
    + PropertyNumber : string <<get>> <<set>>
    + Line1 : string <<get>> <<set>>
    + Line2 : string <<get>> <<set>>
    + Line3 : string <<get>> <<set>>
    + City : string <<get>> <<set>>
    + County : string <<get>> <<set>>
    + PostCode : string <<get>> <<set>>
}
@enduml
