@startuml
class TitleOfficalCopyMessageDetails {
    + Description : string <<get>> <<set>>
    + HMLRReference : string <<get>> <<set>>
    + ActualPrice : decimal <<get>> <<set>>
    + ResultTypeCode : string <<get>> <<set>>
    + <<override>> Equals(obj:object) : bool
    + <<override>> GetHashCode() : int
}
class Attachment {
    + Title : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + CopyrightNotices : string <<get>> <<set>>
    + <<override>> Equals(obj:object) : bool
    + <<override>> GetHashCode() : int
}
class BinaryObjectType {
    + filename : string <<get>> <<set>>
    + format : string <<get>> <<set>>
    + mimeCode : string <<get>> <<set>>
    + characterSetCode : string <<get>> <<set>>
    + <<override>> Equals(obj:object) : bool
    + <<override>> GetHashCode() : int
}
class "EqualityComparer`1"<T> {
}
MessageDetails <|-- TitleOfficalCopyMessageDetails
TitleOfficalCopyMessageDetails --> "Attachment" Attachment
Attachment --> "EmbeddedFileBinaryObject" BinaryObjectType
Attachment --> "Date" DateTime
@enduml
