// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace KnightFrank.Hub.LandRegistry.ApiTests
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ApplicationEnquiryFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "", "ApplicationEnquiry", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "ApplicationEnquiry.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("ApplicationEnquiry.feature", "Feature: ApplicationEnquiry\r\n\r\nA short summary of the feature\r\n\r\n@API-Application" +
                    "Enquiry\r\nScenario: API-ApplicationEnquiry\r\n\tGiven UniqueMsgId <UniqueMsgId>\r\n\tAn" +
                    "d TitleNumber <TitleNumber>\r\n\tAnd ClosedAndContinued Flag <ClosedAndContinued>\r\n" +
                    "\tAnd ClosedAndContinued Flag <ContinueIfFeeExceeds>\r\n\tAnd ApplicationReference <" +
                    "ApplicationReference>\r\n\tWhen I call the land registy API\r\n\tThen I should recieve" +
                    " a LandregistryDTO response <Response>\r\nExamples: \r\n| Test                      " +
                    "  | UniqueMsgId                       | TitleNumber | ApplicationReference | Clo" +
                    "sedAndContinued | ContinueIfFeeExceeds | Response |\r\n| 1-MultipleReturned       " +
                    "   | success-many-results              | DN100       |                      | Tr" +
                    "ue               | False                |          |\r\n| 2-OneReturned           " +
                    "    | success-one-result                | DN101       |                      | T" +
                    "rue               | False                |          |\r\n| 3-AppRefOneReturned    " +
                    "     | application-reference-one-result  |             | U565LDE              | " +
                    "False              | False                |          |\r\n| 4-AppRefClosed30Days  " +
                    "      | application-reference-thirty-days |             | G665YYG              |" +
                    " False              | False                |          |\r\n| 5-NoneReturned       " +
                    "       | success-no-results                | DN102       |                      " +
                    "| False              | True                 |          |\r\n| 6-TitleIsClosed     " +
                    "        | closed-title-number               | DN999       |                     " +
                    " | False              | True                 |          |\r\n| 7-TitleIsClosedAndC" +
                    "ontinued | closed-and-continue               | BK554444    |                    " +
                    "  | True               | False                |          |\r\n| 8-TitleIsNotFound " +
                    "          | title-number-not-found            | DY100       |                   " +
                    "   | True               | False                |          |\r\n| 9-AccessDenied   " +
                    "           | access-denied                     | DN100       |                  " +
                    "    | True               | False                |          |\r\n| 10-OutOfHours   " +
                    "            | out-of-hours                      | DN100       |                 " +
                    "     | True               | False                |          |\r\n\r\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("ApplicationEnquiry.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "ApplicationEnquiry", "A short summary of the feature", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(5, new System.Nullable<long>(1)), "@API-ApplicationEnquiry", "52e95c6869096d519e443a7569d940e8")}), "Scenario", "API-ApplicationEnquiry", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(2)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "UniqueMsgId <UniqueMsgId>", null, null, "42e31dabc5d48f5794ab43fa4f6ae651"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "TitleNumber <TitleNumber>", null, null, "5ea05720980e6556a0f602024c001621"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "ClosedAndContinued Flag <ClosedAndContinued>", null, null, "e630489701feab50b29187d89e48e1be"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "ClosedAndContinued Flag <ContinueIfFeeExceeds>", null, null, "37726f71e25ad854979e0037e7e0f051"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(2)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "ApplicationReference <ApplicationReference>", null, null, "ab679dbba1c96953af938dbaf68f9683"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(2)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I call the land registy API", null, null, "3c58a01aa9c423548e06fe9797a73efd"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(2)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "I should recieve a LandregistryDTO response <Response>", null, null, "efcb76549feacd53bdfcc191257b1568")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[] {
                                                    new global::Io.Cucumber.Messages.Types.Examples(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Examples", "", "", new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(3)), "Test"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(33)), "UniqueMsgId"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(69)), "TitleNumber"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(83)), "ApplicationReference"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(106)), "ClosedAndContinued"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(127)), "ContinueIfFeeExceeds"),
                                                                        new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(150)), "Response")}), "f6481f813f2cc255bdcac16be5119b90"), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableRow>(new global::Io.Cucumber.Messages.Types.TableRow[] {
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(3)), "1-MultipleReturned"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(33)), "success-many-results"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(69)), "DN100"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(104)), ""),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(106)), "True"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(127)), "False"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(159)), "")}), "ac992dcfa8af2e52911b0953390ce22d"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(3)), "2-OneReturned"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(33)), "success-one-result"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(69)), "DN101"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(104)), ""),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(106)), "True"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(127)), "False"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(159)), "")}), "45458057db78ed5c92f94d5f71ada9b8"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(3)), "3-AppRefOneReturned"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(33)), "application-reference-one-result"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(81)), ""),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(83)), "U565LDE"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(106)), "False"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(127)), "False"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(159)), "")}), "eefca62141885a5abb4ac9c333a56c51"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(3)), "4-AppRefClosed30Days"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(33)), "application-reference-thirty-days"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(81)), ""),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(83)), "G665YYG"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(106)), "False"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(127)), "False"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(159)), "")}), "5da26fb455bf3e5994ce3653cf35c972"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(3)), "5-NoneReturned"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(33)), "success-no-results"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(69)), "DN102"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(104)), ""),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(106)), "False"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(127)), "True"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(159)), "")}), "7ece8c48b1b84352b0fd1bb5e7ab32a6"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(3)), "6-TitleIsClosed"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(33)), "closed-title-number"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(69)), "DN999"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(104)), ""),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(106)), "False"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(127)), "True"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(159)), "")}), "dbc8e811c9b7225c9cb56fe40c401fe0"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(3)), "7-TitleIsClosedAndContinued"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(33)), "closed-and-continue"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(69)), "BK554444"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(104)), ""),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(106)), "True"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(127)), "False"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(159)), "")}), "f1d23f19bc05c857b19dc8e858c3c04b"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(3)), "8-TitleIsNotFound"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(33)), "title-number-not-found"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(69)), "DY100"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(104)), ""),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(106)), "True"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(127)), "False"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(159)), "")}), "ad15646696186c55840c123cd35ca266"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(3)), "9-AccessDenied"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(33)), "access-denied"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(69)), "DN100"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(104)), ""),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(106)), "True"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(127)), "False"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(159)), "")}), "ea66e0531b38325fb2cc9e6ecdfd9016"),
                                                                    new global::Io.Cucumber.Messages.Types.TableRow(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.TableCell>(new global::Io.Cucumber.Messages.Types.TableCell[] {
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(3)), "10-OutOfHours"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(33)), "out-of-hours"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(69)), "DN100"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(104)), ""),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(106)), "True"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(127)), "False"),
                                                                                    new global::Io.Cucumber.Messages.Types.TableCell(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(159)), "")}), "87826c0985152c5bb133bf8f4c34c421")}), "c58f9f852da8c954bdfce30c7a434f54")}), "b3552b65b5f64c5e966de04fa33bd047"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("ab8c60ebd00d9e5086b0130687a838ab", "ApplicationEnquiry.feature", "API-ApplicationEnquiry", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "42e31dabc5d48f5794ab43fa4f6ae651",
                                                        "ac992dcfa8af2e52911b0953390ce22d"}), "e4490347dfaefb58b95e6d25e0fbbf3e", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "UniqueMsgId success-many-results"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5ea05720980e6556a0f602024c001621",
                                                        "ac992dcfa8af2e52911b0953390ce22d"}), "b34dc198cc55b5588f14d7994af81eda", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "TitleNumber DN100"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e630489701feab50b29187d89e48e1be",
                                                        "ac992dcfa8af2e52911b0953390ce22d"}), "484358c45ba4295a850c1789fec8dedd", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ClosedAndContinued Flag True"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "37726f71e25ad854979e0037e7e0f051",
                                                        "ac992dcfa8af2e52911b0953390ce22d"}), "84c7b1fd818de55b969af0bfbffc44e5", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ClosedAndContinued Flag False"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ab679dbba1c96953af938dbaf68f9683",
                                                        "ac992dcfa8af2e52911b0953390ce22d"}), "35df942e9b521a588179a05f2a6bf07b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ApplicationReference "),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3c58a01aa9c423548e06fe9797a73efd",
                                                        "ac992dcfa8af2e52911b0953390ce22d"}), "5949488972aca15fbfc8cd6862977b4d", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I call the land registy API"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "efcb76549feacd53bdfcc191257b1568",
                                                        "ac992dcfa8af2e52911b0953390ce22d"}), "1b457b6ce7cbe95b9a113da4b895be42", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should recieve a LandregistryDTO response ")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@API-ApplicationEnquiry", "52e95c6869096d519e443a7569d940e8")}), new System.Collections.Generic.List<string>(new string[] {
                                        "b3552b65b5f64c5e966de04fa33bd047",
                                        "ac992dcfa8af2e52911b0953390ce22d"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("054bd471108e5354a98c3598bcc28732", "ApplicationEnquiry.feature", "API-ApplicationEnquiry", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "42e31dabc5d48f5794ab43fa4f6ae651",
                                                        "45458057db78ed5c92f94d5f71ada9b8"}), "2b02689395316c5483726e19730a1c4b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "UniqueMsgId success-one-result"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5ea05720980e6556a0f602024c001621",
                                                        "45458057db78ed5c92f94d5f71ada9b8"}), "821c56af1ef3fe5b891de3e39b6a5260", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "TitleNumber DN101"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e630489701feab50b29187d89e48e1be",
                                                        "45458057db78ed5c92f94d5f71ada9b8"}), "73740d2f59699f5c86eb5c32d4377fa1", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ClosedAndContinued Flag True"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "37726f71e25ad854979e0037e7e0f051",
                                                        "45458057db78ed5c92f94d5f71ada9b8"}), "519ea70f4c7a4f5896c534df5da4c6c3", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ClosedAndContinued Flag False"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ab679dbba1c96953af938dbaf68f9683",
                                                        "45458057db78ed5c92f94d5f71ada9b8"}), "afaf64e925497a5f929e373335c8e354", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ApplicationReference "),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3c58a01aa9c423548e06fe9797a73efd",
                                                        "45458057db78ed5c92f94d5f71ada9b8"}), "608d6a15c93bec59ae2570185dd71d27", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I call the land registy API"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "efcb76549feacd53bdfcc191257b1568",
                                                        "45458057db78ed5c92f94d5f71ada9b8"}), "5309cafe0a8e6655a7f2924e1e0eb41e", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should recieve a LandregistryDTO response ")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@API-ApplicationEnquiry", "52e95c6869096d519e443a7569d940e8")}), new System.Collections.Generic.List<string>(new string[] {
                                        "b3552b65b5f64c5e966de04fa33bd047",
                                        "45458057db78ed5c92f94d5f71ada9b8"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("7e5c85f66225a95ab560595f7cd8be5a", "ApplicationEnquiry.feature", "API-ApplicationEnquiry", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "42e31dabc5d48f5794ab43fa4f6ae651",
                                                        "eefca62141885a5abb4ac9c333a56c51"}), "4775c168982a5959b9831464833cb073", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "UniqueMsgId application-reference-one-result"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5ea05720980e6556a0f602024c001621",
                                                        "eefca62141885a5abb4ac9c333a56c51"}), "1b58f38e6ed42b5c9637f0e15ef43764", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "TitleNumber "),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e630489701feab50b29187d89e48e1be",
                                                        "eefca62141885a5abb4ac9c333a56c51"}), "49d96e2dec17605cba3a146323bc465c", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ClosedAndContinued Flag False"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "37726f71e25ad854979e0037e7e0f051",
                                                        "eefca62141885a5abb4ac9c333a56c51"}), "aba7db3a5b804556a940691b7ab5ada6", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ClosedAndContinued Flag False"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ab679dbba1c96953af938dbaf68f9683",
                                                        "eefca62141885a5abb4ac9c333a56c51"}), "b4c40178ca9ada51aea78ae589a73119", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ApplicationReference U565LDE"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3c58a01aa9c423548e06fe9797a73efd",
                                                        "eefca62141885a5abb4ac9c333a56c51"}), "3e92427322ecb651b69720b153577ea1", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I call the land registy API"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "efcb76549feacd53bdfcc191257b1568",
                                                        "eefca62141885a5abb4ac9c333a56c51"}), "383629b8b6e56e5db48907d0b1617e73", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should recieve a LandregistryDTO response ")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@API-ApplicationEnquiry", "52e95c6869096d519e443a7569d940e8")}), new System.Collections.Generic.List<string>(new string[] {
                                        "b3552b65b5f64c5e966de04fa33bd047",
                                        "eefca62141885a5abb4ac9c333a56c51"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("f8b253d97fea0955b135d7991cd11885", "ApplicationEnquiry.feature", "API-ApplicationEnquiry", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "42e31dabc5d48f5794ab43fa4f6ae651",
                                                        "5da26fb455bf3e5994ce3653cf35c972"}), "94f9a8d22cc95b519dfe6c5a4d84b78d", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "UniqueMsgId application-reference-thirty-days"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5ea05720980e6556a0f602024c001621",
                                                        "5da26fb455bf3e5994ce3653cf35c972"}), "9f4ce938220e58518a6f755b8d17ac8b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "TitleNumber "),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e630489701feab50b29187d89e48e1be",
                                                        "5da26fb455bf3e5994ce3653cf35c972"}), "215da1d2ae4e135aa927024cd5acb702", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ClosedAndContinued Flag False"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "37726f71e25ad854979e0037e7e0f051",
                                                        "5da26fb455bf3e5994ce3653cf35c972"}), "5b2e6bdd1db10e59b0ccfe2a76019948", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ClosedAndContinued Flag False"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ab679dbba1c96953af938dbaf68f9683",
                                                        "5da26fb455bf3e5994ce3653cf35c972"}), "c1a63ded17bc4d5986c75f822d6ceaf9", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ApplicationReference G665YYG"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3c58a01aa9c423548e06fe9797a73efd",
                                                        "5da26fb455bf3e5994ce3653cf35c972"}), "46a668df6c19f5599068725bf3864c2b", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I call the land registy API"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "efcb76549feacd53bdfcc191257b1568",
                                                        "5da26fb455bf3e5994ce3653cf35c972"}), "f4fd5fa2bba5595cbf898e05513d76c3", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should recieve a LandregistryDTO response ")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@API-ApplicationEnquiry", "52e95c6869096d519e443a7569d940e8")}), new System.Collections.Generic.List<string>(new string[] {
                                        "b3552b65b5f64c5e966de04fa33bd047",
                                        "5da26fb455bf3e5994ce3653cf35c972"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("974a02736de76855a07bfc509f4f5ce3", "ApplicationEnquiry.feature", "API-ApplicationEnquiry", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "42e31dabc5d48f5794ab43fa4f6ae651",
                                                        "7ece8c48b1b84352b0fd1bb5e7ab32a6"}), "3243a0967ac9f059a78ea48457bdb334", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "UniqueMsgId success-no-results"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5ea05720980e6556a0f602024c001621",
                                                        "7ece8c48b1b84352b0fd1bb5e7ab32a6"}), "337d8210c1348450b94d7bcf536a35ff", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "TitleNumber DN102"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e630489701feab50b29187d89e48e1be",
                                                        "7ece8c48b1b84352b0fd1bb5e7ab32a6"}), "dddb37a5a0c33a5e860c2a9e28dbaa7b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ClosedAndContinued Flag False"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "37726f71e25ad854979e0037e7e0f051",
                                                        "7ece8c48b1b84352b0fd1bb5e7ab32a6"}), "94942fa59c785e538ec4f82b0e27027b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ClosedAndContinued Flag True"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ab679dbba1c96953af938dbaf68f9683",
                                                        "7ece8c48b1b84352b0fd1bb5e7ab32a6"}), "b5ec1d411aa3785f85f7d33fd6b4b30b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ApplicationReference "),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3c58a01aa9c423548e06fe9797a73efd",
                                                        "7ece8c48b1b84352b0fd1bb5e7ab32a6"}), "a9c80b8f8c76c654aa1a056de7a0be2e", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I call the land registy API"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "efcb76549feacd53bdfcc191257b1568",
                                                        "7ece8c48b1b84352b0fd1bb5e7ab32a6"}), "76955cce93921c51bc30754262a79664", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should recieve a LandregistryDTO response ")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@API-ApplicationEnquiry", "52e95c6869096d519e443a7569d940e8")}), new System.Collections.Generic.List<string>(new string[] {
                                        "b3552b65b5f64c5e966de04fa33bd047",
                                        "7ece8c48b1b84352b0fd1bb5e7ab32a6"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("61215d15f627f25c9ced4fb170a28f76", "ApplicationEnquiry.feature", "API-ApplicationEnquiry", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "42e31dabc5d48f5794ab43fa4f6ae651",
                                                        "dbc8e811c9b7225c9cb56fe40c401fe0"}), "6af60f23cfddc556ba0b83b9ba8c3e33", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "UniqueMsgId closed-title-number"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5ea05720980e6556a0f602024c001621",
                                                        "dbc8e811c9b7225c9cb56fe40c401fe0"}), "3f6f5a9ec335645494c485b50580fea9", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "TitleNumber DN999"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e630489701feab50b29187d89e48e1be",
                                                        "dbc8e811c9b7225c9cb56fe40c401fe0"}), "2de2b43cd294fc5681d20a1de597d838", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ClosedAndContinued Flag False"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "37726f71e25ad854979e0037e7e0f051",
                                                        "dbc8e811c9b7225c9cb56fe40c401fe0"}), "8feb1af8e0611658945a092ee7c8ad20", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ClosedAndContinued Flag True"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ab679dbba1c96953af938dbaf68f9683",
                                                        "dbc8e811c9b7225c9cb56fe40c401fe0"}), "0d12f2b89924ea518622398423bbdbfc", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ApplicationReference "),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3c58a01aa9c423548e06fe9797a73efd",
                                                        "dbc8e811c9b7225c9cb56fe40c401fe0"}), "fdfb33c31b3a7d5ebbdf5070cb6e95d8", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I call the land registy API"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "efcb76549feacd53bdfcc191257b1568",
                                                        "dbc8e811c9b7225c9cb56fe40c401fe0"}), "ea662b9adf32c6548084ce5895db6e02", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should recieve a LandregistryDTO response ")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@API-ApplicationEnquiry", "52e95c6869096d519e443a7569d940e8")}), new System.Collections.Generic.List<string>(new string[] {
                                        "b3552b65b5f64c5e966de04fa33bd047",
                                        "dbc8e811c9b7225c9cb56fe40c401fe0"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("1e1090aad6c42d579b68390d12211345", "ApplicationEnquiry.feature", "API-ApplicationEnquiry", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "42e31dabc5d48f5794ab43fa4f6ae651",
                                                        "f1d23f19bc05c857b19dc8e858c3c04b"}), "98fc380ab93b0e5eb43ec1fd08a31f17", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "UniqueMsgId closed-and-continue"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5ea05720980e6556a0f602024c001621",
                                                        "f1d23f19bc05c857b19dc8e858c3c04b"}), "cda3b4519a415353821f62aaee1e4b3d", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "TitleNumber BK554444"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e630489701feab50b29187d89e48e1be",
                                                        "f1d23f19bc05c857b19dc8e858c3c04b"}), "f7dd34059a011850bbb16a6000996096", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ClosedAndContinued Flag True"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "37726f71e25ad854979e0037e7e0f051",
                                                        "f1d23f19bc05c857b19dc8e858c3c04b"}), "576e0371a95dee589928a2e2a8c6e6fb", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ClosedAndContinued Flag False"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ab679dbba1c96953af938dbaf68f9683",
                                                        "f1d23f19bc05c857b19dc8e858c3c04b"}), "708285ce15843259947fcb6512c4cfd7", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ApplicationReference "),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3c58a01aa9c423548e06fe9797a73efd",
                                                        "f1d23f19bc05c857b19dc8e858c3c04b"}), "f737918918bf455583ab97f4e3367103", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I call the land registy API"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "efcb76549feacd53bdfcc191257b1568",
                                                        "f1d23f19bc05c857b19dc8e858c3c04b"}), "47ac6e77795b6851aa11f581908ed8d1", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should recieve a LandregistryDTO response ")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@API-ApplicationEnquiry", "52e95c6869096d519e443a7569d940e8")}), new System.Collections.Generic.List<string>(new string[] {
                                        "b3552b65b5f64c5e966de04fa33bd047",
                                        "f1d23f19bc05c857b19dc8e858c3c04b"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("4daeba45ace79a5a8fd6dc5e94d73c58", "ApplicationEnquiry.feature", "API-ApplicationEnquiry", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "42e31dabc5d48f5794ab43fa4f6ae651",
                                                        "ad15646696186c55840c123cd35ca266"}), "ba37f53ae38ba657b647a0194b1df64f", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "UniqueMsgId title-number-not-found"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5ea05720980e6556a0f602024c001621",
                                                        "ad15646696186c55840c123cd35ca266"}), "b4b8f96497db155c9c767d6ed1b8308c", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "TitleNumber DY100"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e630489701feab50b29187d89e48e1be",
                                                        "ad15646696186c55840c123cd35ca266"}), "0da2138ae6f27952910846cbe45f1fdd", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ClosedAndContinued Flag True"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "37726f71e25ad854979e0037e7e0f051",
                                                        "ad15646696186c55840c123cd35ca266"}), "81e0f8cec05f4057961433eb5152fc90", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ClosedAndContinued Flag False"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ab679dbba1c96953af938dbaf68f9683",
                                                        "ad15646696186c55840c123cd35ca266"}), "e0ae4f4bdeaf40589c9e034de79cb0d6", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ApplicationReference "),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3c58a01aa9c423548e06fe9797a73efd",
                                                        "ad15646696186c55840c123cd35ca266"}), "d063b129eff74b5697fbb4e264617c65", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I call the land registy API"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "efcb76549feacd53bdfcc191257b1568",
                                                        "ad15646696186c55840c123cd35ca266"}), "fcfa7b0cb479e359b03a6dac4a2588e7", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should recieve a LandregistryDTO response ")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@API-ApplicationEnquiry", "52e95c6869096d519e443a7569d940e8")}), new System.Collections.Generic.List<string>(new string[] {
                                        "b3552b65b5f64c5e966de04fa33bd047",
                                        "ad15646696186c55840c123cd35ca266"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("d6c5dd1880be5c53a539111d448d3655", "ApplicationEnquiry.feature", "API-ApplicationEnquiry", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "42e31dabc5d48f5794ab43fa4f6ae651",
                                                        "ea66e0531b38325fb2cc9e6ecdfd9016"}), "7eccdbf75e544654a8e5e4fe711be641", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "UniqueMsgId access-denied"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5ea05720980e6556a0f602024c001621",
                                                        "ea66e0531b38325fb2cc9e6ecdfd9016"}), "9e0577fec349605d9baea16dcd5f22cf", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "TitleNumber DN100"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e630489701feab50b29187d89e48e1be",
                                                        "ea66e0531b38325fb2cc9e6ecdfd9016"}), "8622ea35d4b3f25eafd2e0757e30dba1", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ClosedAndContinued Flag True"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "37726f71e25ad854979e0037e7e0f051",
                                                        "ea66e0531b38325fb2cc9e6ecdfd9016"}), "bba33f165f035a5bb8e50084c227cf8d", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ClosedAndContinued Flag False"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ab679dbba1c96953af938dbaf68f9683",
                                                        "ea66e0531b38325fb2cc9e6ecdfd9016"}), "6e982593c53e3951802edf470a0e0b3a", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ApplicationReference "),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3c58a01aa9c423548e06fe9797a73efd",
                                                        "ea66e0531b38325fb2cc9e6ecdfd9016"}), "630fd665a8f2ef5daf6fbc8af53cec98", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I call the land registy API"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "efcb76549feacd53bdfcc191257b1568",
                                                        "ea66e0531b38325fb2cc9e6ecdfd9016"}), "ea74085e49ffb65488dcb9d03a1c9971", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should recieve a LandregistryDTO response ")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@API-ApplicationEnquiry", "52e95c6869096d519e443a7569d940e8")}), new System.Collections.Generic.List<string>(new string[] {
                                        "b3552b65b5f64c5e966de04fa33bd047",
                                        "ea66e0531b38325fb2cc9e6ecdfd9016"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("d58ae368c375225cbf89d523d27c4cb2", "ApplicationEnquiry.feature", "API-ApplicationEnquiry", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "42e31dabc5d48f5794ab43fa4f6ae651",
                                                        "87826c0985152c5bb133bf8f4c34c421"}), "c6712695872b1856916af3c9ad021e61", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "UniqueMsgId out-of-hours"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5ea05720980e6556a0f602024c001621",
                                                        "87826c0985152c5bb133bf8f4c34c421"}), "dfb4e801db3ce959b793bbefab18c502", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "TitleNumber DN100"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e630489701feab50b29187d89e48e1be",
                                                        "87826c0985152c5bb133bf8f4c34c421"}), "3ebdf1acb8d20c5fa4546269a3f43728", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ClosedAndContinued Flag True"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "37726f71e25ad854979e0037e7e0f051",
                                                        "87826c0985152c5bb133bf8f4c34c421"}), "5ccaadd9ad829b548cfac08579a0b350", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ClosedAndContinued Flag False"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ab679dbba1c96953af938dbaf68f9683",
                                                        "87826c0985152c5bb133bf8f4c34c421"}), "9ad2a7807359305a90e68cf1cf1e07f2", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "ApplicationReference "),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3c58a01aa9c423548e06fe9797a73efd",
                                                        "87826c0985152c5bb133bf8f4c34c421"}), "f4baa62c057d5056bce483e532c6ef32", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I call the land registy API"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "efcb76549feacd53bdfcc191257b1568",
                                                        "87826c0985152c5bb133bf8f4c34c421"}), "bfcbd4943635e45197cbcb7f7c4dd1e5", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should recieve a LandregistryDTO response ")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@API-ApplicationEnquiry", "52e95c6869096d519e443a7569d940e8")}), new System.Collections.Generic.List<string>(new string[] {
                                        "b3552b65b5f64c5e966de04fa33bd047",
                                        "87826c0985152c5bb133bf8f4c34c421"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(ApplicationEnquiryFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(ApplicationEnquiryFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(ApplicationEnquiryFeature.PicklesFunc));
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("API-ApplicationEnquiry")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("API-ApplicationEnquiry")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ApplicationEnquiry")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("API-ApplicationEnquiry")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("1-MultipleReturned", "success-many-results", "DN100", "", "True", "False", "", "0", null, DisplayName="API-ApplicationEnquiry(1-MultipleReturned,success-many-results,DN100,,True,False," +
            ",0)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("2-OneReturned", "success-one-result", "DN101", "", "True", "False", "", "1", null, DisplayName="API-ApplicationEnquiry(2-OneReturned,success-one-result,DN101,,True,False,,1)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("3-AppRefOneReturned", "application-reference-one-result", "", "U565LDE", "False", "False", "", "2", null, DisplayName="API-ApplicationEnquiry(3-AppRefOneReturned,application-reference-one-result,,U565" +
            "LDE,False,False,,2)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("4-AppRefClosed30Days", "application-reference-thirty-days", "", "G665YYG", "False", "False", "", "3", null, DisplayName="API-ApplicationEnquiry(4-AppRefClosed30Days,application-reference-thirty-days,,G6" +
            "65YYG,False,False,,3)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("5-NoneReturned", "success-no-results", "DN102", "", "False", "True", "", "4", null, DisplayName="API-ApplicationEnquiry(5-NoneReturned,success-no-results,DN102,,False,True,,4)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("6-TitleIsClosed", "closed-title-number", "DN999", "", "False", "True", "", "5", null, DisplayName="API-ApplicationEnquiry(6-TitleIsClosed,closed-title-number,DN999,,False,True,,5)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("7-TitleIsClosedAndContinued", "closed-and-continue", "BK554444", "", "True", "False", "", "6", null, DisplayName="API-ApplicationEnquiry(7-TitleIsClosedAndContinued,closed-and-continue,BK554444,," +
            "True,False,,6)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("8-TitleIsNotFound", "title-number-not-found", "DY100", "", "True", "False", "", "7", null, DisplayName="API-ApplicationEnquiry(8-TitleIsNotFound,title-number-not-found,DY100,,True,False" +
            ",,7)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("9-AccessDenied", "access-denied", "DN100", "", "True", "False", "", "8", null, DisplayName="API-ApplicationEnquiry(9-AccessDenied,access-denied,DN100,,True,False,,8)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("10-OutOfHours", "out-of-hours", "DN100", "", "True", "False", "", "9", null, DisplayName="API-ApplicationEnquiry(10-OutOfHours,out-of-hours,DN100,,True,False,,9)")]
        public async global::System.Threading.Tasks.Task API_ApplicationEnquiry(string test, string uniqueMsgId, string titleNumber, string applicationReference, string closedAndContinued, string continueIfFeeExceeds, string response, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "API-ApplicationEnquiry"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Test", test);
            argumentsOfScenario.Add("UniqueMsgId", uniqueMsgId);
            argumentsOfScenario.Add("TitleNumber", titleNumber);
            argumentsOfScenario.Add("ApplicationReference", applicationReference);
            argumentsOfScenario.Add("ClosedAndContinued", closedAndContinued);
            argumentsOfScenario.Add("ContinueIfFeeExceeds", continueIfFeeExceeds);
            argumentsOfScenario.Add("Response", response);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("API-ApplicationEnquiry", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync(string.Format("UniqueMsgId {0}", uniqueMsgId), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
 await testRunner.AndAsync(string.Format("TitleNumber {0}", titleNumber), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
 await testRunner.AndAsync(string.Format("ClosedAndContinued Flag {0}", closedAndContinued), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
 await testRunner.AndAsync(string.Format("ClosedAndContinued Flag {0}", continueIfFeeExceeds), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
 await testRunner.AndAsync(string.Format("ApplicationReference {0}", applicationReference), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
 await testRunner.WhenAsync("I call the land registy API", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
 await testRunner.ThenAsync(string.Format("I should recieve a LandregistryDTO response {0}", response), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
